### ISSUE TITLE
Incremental file changes backup - feature request

### ISSUE THREAD

**Issue by phirestalker** [rear/rear#1006]
Relax-and-Recover 1.18 / Git
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

When using tar backup, if the file is changed it saves the whole file in the incremental backup. Is there any way to have a threshold setting, where if a file is larger than the setting it will backup only the changed portions of the file?

My incremental backups are 22GB because of a mysql table file that changes daily.

If not could you recommend the simplest compatible backup software that can still be used for bare metal restore and does incremental backups? If I don't notice an issue for a few days I need to be able to go "back in time".

Thank you

**Comment by jsmeix** [comment]
Only FYI in general regarding incremental backups
(I never used any kind of incremental backups myself)
you may have a look at the possibly related issues
https://github.com/rear/rear/issues/974
and
https://github.com/rear/rear/issues/952

In general regarding issues with backup tools:

Relax-and-Recover (rear) is neither a backup software nor a
backup management software and it is not meant to be one.
rear only calls an external tool that does the backup of the files
during "rear mkbackup" and its counterpart to do the restore
of the files during "rear recover" but neither backup nor restore
functionality is actually implemented in rear, cf. the section about
"Relax-and-Recover (rear) versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

Therefore  issues with backup tools usually do not belong
directly to rear.

Regarding whether or not 'tar' can backup only the changed
portions of the file?

I don't know if 'tar' has support for that.

**Comment by jsmeix** [comment]
Regarding backup is huge because it contains
huge application files like database files:

Personally I would recommend to use rear only
to backup the files of the basic operating system
but not to also backup huge application files like
databases.

Personally I would recommend to do the backup of huge
application files like databases separated from rear, cf.
https://en.opensuse.org/SDB:Disaster_Recovery#Basics
that reads (excerpts):
<pre>
In this particular case "disaster recovery" means
to recreate the basic operating system
...
In particular special third party applications
(e.g. a third party database system which often
requires special actions to get it installed and set up)
must usually be recreated in an additional separate step. 
</pre>

**Comment by jsmeix** [comment]
I think it is sufficiently answered because issues with backup tools
usually do not belong directly to rear.

**Comment by jsmeix** [comment]
Regarding a backup tool that can backup
only the changed portions of the file
you may follow what goes on here
https://github.com/rear/rear/issues/1030

https://borgbackup.readthedocs.io/en/stable/index.html
reads
<pre>
BorgBackup (short: Borg) is a deduplicating backup program.
...
Deduplication based on content-defined chunking is used
to reduce the number of bytes stored: each file is split into
a number of variable length chunks and only chunks that
have never been seen before are added to the repository.
</pre>

**Comment by gozora** [comment]
@jsmeix Did you notice that both issues (#1030 and #1006) are opened by same person? ;-)

**Comment by jsmeix** [comment]
I did not notice it.
My comment makes the issues referenced by each other
so that now also others can notice their relationship ;-)
