### ISSUE TITLE
 Relax-and-Recover (rear) release 1.19 preparation

### ISSUE THREAD

**Issue by gdha** [rear/rear#1018]
# Relax-and-Recover (rear) release 1.19 preparation

* rear version (/usr/sbin/rear -V): 1.19
* OS version (cat /etc/rear/os.conf or lsb_release  -a): n/a
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): n/a
* Place-holder for new release of Relax-and-Recover (rear) release 1.19 - what may we not forget

I would suggest that we freeze our **master** code and only update some pieces of the documentation (if required) so we can have a clean release within a week or so. Suggestion are welcome.

We should only accept from now until the release **critical** and **security** bugs for _rear-1.19_.

**Comment by jsmeix** [comment]
Good grief!
It is assigned also to me but I don't know
what you @gdha expect from me to do here.
But of course I like to help you as good as I can.

@gdha 
which of the steps in
https://github.com/rear/rear/wiki/Release-process
should I do?

Personally since https://github.com/rear/rear/issues/953
is fixed (i.e. since it "just works" for me on SLE12-SP2)
a rear-1.19 release is fine for me.

**Comment by gdha** [comment]
@jsmeix You should just be aware of the fact that we are in a freeze period. And, perhaps, check if our documentation requires here and there a face lift?

**Comment by jsmeix** [comment]
I will check the documentation...

**Comment by jsmeix** [comment]
Currently this is the only open issue for the "Rear v1.19" milestone.

**Comment by jsmeix** [comment]
@gdha 
currently I find several files that contain UTF-8 Unicode characters:
<pre>
doc/rear-presentation.adoc: UTF-8 Unicode English text
doc/rear-release-notes.txt: UTF-8 Unicode English text
doc/user-guide/09-design-concepts.adoc: UTF-8 Unicode C++ program text
</pre>
and
<pre>
usr/share/rear/backup/DUPLICITY/default/50_make_duplicity_backup.sh: UTF-8 Unicode English text
usr/share/rear/lib/mkrescue-functions.sh: UTF-8 Unicode English text
</pre>

I think UTF-8 characters in scripts are not wanted
(they may even cause arbitrary bad failures on systems that
do not support the UTF-8 locale - e.g. during "rear recover")
so that I will fix the UTF-8 characters in scripts.

But I wonder if the English documentation really needs
UTF-8 characters - it makes it at least harder to
display the documentation for any user  on any system.
When one does not have a UTF-8 locale set arbitrary
nonsense could happen, cf.
https://en.opensuse.org/SDB:Plain_Text_versus_Locale

Therefore I would prefer if the Relax-and-Recover documentation
only uses ASCII characters that "just work" everywhere
unless there is a really good reason for locale-specific stuff.

Therefore my question:
@gdha 
do you agree that I simplify the Relax-and-Recover documentation
so that only ASCII characters are used?

**Comment by gdha** [comment]
@jsmeix be my guest ;-) I agree with you

**Comment by jsmeix** [comment]
@gdha 
regarding how one coulkd generate rear-release-notes.txt
with only ASCII output, see
https://github.com/rear/rear/pull/1025#issuecomment-251675516

**Comment by jsmeix** [comment]
With https://github.com/rear/rear.github.com/pull/6 merged
it looks o.k. for me for the 1.19 release but I did not check
the whole Relax-and-Recover documentation - this would be
a bigger task for the future.

**Comment by jsmeix** [comment]
FYI (for the future):

In general I think all Relax-and-Recover documentation sources
should be stored at one single place,
either in
https://github.com/rear/rear/tree/master/doc
or in
https://github.com/rear/rear.github.com/tree/master/documentation

If the Relax-and-Recover documentation files are needed
at several places they can be copied whereto needed
but I think the original source files (i.e. what is edited by us)
should be stored at one single place.

Furthermore I think all documentation in
https://github.com/rear/rear.github.com/tree/master/documentation
should be also provided in the rear RPM packages
which basically means all documentation in
https://github.com/rear/rear.github.com/tree/master/documentation
should be also in
https://github.com/rear/rear/tree/master/doc

Or is there a good reason why we have two separated
sources for Relax-and-Recover documentation?

**Comment by gdha** [comment]
@jsmeix I'll  try to finish up 1.19 tomorrow. Any item I might have forgotten?
PS: IMHO the web site must not be the same as the user guide or vice versa. The web site is already linking to the github pages of the user guide where possible. However, I agree we should try to avoid double information.

**Comment by jsmeix** [comment]
Currenty I am not aware of a forgotten item.

FYI
a side note or proposal regarding
"use git log --oneline to find all modifications since last release..."
on https://github.com/rear/rear/wiki/Release-process

For me the following git command results a nicer
initial output for the release notes:
<pre>
git log --format="* %s : %b %n" --topo-order
</pre>

**Comment by gdha** [comment]
As rear-1.19 has been released we can close this issue as well.
