### ISSUE TITLE
Notification feature to rear

### ISSUE THREAD

**Issue by phracek** [rear/rear#1023]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): 1.17.2
* OS version (cat /etc/rear/os.conf or lsb_release  -a): RHEL-6.8
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Brief description of the issue
Once backup is completed (rear mkbackup), customer would like to log message that "backup complete" with a timestamp and location of the backup so the result can be inserted into a database. 
* Work-around, if any

Pull Request #1022

Reference rhbz: https://bugzilla.redhat.com/show_bug.cgi?id=1377547

**Comment by jsmeix** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1377547
tells me
<pre>
You are not authorized to access bug #1377547.
To see this bug, you must first log in to an account
with the appropriate permissions.
</pre>

**Comment by jsmeix** [comment]
FWIW:
In general I think (as far as I remember) rear runs silent
(except in verbose mode) like traditional Unix programs
"no news is good news".

Personally I prefer verbosity but that is my personal
preference (and not waht rear does by default - as
far as I remember).

@gdha @schlomo 
can you comment what the default rear behaviour
should be regarding verbosity?

**Comment by jsmeix** [comment]
@phracek 
at least I need much better background information
what the intent behind is to understand the issue.

The curent implementation in
https://github.com/rear/rear/pull/1022/files
is a hack that perhaps works for this one customer
(but I don't know what his intent behind is)
but in general it is wrong because

a)
it does the
<pre>
LogPrint "Finished running $WORKFLOW workflow $BACKUP_URL `date` "
</pre>
for any workflow (in particular also for "rear mkrescue")
where no backup is made

b)
we would get a somewhat duplicate messaging
<pre>
Log "Finished running $WORKFLOW workflow"
LogPrint "Finished running $WORKFLOW workflow $BACKUP_URL `date` "
</pre>
with "Finished running $WORKFLOW workflow" two times.

Summary:

From my point of view in its current state
both the issue and its implementation
look rather crude.

@phracek 
in general have a look at
https://github.com/rear/rear/wiki/Developers-Guide

**Comment by jsmeix** [comment]
Typo correction - I meant:
in general have a look at
https://github.com/rear/rear/wiki/Coding-Style

**Comment by jsmeix** [comment]
This issue is not for the 1.19 release (=> "Rear future").

For a future release (hopefully for 1.20) I will try to clean up
messaging in general, cf. https://github.com/rear/rear/issues/885
and https://github.com/rear/rear/issues/887

**Comment by jsmeix** [comment]
According to
https://github.com/rear/rear/pull/1022#issuecomment-255162154
and
https://github.com/rear/rear/pull/1022#issuecomment-255323450
this issue is fixed
in rear 1.19 via POST_BACKUP_SCRIPT, cf.
https://github.com/rear/rear/pull/977
