### ISSUE TITLE
Point-In-Time-Restore

### ISSUE THREAD

**Issue by dcz01** [rear/rear#1059]
# Point-In-Time-Restore

* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.19 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a):
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6

What about the idea of restoring with rear to an point-in-time?
So that the user can select or enter an date of point-in-time and the scripts selects the nearest full backup and the last differential backup if the date is not the full backup itself.

**Comment by gozora** [comment]
Hi,
Since a week or two, ReaR can use [BorgBackup](https://borgbackup.readthedocs.io/en/stable/index.html) as backed. Maybe you can give it a try. 
This might be a good point to [start](https://github.com/rear/rear/blob/master/doc/user-guide/04-scenarios.adoc#bootable-iso-with-borg).

V.

**Comment by didacog** [comment]
Hi,
From DRLM, we have plans to implement a way to be able to select available backups in DRLM to restore from rear, is not yet implemented but we have it on our wishlist/to-dolist.

;)

**Comment by schabrolles** [comment]
Hi,
It is usually possible when running ReaR with a Backup Solution such as IBM Spectrum Protect (TSM).
I've tested it, it works well.

**Comment by gdha** [comment]
@dcz01 Point-in-Time recovery is possible with many backup integrations that REAR supports (NBU, TSM, DP, NSR, BAREOS, BACULA to name a few). Only the internal backup programs (like tar and rsync) do not support this feature in REAR.
Does this answer your question?

**Comment by jsmeix** [comment]
Regarding full backup and differential backup
see the current ReaR documentation, e.g.
https://github.com/rear/rear/blob/master/doc/rear.8.adoc
and
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf
<pre>
The current implementation supports only to restore
one full backup plus one single incremental backup
so that currently "BACKUP_TYPE=incremental"
actually implements a differential backup
</pre>
cf. https://github.com/rear/rear/issues/974

@dcz01 
according to https://github.com/rear/rear/issues/974
it seems you actually use "BACKUP_TYPE=incremental"
with "BACKUP_PROG=tar".

I think it would be best when you implement support
for point-in-time-restore with 'tar' in ReaR and
do a GitHub pull request.

I am not a user of "BACKUP_TYPE=incremental" but as far
as I can imagine it seems a precondition to select a backup
is that more than one backup.tar.gz is supported in ReaR
(currently only one is supported in ReaR).


In general regarding issues with the backup:

Relax-and-Recover is neither a backup software nor a
backup management software and it is not meant to be one, cf.
"Relax-and-Recover (rear) versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

This means issues regarding the backup usually
do not belong directly to ReaR but more to the particular
backup tool that is used by ReaR.

It is very different to what extent support for each
individual backup tool is implemented in ReaR
because support for each individual backup tool
is implemented separated from each other, cf.
https://github.com/rear/rear/pull/1048#issuecomment-255713645
and subsequent comments.

Usually only basic support for the various backup tools
is implemented in ReaR (i.e. plain making a backup during
"rear mkbackup" and plain restore during "rear recover")
but even that is sometimes only "very basic", cf.
https://github.com/rear/rear/issues/823

This means when a particular backup tool
supports point-in-time-restore it is usually
not (yet) implemented in ReaR, cf.
"How to adapt and enhance Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

The general basic question is if more and more backup related
features should be added to ReaR because each feature requires
that someone volunteers to continuously maintain that feature
in the future (i.e. fix bugs and adapt it for future changes).

In general see also
https://github.com/rear/rear/issues/769

**Comment by dcz01** [comment]
Well i think i understand it now that i should use and external backup program like tsm for backup and restore and the simply internal backup solution will not be extended with something like that.
Then i will close it here now. But thanks for all the answers.
