### ISSUE TITLE
in messages/syslog we find "DONE: rc=0" after a rear run - make it more meaningful

### ISSUE THREAD

**Issue by gdha** [rear/rear#1089]
#### Exit code in messages file improvement

* rear version (/usr/sbin/rear -V): v2.0
* OS version (cat /etc/rear/os.conf or lsb_release  -a): n/a

example:
````
# grep DONE /var/log/messages
Nov 25 17:20:45 client rear[14341]: DONE: rc=0
````
Would be better to see something like: `Workflow backup: rc=0`
Are there any other (better) suggestions?

**Comment by jsmeix** [comment]
@gdha 
what does 'rc' mean here?

According to
http://superuser.com/questions/173165/what-does-the-rc-in-bashrc-etc-mean
http://unix.stackexchange.com/questions/111611/what-does-the-rc-stand-for-in-etc-rc-d
https://en.wikipedia.org/wiki/Run_commands
usually 'rc' means "run commands" which cannot be menat here.

I guess here 'rc' could mean "return code" but this is not a function
so that I would prefer to name it as what it actually is: "exit code"

I suggest the following in usr/sbin/rear
<pre>
if test $EXIT_CODE -eq 0 ; then
    LogToSyslog "$PROGRAM $WORKFLOW finished with zero exit code"
else
    LogToSyslog "$PROGRAM $WORKFLOW failed with exit code $EXIT_CODE"
fi
</pre>
Note that I do not use "succeeded with zero exit code"
to avoid false hope because a zero exit code does
not necessarily mean that everything was o.k.

**Comment by jsmeix** [comment]
By the way:
@gdha @schlomo 
do you know why the help workflow sets EXIT_CODE=1
in lib/help-workflow.sh?
According to "git log -p usr/share/rear/lib/help-workflow.sh"
that was implemented by Schlomo Schapiro in
https://github.com/rear/rear/commit/f57be9070cb8ad8692497d0baedf364b47ac7a8d

**Comment by jsmeix** [comment]
Regarding help workflow sets EXIT_CODE=1 see
https://github.com/rear/rear/pull/1126

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1126 merged
the help workflow exits now with zero exit code.

**Comment by jsmeix** [comment]
For the ReaR 2.0 major version bump
there can be changes in the texts so that I implemented
https://github.com/rear/rear/issues/1089#issuecomment-266983001
via
https://github.com/rear/rear/pull/1130
that I will merge tomorrow if there are no objections.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1130 merged
I consider this issue to be fixed, cf.
https://github.com/rear/rear/issues/1073#issuecomment-267555036
