### ISSUE TITLE
ReaR on Raspberry Pi: Rear package for ARM

### ISSUE THREAD

**Issue by ArnoutVerbeken** [rear/rear#1197]
Hello,

I want to install REAR on an Raspberry3 on Debian Jessie (Raspbian actually), but I can't find suitable package for ARM (for v2.0)

Is it available anywhere?  Or how should I install?

Thanks

**Comment by gozora** [comment]
Hi @ArnoutVerbeken ,

I don't know if there are some packages for RPI.
But ReaR is pure bash script, all you need is to download ReaR e.g. from https://github.com/rear/rear/releases, untar it and run `make install`.

This should do the trick.

V.

**Comment by gdha** [comment]
@ArnoutVerbeken How do you plan to boot from the rescue image?

**Comment by ArnoutVerbeken** [comment]
@gdha I was thinking about a bootable USB stick and then restore to SDcard..?

**Comment by didacog** [comment]
@gdha 

I have plans to do some testings on ARM platforms in near future, I cannot assign me any issue, but I can update this issue when I finish those tests with my results if you are agree.

Also I cannot guarantee any dates to finish my tests :-P

Anyway I can say now that if the SDcard is detected as mmc device, ReaR cannot recreate layout for it because this:

**/usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh**
<pre>
    for disk in /sys/block/* ; do
        blockd=${disk#/sys/block/}
        if [[ $blockd = hd* || $blockd = sd* || $blockd = cciss* || $blockd = vd* || $blockd = xvd* || $blockd = dasd* || $blockd = nvme* ]]
</pre>

Kind regards,

**Comment by gdha** [comment]
Indeed, new architectures require new pre-requisites. Looking forward to pull requests.

**Comment by ArnoutVerbeken** [comment]
So if I understand it right, not much I can do right now, except being patient and being a tester if needed?

**Comment by jsmeix** [comment]
Since https://github.com/rear/rear/pull/1662 is merged
I consider this issue to be at least initially solved.

Now since @Lukey3332 implemented the basics for ARM support
it should be relatively easy for other ARM users to further
enhance and adapt that to support more ARM devices
in particular Raspberry Pi.

**Comment by jsmeix** [comment]
@ArnoutVerbeken 

FYI:

How you could test the current ReaR GitHub master code:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

In general regarding how to work on issues in ReaR
see the sections
"Debugging issues with Relax-and-Recover"
"How to adapt and enhance Relax-and-Recover"
"How to contribute to Relax-and-Recover"
at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by Danrancan** [comment]
Has anyone been able to solve this issue? Why was this closed? OUTPUT=PXE is the only support for ARM. Can we develop a full raspberry pi implementation of this?

**Comment by gdha** [comment]
@Danrancan Unfortuntely, no-one contributed any ARM64 code for ReaR as far as I know except for the message around PXE booting. However, the PXE booting itself is not the biggest hurdle, but recovering the PI itself:
- the rescue image creation
- the different disk types are tricky
- make the target PI bootable again
- and other unkowns

The question these days is who is willing to spent time on this for free? Via a team of persons it might be possible...
