### ISSUE TITLE
Extend script with manual optimal aligned partitioning for USB flash/SSD media

### ISSUE THREAD

**Issue by ProBackup-nl** [rear/rear#1201]
* rear version (/usr/sbin/rear -V):
Relax-and-Recover 2.00 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
n/a
* Are you using legacy BIOS or UEFI boot?
UEFI
* Brief description of the issue:
USB flash memory sticks and possibly SSD in USB adapters don't supply alignment information to the Linux kernel. As a result the USB medium partitioning more often far from an optimal alignment then that these devices are optimally aligned.
* Work-around, if any:
Manual edit usr/share/rear/format/USB/default/300_format_usb_disk.sh
and change the parted command to something like 
`parted -s $RAW_USB_DEVICE mkpart primary ~~2~~4Mib "$((~~2~~4 + ${USB_UEFI_PART_SIZE}))"Mib ...`
for the ~~2097152 byte~~4MiB optimal alignment as derived by `flashbench` for a "Sandisk Cruzer Force 16GB" USB stick.

This issue also applicable for the optimal sector and node size, where an adaptation in the command `mkfs …` will likely improve performance and reduce wear for thumb drives.

**Comment by jsmeix** [comment]
Alignment according to physical block size
is a very good thing!

2097152 bytes (i.e. 2 MiB) looks unexpected small to me.
As far as I know usual flash storage operates with
a physical block size of 4 MiB or 8 MiB - nowadays
perhaps even 16 MiB on huge flash storages,
cf. my last comment on
https://hackweek.suse.com/15/projects/23

Because during "rear format" we can do what we want
(in contrast to "rear recover" where we must by default
recreate the system exactly as it was before)
I suggest to simply align at 8 MiB during "rear format"
in any case.
Who cares nowadays about a few unused MiB
at the beginning of a mass storage device?

**Comment by jsmeix** [comment]
See also the related issues
https://github.com/rear/rear/issues/102

See also in the parted manual
https://www.gnu.org/software/parted/manual/parted.html
<pre>
how to partition a low-end flash device
(“low-end”, as of 2011/2012).
For such devices, you should
use 4MiB-aligned partitions (2)
...
(2)
Cheap flash drives will be with us
for a long time to come, and, for them,
1MiB alignment is not enough.
Use at least 4MiB-aligned partitions.
For details, see Arnd Bergman’s article,
http://lwn.net/Articles/428584/
and its many comments.
</pre>

FYI:
Regarding why during "rear recover"
we must try to recreate the partitioning
exactly as it was before see
https://github.com/rear/rear/issues/1078#issuecomment-266099227
and the subsequent comments, in particular
https://github.com/rear/rear/issues/1078#issuecomment-266378990

**Comment by jsmeix** [comment]
Something like
<pre>
parted -s $RAW_USB_DEVICE mkpart primary 8Mib "$((8 + ${USB_UEFI_PART_SIZE}))"Mib ...
</pre>
cannot work well because if e.g. USB_UEFI_PART_SIZE is 7 MiB
it still results bad alignment for the ReaR data partition.
We need "more intelligent" code that rounds
the user-specified values to 8 MiB chunks, cf.
https://github.com/rear/rear/issues/102#issuecomment-149175705

**Comment by ProBackup-nl** [comment]
Indeed 2 MiB was too small. I am still struggling with correctly interpreting `flashbench` output. I do agree that rounding user input to 8 MiB chunks is necessary.

**Comment by ProBackup-nl** [comment]
And this wish also request for some **variable** that allows inserting **additional parameters** for the **mkfs** command at usr/share/rear/format/USB/default/300_format_usb_disk.sh.

As an example how I modified that file after running Linaro's flashbench on the Sandisk Cruzer Fit:
```
-mkfs.$USB_DEVICE_FILESYSTEM -L REAR-000 ${RAW_USB_DEVICE}${ParNr} >&2 || Error "Failed to create $USB_DEVICE_FILESYSTEM filesystem on '${RAW_USB_DEVICE}${ParNr}'"
+mkfs.$USB_DEVICE_FILESYSTEM -L REAR-000 -b 4096 -E stride=8,stripe-width=256 -O sparse_super,^has_journal ${RAW_USB_DEVICE}${ParNr} >&2 || Error "Failed to create $USB_DEVICE_FILESYSTEM filesystem on '${RAW_USB_DEVICE}${ParNr}'"
```

**Comment by FGrose** [comment]
@ProBackup-nl:  Have you replicated the flashbench findings on other devices of varying size and source to confirm the applicability of those results for other units?

**Comment by ProBackup-nl** [comment]
@FGrose Yes, I have verified using `flashbench` that the above values are **not applicable to other USB flash drives**. The above code is just an **example**.

I need something like:
`+mkfs.$USB_DEVICE_FILESYSTEM -L REAR-000 ${USB_DEVICE_FILESYSTEM_PARAMS} ${RAW_USB_DEVICE}${ParNr} >&2 || Error "Failed to create $USB_DEVICE_FILESYSTEM fil...`

**Comment by ProBackup-nl** [comment]
@jsmeix "more intelligent" code that rounds to chunks has been implemented in pull request #1217

**Comment by jsmeix** [comment]
@ProBackup-nl 
many thanks for your contribution!

@FGrose 
see https://github.com/rear/rear/pull/1217
by default USB_DEVICE_FILESYSTEM_PARAMS
is empty.
The basic idea behind such variables is to give the user
a mean of "final power" so that the user can specify
if needed what ReaR will actually do, cf.
"too much secretly working 'magic automatisms' in ReaR" in
https://github.com/rear/rear/pull/1204#issuecomment-282252947

**Comment by jsmeix** [comment]
With
https://github.com/rear/rear/pull/1217
merged, this issue should be fixed.
