### ISSUE TITLE
Can't 230_run_efibootmgr.sh in folder Linux-i386 be moved to default?

### ISSUE THREAD

**Issue by ProBackup-nl** [rear/rear#1238]
* rear version : 2.00 git
* OS version (lsb_release -a):
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
* UEFI boot
* Brief description of the issue: No execution of 230_run_efibootmgr.sh upon `rear mkrescue` for GNU/Linux.

What could be the reason(s) to **not** move `230_run_efibootmgr.sh` from folder `Linux-i386` to folder `default`?

--- 
Reasons to do move this run_efibootmgr script:

 * This script itself starts with a `is_true $USING_UEFI_BOOTLOADER || return` check.
 * There might not be UEFI support on the PPC platform, but there are a lot more environments with UEFI boot then just `Linux-i386`.

**Comment by jsmeix** [comment]
@ProBackup-nl 
in general see
https://github.com/rear/rear/issues/1214#issuecomment-286056772
<pre>
Caution with moving a script to 'default' because then
this script is sourced in any case.
I would recommend to better set one of those zillions
of variables right for Arch Linux so that
finalize/Linux-i386/230_run_efibootmgr.sh
gets sourced.

How to set those variables right for Arch Linux see
the SetOSVendorAndVersion function in
lib/config-functions.sh
</pre>

Regarding other environments with UEFI boot than Linux-i386:

I am not at all a UEFI boot expert but I assume that the
current scripts only work for 'Linux-i386' like environments.
I assume that UEFI scripts for other environments
are not like 'Linux-i386' so that then UEFI scripts for
other environments should be in separated directories
that match the other environments.

@gozora @gdha 
what is your opinion here?

**Comment by ProBackup-nl** [comment]
There is little/no purpose for moving a finalize script, to make it run in the `mkrescue` process because the `finalize` phase is intended for the `recover` instead of `mkrescue` process.
