### ISSUE TITLE
How to avoid the copy of ISO (rescue +data) under /var/lib/rear/output ?

### ISSUE THREAD

**Issue by jfucanada** [rear/rear#1281]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V):
* OS version (cat /etc/rear/os.conf or lsb_release -a):
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue:
* Work-around, if any:

My local.conf is as below.

OUTPUT=ISO
OUTPUT_URL=null
BACKUP=NETFS
BACKUP_URL=iso:///mondo
SSH_ROOT_PASSWORD="redhat"
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/mondo' '/var/tmp' '/var/crash')
#NETFS_KEEP_OLD_BACKUP_COPY=

**Comment by jfucanada** [comment]
My version is Relax-and-Recover 2.00 / Git

OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6

**Comment by jsmeix** [comment]
@jfucanada 
perhaps you misunderstand what OUTPUT_URL=null
actually does?

For some background information you may have a look at
https://github.com/rear/rear/issues/734
and also see the other issues mentioned therein.

Accordingly you cannot avoid the local ISO because
currently there is no support in ReaR that ReaR
creates its ISO directly on a remote location.
You can only avoid that the locally generated ISO
gets afterwards copied to a remote location.

**Comment by gdha** [comment]
@jfucanada I think the solution you are looking for is described in issue #802

**Comment by jsmeix** [comment]
@gdha 
I do not know what exactly @jfucanada is asking for.

I assumed @jfucanada likes to avoid
that the ISO exists in a local directory
(which is by default /var/lib/rear/output).

If @jfucanada only likes to change the default directory
where the local ISO gets stored, ISO_DIR helps.

With ISO_DIR I could only specify a local directory
where the ISO is created like
<pre>
ISO_DIR="/tmp/myISOdir"
</pre>
but I failed to specify a remote place for the ISO
(i.e. so that one never has the ISO locally).

Even manually mounting e.g. a NFS share
using ISO_DIR as mountpoint like
<pre>
ISO_DIR="/tmp/nfsISOdir"
PRE_BACKUP_SCRIPT="mkdir -v -p $ISO_DIR ; mount -v -t nfs -o $OUTPUT_OPTIONS 10.160.4.244:/nfs/$HOSTNAME $ISO_DIR"
POST_BACKUP_SCRIPT="umount $ISO_DIR"
</pre>
does not work
because backup/default/990_post_backup_script.sh
that umounts the NFS share from ISO_DIR
is run before output/ISO/Linux-i386/800_create_isofs.sh
that creates the ISO - now in the local ISO_DIR
so that one gets in the end still a local ISO:
<pre>
# ls -lh /tmp/nfsISOdir/rear-e205.iso
-rw------- 1 root root 1.3G Apr  7 15:08 /tmp/nfsISOdir/rear-e205.iso
</pre>

In local.conf I even tried things like
<pre>
export TMPDIR="/tmp/myReaRtmpdir"
ISO_DIR="$TMPDIR/rear.*/myISOdir"
</pre>
and
<pre>
ISO_DIR=nfs://10.160.4.244/nfs/$HOSTNAME
</pre>
but that did not work - as expected when looking briefly
at the code about ISO_DIR which basically does
<pre>
mkdir -p "$ISO_DIR"
</pre>

**Comment by jsmeix** [comment]
Mainly for my own information
why the 'output' stage is usually before the 'backup' stage see
https://github.com/rear/rear/issues/1283#issuecomment-293205009
(excerpt):
<pre>
... there is a reason why the output workflow
is before the backup workflow and that is OBDR
(however, is anyone still using that?)
</pre>
