### ISSUE TITLE
ReaR website: development documentation: include how to make a branch stay in sync with upstream

### ISSUE THREAD

**Issue by ProBackup-nl** [rear/rear#1304]
http://relax-and-recover.org/development/ gives a nice example how to contribute.

However the example doesn't work very well for branches that live longer then a week. These branches tend to become 100+ commits behind master, causing merge conflicts etcetera.

Please include some hints how to stay up to date with upstream/master code.
`$ git pull upstream master`?

**Comment by jsmeix** [comment]
I am not at all a git expert but I could at least document how I do it.
Hopefully I find some time during May or later but no promises...

**Comment by schlomo** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by jsmeix** [comment]
My favorite article is:

https://2buntu.com/articles/1459/keeping-your-forked-repo-synced-with-the-upstream-source/

I like that most because it explains "all in one" single article.

I think such links could be added to
http://relax-and-recover.org/development/
only as a courtesy for ReaR contributors.
Of course
http://relax-and-recover.org/development/
is not meant as exhaustive explanation how to use git
or how to work with GitHub but some useful links
for more information would be nice.

**Comment by jsmeix** [comment]
@schlomo 
many thanks for adding the link!
