### ISSUE TITLE
IDEA: Automatically eject CDROM

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1361]
This would have helped me in the [workshop](https://github.com/schlomo/rear-workshop).

Idea is to create a new variable `ISO_EJECT` that would eject the CD after recovery or before rebooting.

Effectively prevents a boot loop when using `ISO_DEFAULT=manual`

**Comment by jsmeix** [comment]
Only a side note for the fun of "eject CD":

In ancient S.u.S.E. times there was the default that after
the S.u.S.E. Linux installation was done the installation CD
was automatically ejected but we got unfriendly user complaints
so that we switched to the current default to boot from harddisk.

What I like to say is that a physical "eject CD"
may cause trouble for some users.

But with ISO_EJECT="no" by default everything should be o.k.

I never used ISO_DEFAULT other than the default "boothd"
but I wonder if "eject CD" also works on virtual machines?
