### ISSUE TITLE
Creating ext2/3/4 filesystem on whole disk requires answering y without prompt

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1386]
See the `y` that the user had to enter to continue the recovery process:
![image](https://user-images.githubusercontent.com/101384/27327308-85610a18-55ae-11e7-96c8-885cab24a7d9.png)

I'll fix this issue with the next release.

**Comment by jsmeix** [comment]
Good grief!
Many thanks for finding that special case!
I think this explains why '>&2' was not used
for 'mkfs' commands, cf.
https://github.com/rear/rear/issues/885#issuecomment-226784037
(excerpt)
<pre>
You will notice that the mkfs commands do
not have >&2 appended (I guess that was done
on purpose so that the user see something on the screen).
</pre>
Now we do no longer need to guess what that purpose was ;-)

**Comment by jsmeix** [comment]
@schlomo 
out of curiosity: How do you intend to fix it?

If the current '>&2' is removed from the 'mkfs' calls
it leads usually (i.e. when it does not need a 'y' response)
to unintended blabber on stdout, see what I got for btrfs
https://github.com/rear/rear/issues/885#issue-160886808

**Comment by schlomo** [comment]
I plan to add `-F` to the mkfs calls. IMHO any mkfs output should rather go to the logfile. If it fails then the user should expect to find all relevant infos there. If it doesn't fail then the output of mkfs is not interesting.

**Comment by jsmeix** [comment]
I fully agree!

In https://github.com/rear/rear/wiki/Coding-Style added a
"Careful with tools that may (sometimes) prompt for user input!"
to the "What to do with stdout and stderr" section.
