### ISSUE TITLE
Could endianness on POWER make a difference for ReaR?

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1490]
@schabrolles 
I got a question about ReaR on POWER big-endian
versus on POWER little-endian.

Because ReaR is only bash scripts I assume the plain
byte ordering does not make a difference so that
I assume the ReaR bash scripts work same on
POWER big-endian and little-endian.

But there might be other differences between POWER big-endian
and POWER little-endian that could make a difference for ReaR
on POWER big-endian versus on POWER little-endian.

Do you know if ReaR works same on POWER big-endian
and on POWER little-endian or are there special adaptions
needed for big-endian versus little-endian?

**Comment by schabrolles** [comment]
@jsmeix You are absolutely right. ReaR code is not "endian sensitive" because it is based on Shell and not a compiled binary.

I currently test ReaR on Power on:

- Suse 11 SP4 => Big-Endian
- Suse 12 SP2 => Little-Endian
- Rhel 7.3 => Little & Big Endian
- Ubuntu 16.04 => Little Endian

There is no really a something specific due to endianness for ReaR, but more on the difference between Linux distro / generation.

New Linux distribution are now using grub2 bootloader (Suse12 / ubuntu / Rhel7) while older distro still use Yaboot/Lilo (Rhel6/Sles11). 
Because Suse12 / ubuntu / Rhel are available in ppc64le (Little Endian), we can conclude that all LE Linux on Power Version are using grub2 bootloader.
But we cannot say that BE Linux is using only Yaboot/Lilo (like rhel6,sles11) because rhel 7, which use grub2, is also available in BE.

Currently, all this differences are already managed by ReaR code.

**Comment by jsmeix** [comment]
@schabrolles 
many thanks for your prompt and even explanatory answer.
You helped me a lot!
