### ISSUE TITLE
"rear mkrescue" useless/dangerous in case of backup on ISO

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#1547]
This is a follow-up of https://github.com/rear/rear/issues/1545

Current ReaR master code:

Summary:
When I do a backup on the ISO via "rear mkbackup"
then recovery via "rear recover" works.
But "rear mkrescue" with
<pre>
BACKUP_URL="iso:///mybackup"
</pre>
is useless and even dangerous because such an ISO can
never work later for "rear recover" because a non-working
backup URL is stored in that recovery system.

Doing "rear recover" with such a "rear mkrescue" ISO fails with
<pre>
RESCUE e205:~ # rear -d -D recover
...
ERROR: Backup archive 'backup.tar.gz' not found.
Aborting due to an error, check /var/log/rear/rear-e205.log for details
</pre>
In case of "rear mkrescue" there is no backup in the ISO
so that such an ISO is useless because it can never work
unless the backup is actually in the ISO.

Therefore backup in the ISO via something like
<pre>
BACKUP_URL="iso:///mybackup"
</pre>
conflicts with "rear mkrescue" so that the mkrescue workflow
must be forbidden when the backup is configured to be in the ISO.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1549 merged
this issue should be fixed.

**Comment by Testicule** [comment]
The mkrescue iso is not "useless", just because it does not include backup.tar.gz

Just boot onto it, setup network interface, and then edit the local.conf to change the BACKUP_URL and/or other parameters to point to your backup on a network share. Or set REQUESTRESTORE, so you can restore the backup.tar manually.

The iso is still *extremely* useful, as it sets up disks and partitioning and gives you an environment that can restore from network shares, and then tweaks all your files and re-installs grub.
