### ISSUE TITLE
NEtbackup Restore failed on RHEL 7 with error standard policy restore error.

### ISSUE THREAD

**Issue by shail1774** [rear/rear#1707]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.00 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
BACKUP=NBU
OUTPUT=ISO
OUTPUT_URL=

* Are you using legacy BIOS or UEFI boot? :- BIOS
* Brief description of the issue: Unable to restore from Netbackup getting standard policy  restore error
We have installed rear package through redhat 7 repo and configured the local.conf to  integrate the rear backup with netbackup.

Netbackup team successfully take OS full backup and we successfully create ISO with rear mkrecover command.

We boot the server with ISO and seletct first option "Recover "Hostname"" which leads to start the restoration after asking the username and 2 times enter to take default option (Hostname and last full backup) but it went fail with standard policy  restore error.

We have checked with network there is no firewall or port blocked between netbackup servers and test servers.

Could you please guide us to resolve this issue.
* Work-around, if any:

**Comment by jsmeix** [comment]
@shail1774 

I do not use any of the third-party backup tools
so that I can neither reproduce any issue nor fix or
enhance things that are related to third-party backup tools.

In general regarding third-party backup tools and ReaR see
"Relax-and-Recover versus backup and restore" at
https://en.opensuse.org/SDB:Disaster_Recovery

Perhaps there is another ReaR user here who uses
BACKUP=NBU stuff (Symantec/Veritas NetBackup)
who could help you with BACKUP=NBU specific issues.
If not you would have to debug this issue on your own.

In general regarding debugging issues with ReaR see
"Debugging issues with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by gdha** [comment]
@shail1774 As we do not have the required equipment and tools I've added the label "needs sponsorship"  Perhaps, someone can help you with an in-depth NBU knowledge?

**Comment by gdha** [comment]
@shail1774 if you have a RH subscription contract you could open a support case at RH for further assistance as you are using the rear version from RHEL7 repo.
