### ISSUE TITLE
Option '-C' not mentioned in Release Notes

### ISSUE THREAD

**Issue by gdha** [rear/rear#1726]
Brought to my attention via gitter: (from @CFCombs)

* rear version (/usr/sbin/rear -V): 1.17.2
* Brief description of the issue:
Using Multiple Backups for Relax-and-Recover - but I have found the issue. The -C option to specific a different configuration file does not exist in ver 1.17. I've installed ver 2.3 and the -C works. Curious why this change was never called out in the release notes anywhere.

**Comment by jsmeix** [comment]
In
http://relax-and-recover.org/documentation/release-notes-2-3
I found
<pre>
Product Features
...
Multiple backup methods (read the documentation
https://github.com/rear/rear/blob/master/doc/user-guide/11-multiple-backups.adoc)
.
.
.
Version 2.00 (January 2017)
...
Multiple backups are now possible (issues #1088, #1102, #1096) - see
the documentation page
https://github.com/rear/rear/blob/master/doc/user-guide/11-multiple-backups.adoc
(New)
</pre>
and same in
http://relax-and-recover.org/documentation/release-notes-2-2
http://relax-and-recover.org/documentation/release-notes-2-1
http://relax-and-recover.org/documentation/release-notes-2-00
but not in
http://relax-and-recover.org/documentation/release-notes-1-19
and older.

From my point of view Multiple Backups are sufficiently documented
since they exist.
