### ISSUE TITLE
Missing ReaR RPM for SLES 12 SP3

### ISSUE THREAD

**Issue by gozora** [rear/rear#1732]
Hi @gdha, @jsmeix 

Is there any particular reason why we are missing ReaR RPM for SLES12 SP3 ?

V.

**Comment by gdha** [comment]
I enabled the missing SLES12 SP3 on OBS - it should have been builded by now. I still need to update our Download page

**Comment by gozora** [comment]
Thank you, kind sir! ;-)

V.

**Comment by gozora** [comment]
I can now see SLES12 SP3 packages under: https://download.opensuse.org/repositories/Archiving:/Backup:/Rear/SLE_12_SP3/x86_64/

V.

**Comment by jsmeix** [comment]
@gozora 
in general regarding a 'rear' RPM for a specific Linux distribution version.
Because ReaR is only bash scripts it should not matter in practice
which 'rear' RPM you download and use because ReaR is meant
to also work when you "git clone" the plain GitHub sources,
cf. "it should not matter for which SUSE product you use ReaR" in
https://github.com/rear/rear/issues/1724#issuecomment-363446158

**Comment by rakon2** [comment]
while taking backup also we are getting below notification 
Driver 'xennet' for 'eth0' not loaded - is that okay? for rear

due to this unable to create vm through xl create and u nable to do recover 
used all below rears


  | Name | Last modified | Size | Metadata
-- | -- | -- | -- | --

  | Parent Directory |   | - |  
  | rear-1.17.2-1.x86_64.rpm | 16-Feb-2018 08:33 | 317K | Details
  | rear-1.18-3.x86_64.rpm | 16-Feb-2018 08:33 | 346K | Details
  | rear-1.19-2.x86_64.rpm | 16-Feb-2018 08:33 | 367K | Details
  | rear-2.00-1.x86_64.rpm | 16-Feb-2018 08:33 | 386K | Details
  | rear-2.1-2.x86_64.rpm | 16-Feb-2018 08:33 | 423K | Details
  | rear-2.2-5.x86_64.rpm | 16-Feb-2018 08:33 | 434K | Details
  | rear-2.3-1.x86_64.rpm | 16-Feb-2018 08:33 | 467K | Details

**Comment by jsmeix** [comment]
@rakon2
please do not post unrelated stuff here.
This issue is done and closed.
Use separated GitHub issues for separated things.
