### ISSUE TITLE
Unattended PXE recover mode with BAREOS halts after restore

### ISSUE THREAD

**Issue by gdha** [rear/rear#1762]
* rear version (/usr/sbin/rear -V): 2.3 and higher
* OS version (cat /etc/rear/os.conf or lsb_release -a): RHEL, SLES
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): BACKUP=BAREOS
* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue: When using PXE to recover unattended with BAREOS we get a prompt after a successful restore if we want to continue or inspect with shell? That is not the desired state we expected.
* Work-around, if any:
Problem is found in script `/usr/share/rear/restore/BAREOS/default/400_restore_backup.sh:if [ "$ISO_DEFAULT" != "automatic" ]` where the variable ISO_DEFAULT is not the correct one. It should have been ISO_RECOCER_MODE and PXE_RECOVER_MODE

**Comment by jsmeix** [comment]
@gdha 
which exact "prompt after a successful restore if we want to continue or inspect with shell"
do you get?

Is it the `rear_shell "Did the backup successfully restore ..."` in
usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
or is it perhaps the new UserInput RESTORED_FILES_CONFIRMATION
in the new usr/share/rear/finalize/default/020_confirm_finalize.sh
from my https://github.com/rear/rear/pull/1758

In the latter case the actual reason is that you are in MIGRATION_MODE
and then the UserInput RESTORED_FILES_CONFIRMATION
is intentionally there.

In the former case that too simple `rear_shell "Did the backup successfully restore..."`
should be replaced by a UserInput() call so that the user can predefine
a user input value in this case (i.e. so that there is no longer a hardcoded
disruptive break into the rear_shell).

**Comment by gdha** [comment]
@jsmeix I reran the test and saw MIGRATION_MODE being turned off because I was using _unattended_ mode. Therefore, I think what I thought above is correct. Will make a PR and we can retest it once available.

**Comment by gdha** [comment]
@jsmeix It was switched off -
`2018-03-21 17:33:02.606873147 Switching off manual disk layout configuration (MIGRATION_MODE) due to 'unattended' kernel option`

**Comment by jsmeix** [comment]
To Keep Separated Issues Separated (KSIS )
I could after https://github.com/rear/rear/pull/1763 was merged
enhance the `rear_shell "Did the backup successfully restore..."`
by a UserInput() call.

**Comment by jsmeix** [comment]
After having a bit closer look at the code in
usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
I (as a non-bareos user) will not touch that code
because that code is too obsuce for me.

**Comment by jsmeix** [comment]
I think with https://github.com/rear/rear/pull/1763 merged
this issue can be closed as fixed.
