### ISSUE TITLE
aarch64 architecture   kylin OS  not support  output=iso ?

### ISSUE THREAD

**Issue by genghongxiang** [rear/rear#1772]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

*1.17.2
* OS_VENDOR=Ubuntu    OS_VERSION=4.0.2 
* OUTPUT=ISO  BACKUP=NETFS    BACKUP_URL=file:///mnt/rear_iso
* aarch64  kylin os
 rear is not  support ARM architecture  OUPUT=ISO ?   modify rear shell  make it work, but  *.iso file  can't guide

**Comment by jsmeix** [comment]
ReaR version 1.17.2 is too old.

According to
https://github.com/rear/rear/blob/master/doc/rear-release-notes.txt
that version is from August 2015.

Initial support for the ARM architecture was introduced
by @Lukey3332 via
https://github.com/rear/rear/pull/1662
that got merged in February this year (2018).

You need a more current version, cf.
http://relax-and-recover.org/download/

Because the current ReaR version 2.3
was released in December 2017
it does not provide the initial support
for the ARM architecture.

Accordingly you need to try out our current
ReaR upstream GitHub master code as follows:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

I recommend to use our current ReaR upstream GitHub master code
because that is the only place where we fix bugs and add enhancements.

If the current (limited) initial support for the ARM architecture
is insufficient for your use case you need to adapt and enhance ReaR
as you need it for your use case, see
http://relax-and-recover.org/development/
and the sections about
"Debugging issues with Relax-and-Recover"
"How to adapt and enhance Relax-and-Recover"
"How to contribute to Relax-and-Recover"
in
https://en.opensuse.org/SDB:Disaster_Recovery

Bugs in older ReaR versions are not fixed by us (i.e. by ReaR upstream).
Missing features in older ReaR versions are not backported by us.

Bugs in older ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (provided the fix can be backported)
by the Linux distributor wherefrom you got your older ReaR version.
Missing features in older ReaR versions are usually not backported
by the Linux distributor wherefrom you got your older ReaR version.
