### ISSUE TITLE
Support Question: Pipe output

### ISSUE THREAD

**Issue by namezero111111** [rear/rear#1800]
Dear folks,

we want to evaluate REAR, and want to backup a restoreable USB image to Bareos, so we can just recover that to another machine, and recover from there.

Is there a way to pipe the output of REAR into another process?

Thanks!

**Comment by gozora** [comment]
@namezero111111 

Isn't it easier to do whole backup (ReaR recovery system ISO + OS data) to USB ?

V.

**Comment by namezero111111** [comment]
Mhh... ok. Maybe this was phrased in an unfortunate way.
We are trying to use Rear to have a full BMR of some CentOS6/7 machines. This backup should be completely in Bareos, including the (custom?) boot image for each machine.
As an additional benefit, we would like to be able, if the necessity arises, to be able to restore random machines in isolated environments where they will not have access to the original Bareos server druing restore.

For many machines, we backup the images directly from VMware to achieve these goals. However, in some cases this option is not available for a varietly of reasons, so we are looking into an alternative in these cases.

**Comment by jsmeix** [comment]
My untested first idea is to not change ReaR
but to use ReaR as it is meant to be used
and do the intended things "outside" of ReaR
something like the following

Configure ReaR so that "rear mkrescue" stores
the results on the local disk.

Configure the backup so that the "rear mkrescue"
results are also included in the backup.

Run the backup directly if an external backup tool is used
or run "rear mkbackuponly" if an internal backup tool is used
to get a backup that also contains the "rear mkrescue" results.

Background information:

There is no feasible way (with reasonable effort)
to pipe the output of ReaR into another process
because ReaR does not write its output as a single
stream of dats to a single file descriptor that could be
redirected into a pipe.

Note that stdout and stdin are redirected into the ReaR log file,
cf. "What to do with stdin, stdout, and stderr" at
https://github.com/rear/rear/wiki/Coding-Style

"rear mkrescue" produces various regular files,
the so called RESULT_FILES (see default.conf).

ReaR supports to send the RESULT_FILES via
mail (see default.conf).

ReaR does not support to output the RESULT_FILES
as a data stream via a file descriptor that could be
redirected into a pipe.

"rear mkbackup" produces the RESULT_FILES
plus whatever specific kind of backup (files)
that depend on the particular backup program
that is called by ReaR and how support for that
particular backup program is implemented in ReaR,
cf. "Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
@namezero111111 
in general regarding questions about third-party backup tools (like Bareos)
you should better directly ask those who make the third-party backup tool.
In particular I do not use any third-party backup tool so that
I cannot answer any question about third-party backup tools.

**Comment by didacog** [comment]
@namezero111111 

You can combine ReaR, [DRLM](https://github.com/brainupdaters/drlm) and BareOS.
DRLM provides DR over network (PXE) and manages ReaR installations. You can export/import DRLM images (rear backup + boot img PXE) from/to different servers(clients) for testing, migrations or installations from template DR image, then You can get those backups with BareOS from /var/lib/drlm/arch in DRLM server with a standard BareOS backup job on a convenient backup window.
DRLM keeps a configurable number of DR images at disk, olders are removed, you can always restore a older and removed DR image from BareOS to any DRLM server, import it to a DRLM client and recover it. 

Hope this can help you.

Regards,
Didac

**Comment by namezero111111** [comment]
Ok thank you for all your expert advice. We will try the suggestions in a test environment and report back!
