### ISSUE TITLE
No Networker ISO Backups found.

### ISSUE THREAD

**Issue by nirmal21s** [rear/rear#1807]
Installed REAR & integrated it with NSR : 
While creating mkrescue image "its saying no Networker ISO backups found ". But ISO image has been created with 136MB size. Is this image valid and can be tested or  am i missing something here ? 

OS Version :Red Hat Enterprise Linux Server release 6.7 (Santiago)
REAR rpm used : rear-2.3-1.el6.x86_64.rpm
Networker client : lgtoclnt-7.6.4.1-1.x86_64

MKrescue output : 
[root@ts2ccgcs113 ~]# rear -v mkrescue
Relax-and-Recover 2.3 / 2017-12-20
Using log file: /var/log/rear/rear-ts2ccgcs113.log
Creating disk layout
Using guessed bootloader 'GRUB'
No Networker ISO Backups found.
Creating root filesystem layout
To log into the recovery system via ssh set up /root/.ssh/authorized_keys or specify SSH_ROOT_PASSWORD
Copying logfile /var/log/rear/rear-ts2ccgcs113.log into initramfs as '/tmp/rear-ts2ccgcs113-partial-2018-05-16T05:17:00+0200.log'
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Copying all files in /lib*/firmware/
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (136285387 bytes) in 28 seconds
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-nsr-ts2ccgcs113.iso (137M)
Copying resulting files to file location
Saving /var/log/rear/rear-ts2ccgcs113.log as rear-ts2ccgcs113.log to file location

**Comment by nirmal21s** [comment]
Thanks for your response.. 
I have left it blank now.

**Comment by jsmeix** [comment]
@nirmal21s 

I recommend to try out our current ReaR upstream GitHub master code
because that is the only place where we at ReaR upstream fix bugs.

To use our current ReaR upstream GitHub master code
do the following:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

If it works with current ReaR upstream GitHub master code
we would really appreciate an explicit positive feedback.
