### ISSUE TITLE
Misusing -c option produces unexpected result

### ISSUE THREAD

**Issue by wzwei** [rear/rear#1815]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.3 / Git
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): Red Hat Enterprise Linux 7
* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"): does not matter
* System architecture (x86 compatible or POWER and/or what kind of virtual machine): x86
* Are you using BIOS or UEFI or another way to boot? does not mattter
* Brief description of the issue: Stating a file instead of a dir to "rear -c ..." gives unexpected results
* Work-around, if any: use the right options

I accidentally gave a config file to "-c" which produced a rescue ISO file (as expected). It would
be better if rear bails out in that situation and gives a warning/error message.

**Comment by jsmeix** [comment]
I think a test in usr/sbin/rear that the '-c' option argument is a directory
is possible because I think the '-c' option argument must be a directory
in any case (at least 'man rear' indicates that).

@wzwei 
in general ReaR is currently not really fail-safe.
Currently many things in ReaR can go wrong in weird arbitrary ways
at unexpected places if you do not carefully set up and use ReaR.

In general you may have a look at the section
"Inappropriate expectations" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by wzwei** [comment]
@jsmeix thank you for the hint. I know the points and already experienced some problems ;-)

Thx,
Wolfgang

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1920 merged
this issue should be fixed.

@gdha 
thank you for fixing it regardless that it was assigned to me
(currently I have not so much time for ReaR).
