### ISSUE TITLE
give a specific title/name to a menu item in rear recover iso 

### ISSUE THREAD

**Issue by silent-mobius** [rear/rear#1878]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.4 / 2018-06.21

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
<pre>
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)
</pre>

* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"):
<pre>
OUTPUT=ISO
OUTPUT_URL=cifs://192.168.0.5/System_backup/
BACKUP_URL=cifs://192.168.0.5/System_backup/
BACKUP=NETFS
BACKUP_OPTIONS="cred=/etc/rear/cifs"
OUTPUT_OPTIONS="cred=/etc/rear/cifs"
</pre>

* Real hardware (PC or PowerNV BareMetal or ARM) and/or virtual machine (KVM guest or PoverVM LPAR):
PC

* System architecture (x86 compatible or POWER PPC64/PPC64LE or what excat ARM device):
x86_64

* Are you using BIOS or UEFI or another way to boot (Open Firmware or Petitboot)?
BIOS

* Brief description of the issue:
I want to have custom name to iso choises - but there is no documentation on that issue.

* Work-around, if any:

**Comment by jsmeix** [comment]
@silent-mobius 
what "menu item in rear recover iso" are you talking about
and what is your goal behind why you would like to
"give a specific title/name to a menu item"?

**Comment by silent-mobius** [comment]
i am generating the recovery  for various system at my company, i'd like to have a name of image that i am trying to recover at the boot screen when booting from recovery.iso

**Comment by jsmeix** [comment]
The ReaR recovery system bootloader is usually syslinux
which is set up by the syslinux related functions
in usr/share/rear/lib/bootloader-functions.sh
therein in particular the make_syslinux_config function.

Those functions set the hostname in the recovery system boot menue
e.g. in the make_syslinux_config function via (excerpt)
<pre>
        syslinux_menu "label ^Recover $HOSTNAME"
</pre>

The default vaule of the HOSTNAME variable is set in
usr/share/rear/conf/default.conf via
<pre>
HOSTNAME="$( hostname -s 2>/dev/null || uname -n | cut -d. -f1 )"
</pre>
but if that is not the right way to set this value in your case
you can set it as you need in your etc/rear/local.conf
where you can call any commands you like to set HOSTNAME
because also config files are sourced/executed as bash scripts.
Be careful because etc/rear/local.conf is also executed during "rear recover"
but the usual way how the hostname in the running recovery system is set
is during recovery system startupo via /etc/scripts/boot that is
usr/share/rear/skel/default/etc/scripts/boot
and /etc/HOSTNAME in the recovery system is created
during "rear mkrescue/mkbackup" by
usr/share/rear/rescue/default/100_hostname.sh

Or is perhaps the hostname not sufficinet in your particular case?
I assume that your various systems have different hostnames
so that you could distinguish them by their hostnames.

**Comment by jsmeix** [comment]
I do not understand how the ReaR recovery system boot menue entries
could provide different ReaR recovery system versions because
one particular ISO image is one single ReaR recovery system
(the one that matches the one original system at the time when
 "rear mkrescue/mkbackup" was run there - the recovery system
 is specific for the one particular original system where it was made)
and when you boot that particular ISO image there is no way
to choose another ReaR recovery system.

In general there is no support for version control in ReaR
and ReaR is not meant to provide version control support
or any other ways to manage multiple backups or ISO images
for various systems.

Cf. the section
"Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

To manage multiple backups or ISO images for various systems
additional software is usually needed.
You may have a look at tools that are intended to manage backups.
In particular to manage ReaR for various systems have a look at
the Disaster Recovery Linux Manager (DRLM), see
http://drlm.org/
that reads in particular (excerpt):
<pre>
DRLM is an easy-to-use software to manage your growing
ReaR infrastructure. It ... offers all the tools you need to
efficiently manage your GNU/Linux disaster recovery backups.
</pre>

Some very limited things could be done in ReaR, like an added timestamp
but as a consequence runtime dependant file names cause drawbacks
for "rear recover", see
http://lists.relax-and-recover.org/pipermail/rear-users/2018-July/003575.html
and
http://lists.relax-and-recover.org/pipermail/rear-users/2018-June/003569.html

Perhaps also
http://lists.relax-and-recover.org/pipermail/rear-users/2018-July/003576.html
and the links therein might be helpful here.

But all those are not about the ReaR recovery system boot menue entries.

**Comment by jsmeix** [comment]
I think this issue is sufficiently answered.
