### ISSUE TITLE
Restore fails when teaming runner is configured as LACP

### ISSUE THREAD

**Issue by MogiePete** [rear/rear#1926]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version: 2.4-1.el7

* OS version: CentOS 7.5
* ReaR configuration files:
OUTPUT=ISO
BACKUP=TSM
* Hardware: Cisco C240 M4
* System architecture: x86_64
* Firmware: BIOS
* Storage: Local Disk
* Description of the issue (ideally so that others can reproduce it):

In issue #655 @rg-fine has an issue with rear working with teamed interfaces in RHEL and provided work around in PR #662.

The resolution was to simplify the function that all ip-addresses and routing-entries of a teaming-interface will be attached to its first available teaming-member according to teamdctl.

While this works well in a team configured for broadcast, roundrobin, and activebackup it does not work when configured for LACP. (I can't confirm for loadbalance as I haven't tested it).

As stated in #662 all ip-addresses and routing-entries are configured on one interface but LACP is not operational. This results in the host not being able to communicate with the TSM server and the backup failing.

**Comment by jsmeix** [comment]
@MogiePete 
in ReaR version 2.4
<pre>
Network setup was completely reworked to support
bonding, bridges, vlans and teaming. There is a full
rewrite of the 310_network_devices.sh script generating
network interfaces for use during ReaR rescue/recovery
system networking setup via the 60-network-devices.sh
script. It also handles corner cases/odd setups that can
be found from time to time, typically when the administrator
uses bonding plus bridges plus vlans as well as teaming.
</pre>
see
http://relax-and-recover.org/documentation/release-notes-2-4

@rmetrich 
could you have a look here because it is about
teamed network interfaces which could be related to your code in
usr/share/rear/rescue/GNU/Linux/310_network_devices.sh

**Comment by jsmeix** [comment]
@MogiePete 
in general when ReaRs automated setup of the networking stuff
in the ReaR recovery system does not work as you need it
in your particular case, you can as a workaround manually
specify any networking setup comands as you need it via the
`NETWORKING_PREPARATION_COMMANDS` array, see
usr/share/rear/conf/default.conf

**Comment by rmetrich** [comment]
Hello,

If I remember well, the teaming is always simplified.
Could you hence submit the generated file (`/etc/scripts/system-setup.d/60-network-devices.sh`)?

Also a debug log of the `rear -dD mkrescue` may help there.

**Comment by rmetrich** [comment]
@MogiePete 
Would it work with LACP if an interface is taken administratively down?
What happens on the OS if you set carrier to 0 on one of the physical interface?
The idea is to find a solution without integrating the whole teamdctl stack.

**Comment by MogiePete** [comment]
@rmetrich 

I have attached the 60-network-devices.sh renamed to .txt as requrested along with the debug log.

In regards to your question about setting the carrier to 0 I do not know how to do that with teaming and rear but it would be worth a try.

Also, we did work with our network team and tried with the second port set to admin down but they were not seeing any LACP traffic. Additionally, when they disabled the Port-Channel then traffic was flowing but this is not the ideal path to take as doing a restore when the OS is configured for bonding does not require any modification of the network configuration.

[60-network-devices.sh.txt](https://github.com/rear/rear/files/2470584/60-network-devices.sh.txt)
[rear-mariadb01.log](https://github.com/rear/rear/files/2470586/rear-mariadb01.log)

**Comment by rmetrich** [comment]
Looking closer, I think we really need to simplify the Teaming configuration because including Teaming is very complicated: it requires d-bus and other stuff we probably don't want in the rescue.
Could your network team describe the switch configuration of the ports?
With same switch configuration, is it possible to configure the OS in bonding instead? If so, can you describe the required bonding configuration?
Asking because maybe we could just map teaming to bonding while in rescue.

**Comment by rmetrich** [comment]
Hello @MogiePete ,
I've started implementing the teaming code inside recovery. I believe this is doable without including D-Bus.
Please allow me some time as this is not my primary responsibility at Red Hat.

My understanding is that with LACP, using network simplification will not work, even for Bonding. Hence, I would also like to harden the bond code so that in case of LACP, no network simplification happens and a message gets printed to the user.

Once code is implemented, please help us testing, because I don't have access to the required hardware.

**Comment by rmetrich** [comment]
@jsmeix LACP works by sending frames to negociate link state between switch and host. If we just plumb a single network interface, then no frame will be sent, preventing any network traffic to occur.

**Comment by MogiePete** [comment]
@rmetrich 

Thank you for working on this. I am sure many will benefit.

Once the code is committed I will test and provide feedback.

Thanks again.

**Comment by MogiePete** [comment]
@rmetrich 

I was able to test this using bonding and teaming after building the rpm from your pull request.

On one of the two nodes I had an issue with the system booting properly after the TSM restore. The UUID of /dev/sda1 which holds /boot was not updated in the fstab which resulted in the system failing to load the operating system properly. A quick edit after booting into recovery on the CentOS iso resolved the issue. The two systems were identical in terms of hardware and OS configuration so I am not sure what the issue was.

Other than that one issue I can report that the additions to the networking code are working properly.

Thank you so much for the quick turn around on this issue.

**Comment by jsmeix** [comment]
@MogiePete 
can you open a new separated issue for
<pre>
The UUID of /dev/sda1 which holds /boot
was not updated in the fstab which resulted in the
system failing to load the operating system properly
</pre>
We need separated GitHub issue reports for separated issues
because otherwise different things could mess up until havoc.

Normally UUIDs in the restored etc/fstab get automatically adjusted via
usr/share/rear/finalize/GNU/Linux/280_migrate_uuid_tags.sh
that reads a FS_UUID_MAP file var/lib/rear/layout/fs_uuid_mapping
which gets created during "rear recover" by the script
usr/share/rear/layout/prepare/GNU/Linux/130_include_filesystem_code.sh

You may also have a look at item (5)
in https://github.com/rear/rear/issues/1854#issue-338886055
and https://github.com/rear/rear/pull/1758
and https://github.com/rear/rear/issues/1857

To have a chance to understand what went wrong in your case
I need a debug log of "rear -D recover" (the recovery log gets
copied into the recreated system so that you should have it)
plus - if possible - your old etc/fstab from the backup and the
new adapted one that works.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1934 merged
this issue should be fixed.

**Comment by jsmeix** [comment]
@MogiePete 
thank you for your follow up issue https://github.com/rear/rear/issues/1938
regarding https://github.com/rear/rear/issues/1926#issuecomment-430533773

**Comment by pcahyna** [comment]
@MogiePete "I was able to test this using bonding and teaming after building the rpm from your pull request."
Did you test teaming with multiple interfaces in the team? For us this did not work because teaming seems to have a problem analogous to #1954, which was fixed for bonding, but not for teaming.

**Comment by MogiePete** [comment]
@pcahyna

Yes this was tested with 2 interfaces configured for LACP.

**Comment by pcahyna** [comment]
@MogiePete  thanks for the confirmation. I don't see how this could have worked though. In our testing, teamd is invoked as
```
teamd -d -c '{"device": "int-team", "ports": {"em1": {"link_watch": {"name": "ethtool"}}, "em1": {"link_watch": {"name": "ethtool"}}}, "runner": {"name": "lacp", "tx_hash": ["eth", "ipv4", "ipv6"]}}'
```
which fails with this message:

> Failed to parse config: duplicate object key near '"em1"' on line 1, column 82
> Failed to load config.

@rmetrich  any idea?

**Comment by rmetrich** [comment]
@pcahyna You have "em1" twice, is that expected?

**Comment by pcahyna** [comment]
@rmetrich, yes, that's the point. That's why it fails. Since the MAC address is duplicated, the sed command modified the script so that it contains a duplicate interface name.

**Comment by MogiePete** [comment]
@pcahyna @rmetrich 

This is the version I had installed:

Relax-and-Recover 2.4-git.3115.507837a.unknown / 2018-10-16
