### ISSUE TITLE
ReaR doesn't create disklayouts correctly using GPT partition tables

### ISSUE THREAD

**Issue by CJCShadowsan** [rear/rear#1950]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
2.00 
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
````
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7
#
# WARNING ! This information was added automatically by the mkrescue workflow !!!
ARCH='Linux-i386'
OS='GNU/Linux'
OS_VERSION='7'
OS_VENDOR='RedHatEnterpriseServer'
OS_VENDOR_VERSION='RedHatEnterpriseServer/7'
OS_VENDOR_ARCH='RedHatEnterpriseServer/i386'
````
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
````
# Default is to create Relax-and-Recover rescue media as ISO image
# set OUTPUT to change that
# set BACKUP to activate an automated (backup and) restore of your data
# Possible configuration values can be found in /usr/share/rear/conf/default.conf
#
# This file (local.conf) is intended for manual configuration. For configuration
# through packages and other automated means we recommend creating a new
# file named site.conf next to this file and to leave the local.conf as it is.
# Our packages will never ship with a site.conf.
USB_UEFI_PART_SIZE="500"
OUTPUT=USB
OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
BACKUP=NETFS
BACKUP_URL=file:///mnt/backups
BACKUP_PROG=rsync
````
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PC
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI
* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local disk
* Description of the issue (ideally so that others can reproduce it):
When creating a rescue image on a GPT partition, it leaves disklayout.conf without a field set - which results in a restore failing because the partition name isn't set (because it's not got enough fields to read).
* Workaround, if any:
set 'primary' inside disklayout.conf
 
* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by gdha** [comment]
@CJCShadowsan please paste the `/var/lib/rear/layout/disklayout.conf` file.

**Comment by jsmeix** [comment]
@CJCShadowsan 
ReaR version 2.00 is a bit old, from January 2017, cf.
http://relax-and-recover.org/documentation/release-notes-2-4

Try out if a more current version works better for you, cf.
http://relax-and-recover.org/download/

See
http://relax-and-recover.org/documentation/release-notes-2-4
what has changed from ReaR 2.0 to the current ReaR 2.4.
There are some possibly backward incompatible changes.

I would also recommend to try out our current
ReaR upstream GitHub master code as follows:

Basically "git clone" our current ReaR upstream GitHub master code
into a separated directory and then configure and run ReaR
from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

I recommend to try out our current ReaR upstream GitHub master code
because that is the only place where we fix bugs - i.e. bugs in older
ReaR versions are not fixed by us (i.e. by ReaR upstream).

Bugs in older ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (provided the fix can be backported
with reasonable effort) by the Linux distributor wherefrom you got your
older ReaR version.

If the issue also happens with current ReaR upstream GitHub master code
please provide us a complete ReaR debug log file of "rear -D mkrescue"
so that we can have a look how it behaves in your particular environment
cf. "Debugging issues with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

If it works with current ReaR upstream GitHub master code
we would really appreciate an explicit positive feedback.

Alternatively:
If you have a RH subscription contract you could open a support case at RH
for further assistance provided you use the ReaR version from the RHEL repo.

**Comment by jsmeix** [comment]
I assume "no news is good news".
