### ISSUE TITLE
rear recover stops if /boot/efi is missing.

### ISSUE THREAD

**Issue by gozora** [rear/rear#1972]
#### Relax-and-Recover (ReaR) Issue Template

* ReaR version ("/usr/sbin/rear -V"): 
`Relax-and-Recover 2.4 / Git`

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
```
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
BACKUP=NETFS
OUTPUT=ISO

BACKUP_URL=nfs://backup.virtual.sk/mnt/rear
OUTPUT_URL=nfs://backup.virtual.sk/mnt/rear/iso

BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} /media )
GRUB_RESCUE=n
BACKUP_OPTIONS="nfsvers=3,nolock"

BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '/mnt' '/media' '/var/tmp/*' '/tmp' )

ISO_MKISOFS_BIN="/bin/ebiso"

EFI_STUB=y
USING_UEFI_BOOTLOADER=y
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
`VirtualBox VM`

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
`x86`

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
`UEFI - EFISTUB` ;-)

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
`local`

* Description of the issue (ideally so that others can reproduce it):
`rear recover` throws error in [510_selinux_fixfiles_exclude_dirs.sh](https://github.com/rear/rear/blob/master/usr/share/rear/restore/NETFS/Linux-i386/510_selinux_fixfiles_exclude_dirs.sh) if /mnt/local/boot/efi directory is missing:

```
if ! test -d "$TARGET_FS_ROOT/boot/efi" ; then
    Error "Could not find directory $TARGET_FS_ROOT/boot/efi"
fi
```

I was just wondering if anybody would mind if I change this to some kind of warning, or even better, to completely remove this check ...
It looks pointless to me to stop restore near to the end of the process.

V.

**Comment by jsmeix** [comment]
In general we should not error out during "rear recover"
after the backup was restored.

E.g. see my comment in finalize/Linux-i386/620_install_grub2.sh
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/finalize/Linux-i386/620_install_grub2.sh
<pre>
# This script does not error out because at this late state of "rear recover"
# (i.e. after the backup was restored) I &lt;jsmeix@suse.de&gt; consider it too hard
# to abort "rear recover" when it failed to install GRUB2 because in this case
# the user gets an explicit WARNING via finalize/default/890_finish_checks.sh
# so that after "rear recover" finished he can manually install the bootloader
# as appropriate for his particular system.
</pre>

**Comment by gozora** [comment]
With https://github.com/rear/rear/pull/1977 merged, this issue can be closed.

V.
