### ISSUE TITLE
REAR recovery issue with single ISO

### ISSUE THREAD

**Issue by attiqmscs004** [rear/rear#1984]
Hi team,
I have used a single ISO recovery image as per guide of REDHAT. I have used following settings for creating both rescue and backup data on single iso image. My ISO image file is created successfully of size 6.5 GB. When I try to recover data from this ISO image on another physical server, I get the following error. Please guide what I am missing.

Environment: 
RHEL 7.4
Physical Blade Serer Gen 8

Source Host:
[root@localhost rear]# cat /etc/rear/local.conf 

OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=file:///srv/backup/
BACKUP_URL=iso:///rear
BACKUP_PROG_EXCLUDE=( '/tmp/*' '/dev/shm/*' '/home/attiq.rehman/rhel-server-7.3-x86_64-dvd.iso' )
BKUP_MAX_SIZE=3500MB

Target Host:
rear -d -v recover 

cat /var/log/rear/rear-localhost.log
Error:
"the workflow restore is not supported in the rear rescue/recovery system"

**Comment by jsmeix** [comment]
@attiqmscs004 
there is no `restore` workflow in ReaR so that I cannot imagine
from your error message alone what goes on in your particular case.
Cf. https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
that reads (excerpt):
<pre>
Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files)
</pre>
see also "Debugging issues with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by attiqmscs004** [comment]
Apology for typo mistake.
It is recover instead of restore.

rear -v recover

**Comment by gdha** [comment]
@attiqmscs004 please show us the log file with the error message (preferably in debug mode)

**Comment by gdha** [comment]
@attiqmscs004 Did you boot from the ISO image on the 2th system?
