### ISSUE TITLE
error in logs: File changed as we read it

### ISSUE THREAD

**Issue by amiirrmm** [rear/rear#1990]
* ReaR version: 2.4

* OS version: Debian 9

* ReaR configuration files: 
OUTPUT=ISO, type=tar, NETFS, incremental, NFS storage

* Hardware: KVM guest

Hi

I have created a backup successfully with no errors on my NFS server from a machine. Then during examining the log file, I encountered multiple statements stating: **"tar: /...../ : file changed as we read it".** 

1. Is the archived file healthy? Is the whole backup healthy and recoverable?

2. Although these files may not be important in many cases, I wanted to know how ReaR treats these files. Consider a huge database file that changes as ReaR tires to back it up. what would happen to these huge files?

3. If the huge file gets damaged by this method, is there any other ways to backup the machine using rear to keep the file healthy?

Thanks in advance !

**Comment by jsmeix** [comment]
It is your task to ensure the backup is consistent,
e.g. you may have to stop certain running processes
(e.g. whatever services or things like that)
that are running while the backup is done.

ReaR only calls the backup tool (in your case `tar`)
but ReaR does not do anything to ensure none of the files change
that get included in your backup while the backup tool runs
(because ReaR cannot know what to do to ensure that).

Cf. the section
"Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery
