### ISSUE TITLE
Question about "fc_transport.info"

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#2020]
Hello @rear/contributors 
`/usr/share/rear/rescue/GNU/Linux/270_fc_transport_info.sh` collects a **recovery/fc_transport.info** file based on content of `/sys/class/fc_transport`.

Do you know why this is needed? Is that useful to the system administrator upon recovery?

**Comment by jsmeix** [comment]
@rmetrich 
my preferred first step of forensics that I usually do
(e.g. when there are no explanatory comments in the code)
is
```
git log -p --follow usr/share/rear/rescue/GNU/Linux/270_fc_transport_info.sh 
```
which shows that it was made by @gdha via
https://github.com/rear/rear/commit/f593fa8a33d6638d9fd2b4fcdd175805203edc4a

But there is also no further info in that commit
so that I "just assign" your question directly to @gdha ;-)

**Comment by rmetrich** [comment]
Didn't want to fingerpoint him :-)

**Comment by jsmeix** [comment]
It has been a privilege and a pleasure for me to do you a favour :-)

**Comment by rmetrich** [comment]
Asking because we have a customer having issues with the `find /sys/class/fc_transport` command taking several hours!

**Comment by gdha** [comment]
Oh boy - the info is not worth waiting for - we can live without it...

**Comment by gdha** [comment]
Script will return immediately - so this issue can be closed

**Comment by jsmeix** [comment]
Because since https://github.com/rear/rear/commit/d642fa1c9c26361f130d3f18e40dc425efe6e2f0
we still have rescue/GNU/Linux/270_fc_transport_info.sh
which is now basically dead code
I like to re-open this issue and assign it to
@schabrolles 
so that he can check if rescue/GNU/Linux/270_fc_transport_info.sh
could be completely removed.

**Comment by schabrolles** [comment]
I don't remember having to use this script or the file generated by it `$VAR_DIR/recovery/fc_transport.info`
I don't see any other script from git that would need it either...

**Comment by jsmeix** [comment]
I removed rescue/GNU/Linux/270_fc_transport_info.sh via
https://github.com/rear/rear/commit/ad73a2197079413e4359e131b6aa4175a458fd35
