### ISSUE TITLE
rear.spec: Remove obsolete Group tag

### ISSUE THREAD

**Issue by gdha** [rear/rear#2027]
* Description of the issue (ideally so that others can reproduce it):
References: https://fedoraproject.org/wiki/Changes/Remove_Group_Tag

````
diff --git a/rear.spec b/rear.spec
index 80f037f..7d8650b 100644
--- a/rear.spec
+++ b/rear.spec
@@ -11,7 +11,6 @@ Name: rear
 Version: 2.4
 Release: 2%{?rpmrelease}%{?dist}
 License: GPLv3
-Group: Applications/File
 URL: http://relax-and-recover.org/

 # as GitHub stopped with download section we need to go back to Sourceforge for downloads
````

https://src.fedoraproject.org/rpms/rear/c/84408a7964330f613252a073aebdcc93606a6cb9?branch=master

**Question for SuSe**: again what applies for SLES today?

**Comment by jsmeix** [comment]
I think removing the `Group` tag would violate
the "openSUSE:Specfile guidelines" at
https://en.opensuse.org/openSUSE:Specfile_guidelines
that read (excerpts):
```
Group: only package groups listed in the package group guidelines
https://en.opensuse.org/openSUSE:Package_group_guidelines
should be used.
```

Regardless that the `Group` tag is not strictly required
by the "openSUSE:Specfile guidelines" I remember that
the `Group` tag is used at several places in SUSE and openSUSE
(for example by the YaST/zypper/libzypp package installation tools).

At openSUSE there was a discussion about removing the `Group` tag
see the "Killing Group tag in .spec files" mail thread
on the opensuse-factory mailing list
https://lists.opensuse.org/opensuse-factory/2018-05/msg00460.html

According to
https://lists.opensuse.org/opensuse-factory/2018-05/msg00466.html
it seems the `Group` tag is somehow mandatory for
SUSE Linux Enterprise (SLE) related things and
https://lists.opensuse.org/opensuse-factory/2018-05/msg00498.html
shows that it is required to build ReaR for older SLE versions
so that at least for the near future the `Group` tag has to stay.

As in
https://github.com/rear/rear/issues/2026#issuecomment-458493458
I think we need to maintain several separated RPM spec files
as needed for different Linux distributions.

**Comment by gdha** [comment]
As we build on OBS we must keep this group tag IMHO. We will not fix it.
