### ISSUE TITLE
Placeholder for new release of ReaR 2.5

### ISSUE THREAD

**Issue by gdha** [rear/rear#2033]
#### Relax-and-Recover (ReaR) release 2.5 Preps

* close as many **ReaR 2.5 labeled** issues

* decide on some issues to post-pone to a next release

* verify if there are no blockers for the release

* check the documentation if it is still accurate for the new release

* wrap-up the release notes

* cool-down period to allow testing of the ReaR-2.5 (beta) release

* decide on a release date

_PS: if we miss something please let us know_

**Comment by gdha** [comment]
Update documentation e.g. doc/user-guide/03-configuration.adoc

**Comment by jsmeix** [comment]
Because of what @schabrolles wrote 3 days ago in
https://github.com/rear/rear/issues/2019#issuecomment-466769572
```
I don't have a lot of time and will be really busy
till the end of next week
```
I suggest to postpone the ReaR 2.5 release until @schabrolles 
has a bit more time for ReaR according to
https://github.com/rear/rear/milestones
```
For ReaR release 2.5 we do not have a release date
in mind (beginning 2019). It depends on bug fixes
or bleeding edge new features... 
```

I suggest to postpone the ReaR 2.5 release until `end of next week`
plus one more week which would be until Friday 15. March 2019
provided that one week is sufficient for @schabrolles 

@schabrolles 
I would appreciate it if you could before ReaR 2.5 release have a look at

* https://github.com/rear/rear/issues/2041#issuecomment-464646710

* https://github.com/rear/rear/issues/2019#issuecomment-466349187
therein in particular what I wrote about your
`refresh udev with trigger before activating multipath` in your
https://github.com/schabrolles/rear/commit/03228ffdbf748e16026d8776c0745b0794c74148

* https://github.com/rear/rear/pull/2055

**Comment by gdha** [comment]
I moved the scheduled release to end of March 2019 - plenty of time to get the last issues in and do the stability tests...

**Comment by gdha** [comment]
@rear/contributors Shall we try to wrap up rear-2.5 so we can start creating our validation matrix?

**Comment by jsmeix** [comment]
Right now this is the only open issue for ReaR 2.5
(also no pull requests that we must have in ReaR 2.5) and with
https://github.com/rear/rear.github.com/commit/4bc1a19f6cb4f779d895434e1c32f19d8a09bab1
the release notes for ReaR 2.5 are up to date,
only `Version 2.5 (work in progress)` would have
to be changed to `Version 2.5`
provided we @rear/contributors agree to release
our current GitHub master code as ReaR 2.5.

**Comment by gdha** [comment]
@rear/contributors Fine - shall we first file up https://github.com/rear/rear/wiki/Test-Matrix-rear--2.5 a bit before we make the general release available. Can we agree on this?

**Comment by jsmeix** [comment]
I agree with https://github.com/rear/rear/issues/2033#issuecomment-486999654

What I basically meant with
https://github.com/rear/rear/issues/2033#issuecomment-486983987
is that we first agree to freeze our current GitHub master code
so that we can test a non-moving state and then - provided
there are no severe issues - release it as ReaR 2.5.

**Comment by jsmeix** [comment]
A side note regarding "review the documentation":
I found https://github.com/rear/rear/issues/2140
but that is an "RFC" for "Rear future".

**Comment by jsmeix** [comment]
@gdha 
currently on
https://build.opensuse.org/package/show/Archiving:Backup:Rear:Snapshot/rear
all fail because there is no `rear-2.4-git.0.f98a187.unknown.tar.gz`
e.g. see the build log for openSUSE_Factory/x86_64 at
https://build.opensuse.org/package/live_build_log/Archiving:Backup:Rear:Snapshot/rear/openSUSE_Factory/x86_64
that contains (excerpt):
```
error: Bad source: /home/abuild/rpmbuild/SOURCES/rear-2.4-git.0.f98a187.unknown.tar.gz: No such file or directory
```
which is also shown at
https://build.opensuse.org/package/show/Archiving:Backup:Rear:Snapshot/rear
that there is no such file in the list of `Source Files` that is shown there.

**Comment by gdha** [comment]
@jsmeix I forced a rebuild - it started building again...

**Comment by gdha** [comment]
As ReaR-2.5 has been released in the meantime we may close this issue.
