### ISSUE TITLE
Missing basic executables in ReaR

### ISSUE THREAD

**Issue by gdha** [rear/rear#2040]
* ReaR version ("/usr/sbin/rear -V"): latest

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): all

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"): n/a

* Description of the issue (ideally so that others can reproduce it):
Was doing a DR exercise at a customer where the console of vSphere was not fitting the window, meaning the bottom-line was not visible, and it is there where the most typing happens.
Unfortunately the `clear` command was not part of the basic ReaR tool-set. Would like to include this.
The question is are there other little programs that you miss from time to time?

**Comment by jsmeix** [comment]
I do not miss other little programs from time to time.

@gdha
feel free to add useful optional helper tools to the PROGS array
and missing generic helper tools to the REQUIRED_PROGS array
up to any point that you think is reasonable.

With "missing generic helper tools" I mean tools that exist
on all Linux distributions and that one (desperately) needs
in this or that exceptional cases to save the day.

In general I prefer when ReaR users get by default
a rather big and full featured ReaR recovery system
that works in almost all cases, in particular on most
(possibly different) replacement hardware.

I think those cases where the ReaR recovery system should be minimal
must be explicitly specified by the user via COPY_AS_IS_EXCLUDE
when he finds out that the default recovery system is too big in his case.

My reasoning behind is that a by default big recovery system
that works in almost all cases and on most hardware causes less
severe issues compared to a by default minimal recovery system
because a too big recovery system only wastes some space
but when something essential is missing in the recovery system
it is basically a dead end for the user during "rear recover".

Cf.
https://github.com/rear/rear/pull/1961#issuecomment-437352262

**Comment by jsmeix** [comment]
I think with https://github.com/rear/rear/pull/2043 merged
this issue is fixed/solved/done - at least for now - because
currently nobody is missing other little programs.
