### ISSUE TITLE
kernel panic "VFS: Unable to mount root fs on unknown-block(0,0)" on HPE ProLiant DL380 Gen10 UEFI with backup on ISO

### ISSUE THREAD

**Issue by jfucanada** [rear/rear#2052]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.4 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
  OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7
RHEL 7.6

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
MODULES=( 'all_modules' )
FIRMWARE_FILES=( 'yes' )
OUTPUT=ISO
OUTPUT_URL=file:///ReaR
BACKUP=NETFS
BACKUP_URL=iso:///ReaR
SSH_ROOT_PASSWORD="redhat"
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/ReaR' '/var/tmp' '/var/crash') #NETFS_KEEP_OLD_BACKUP_COPY=
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

BareMetal-HP DL380 UEFI
* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI
* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SSD
* Description of the issue (ideally so that others can reproduce it):
We booted from ReaR ISO image and select Relax-and-Recover (no Secure  Boot)  the we got Kernel got panic
* Workaround, if any:
No
* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

**Comment by gozora** [comment]
https://github.com/rear/rear/issues/2035 || please correctly fill the issue template ...

V.

**Comment by jfucanada** [comment]
Where can I find beta version if it already included the fix?

**Comment by jfucanada** [comment]
<img width="528" alt="rear-screen-shot" src="https://user-images.githubusercontent.com/11881813/53278626-35c0ec00-36bf-11e9-853c-f441eef5d49e.png">

**Comment by jsmeix** [comment]
@jfucanada 
we need a "rear -D mkrescue/mkbackup" debug log file, cf.
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md

https://github.com/rear/rear/issues/2035#issuecomment-465987439
describes how you can try out our current ReaR GitHub master code.

A kernel panic while the kernel of the ReaR recovery system starts up
is not related to https://github.com/rear/rear/issues/2035

I guess your kernel panic happens when the recovery system starts up
and not after "rear recover" finished and you reboot the recreated system.

You did not describe your issue so that others (i.e. we) understand it, cf.
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md

I do not have your hardware so that if your issue is specific on your
hardware there is nothing what I could do - but perhaps others might
be able to help you - provided your description is helpful for them.

When you have a Red Hat support contract you may also ask
the Red Hat support.

**Comment by jfucanada** [comment]
[rear-lnxcstsdsgg01.log](https://github.com/rear/rear/files/2902425/rear-lnxcstsdsgg01.log)

**Comment by jfucanada** [comment]
This problem is fixed after we upgraded the firmware.

**Comment by glemes01** [comment]
I am with same trouble, updated the frimware but same error =[... could someone help me?

**Comment by glemes01** [comment]
HP GEN 9 DL380....

**Comment by pcahyna** [comment]
@glemes01 please open a new issue and fill out the issue template. I need to know your distribution and version and please include also the version of the GRUB packages. I suspect your problem might be https://bugzilla.redhat.com/show_bug.cgi?id=2207732, so please include the GRUB messages (before the kernel starts booting).
