### ISSUE TITLE
Retain log file at a safe place during recovery

### ISSUE THREAD

**Issue by gdha** [rear/rear#21]
Was on Sourceforge as SF#[3448325](https://sourceforge.net/tracker/?func=detail&aid=3448325&group_id=171835&atid=859455)

Currently when "rear recover" runs successfully its log file /tmp/rear-<hostname>.log in the ReaR recovery system is copied into /root/ on the recovered system.

But when "rear recover" fails, its log file is not saved to a save plave so that it is lost when the ReaR recovery system is finished.

For "BACKUP=NETFS" the "rear recover" log file should be saved in any case to the NETFS_URL to have it automatically at the same save place where the backup.tar.gz and the "rear mkbackup" log file and the ISO image already are.

To make sure a "rear recover" log file exists at the save place in any case even if "rear recover" breaks at a random stage,
it is perhaps best to write the "rear recover" log directly into a file at the save place as soon as this is possible (instead of copying it just before "rear recover" finishes).

**Comment by gdha** [comment]
post-pone this to rear-1.18

**Comment by jsmeix** [comment]
I will implement it.

I think /mnt/local/root/ is o.k. but probably not really
the  best directory for that.

See also https://github.com/rear/rear/issues/706

I think only the plain log file is not fully sufficient.
I prefer to also keep other recovery-related data.

In the end what I like to keep is all what is needed
so that the admin or rear upstream can do later
a full detailled analysis of a recovery.

In particular for professional support
(e.g. from Relax-and-Recover upstream or
from our SUSE Linux Enterprise support department)
the ability to do a full detailled analysis after a recovery
is mandatory.

This is another reason why I would like to keep
the 'rear recover' log et alii by default so that this
information is by default available after a recovery.

**Comment by jsmeix** [comment]
As a first step I implemented https://github.com/rear/rear/issues/706

But for this issue here I need a bit more time to think about how to do it.

Because currently it is copied as an exit task I wonder if this is not yet sufficiently fail-safe - at least for normal error exits.

I assume the exit tasks are called for any exit (i.e. also when there is
a normal error exit) as far as I understand _input-output-functions.sh
<pre>
builtin trap "DoExitTasks" 0
</pre>
and "help trap"
<pre>
trap: trap [-lp] [arg signal_spec ...]
  ... If a SIGNAL_SPEC is EXIT (0)
  the command ARG is executed on exit from the shell.
  ...
</pre>

**Comment by Robertaquino102uk** [comment]
- [ ] - [ ] #googleclouduk #GoogleDocs #googlechrome #googlecloudplatform #GOOGLECLOUD_JP #google #GooglePlay #FederalReserve #libertytax #riverside #perris #googlefr FederalTransit Administration (FTA) FBI – Federal Bureau of Investigation #losangeles #googleplayservices #googleconconsole #pakistan #apache2.0 #googleearth #Samsung #FederalAviationAdministration #federalrailwayadminstration #tmobile #ATF #googleSwitzerland #googlenewzealand #googleaustralia #googlekr #googledevelopers #googleindia #googlesouthafrica #googleclouduk #libertytax #t-mobile #timcook #thomasdohmke  #Michigan tomcole@thetaxdoctorinc.com  EXCEPT AS SET IN THIS AMENDMENT 2021 original agreement as amended remains in full force &effect center services your area form ss-510-2021
Non face to face distribution tobacco products advertising promotions in connection with 3cfr10270 handicap code of federal regulations compilation of procedure 

Dea my not  establish any open cases regarding pharmacy information us Supreme Court with out acknowledging the the correct information and the correct person.failure to provide any consent or failure to read Miranda rights any information my not be allowed to be given or used against them regarding pharmacy records under any circumstances under a health care provider my not be asked personal information if they do not know 

- [ ] https://www.facebook.com/100094101652538/posts/266813939798659/?app=fbl
Violation my result to federal arbitration act Open Source Initiative approved license 
Version 2.0 submitted feb 8 2004  submitter Kevin coar  spdx short identifier Apache 2.0? Steward Apache software foundation 1 through 9 of this document intellectual property mean as distribution required under applicable laws www.gnu.org/licenses gpl-3.0 -standalone  violation America with disability act title (2) HTTPS://www.eitc.irs.gov/tax-preparer-toolkit/preparer-due-diligence/due-diligence-law-and-regulation marked with a serial number ATF.gov/rules-underregulation/permanent-brandy-permit-concealdeadly Federal) rules of criminal procedures house of representatives 116th Congress. federal civil rights regarding federal arbitration  act permits civil damages pertains against violation of constitutional rights. Code of federal law discrimination retaliation act unauthorized reproduction or distribution of this copyrighted work is illegal.criminal copyright infringement without monetary gain is investigated by the fbi & is punishable by up to 5 years in federal prison & a fine of $250,000 sec 403 misuse of federal   agency name arseal elijah ecuming
