### ISSUE TITLE
"rear recover" mount.nfs failed with "rpc.statd is not running but is required for remote locking"

### ISSUE THREAD

**Issue by snxkunwar** [rear/rear#2100]
Hello Everyone,

 I have taken backup using REAR and stored on the 
NFS server. I am trying to restore that backup while recovering i am facing issues after run #rear -d -v recover its showing mount.nfs mounting xx.xx.xx.70:/media/nfs failed reason given by server no such file or directory. But on the NFS server /media/nfs directory is available. 
 
 
 please provide some adequate solution that will be appreciated.
 
 
 Thanks.

![recover](https://user-images.githubusercontent.com/48988607/55073728-7643c900-50b4-11e9-9a66-c8ae2c8339f2.PNG)

**Comment by dcz01** [comment]
@snxkunwar 
Hello, why do you haven't filled out the support template?
Which operating system are you using?
Which version of ReaR are you using?
Have you activated the following services for the backup? (services described here are for RHEL/CentOS 6 or an older SUSE operating system)
````
chkconfig rpcbind on
chkconfig rpcidmapd on
chkconfig nfslock on
chkconfig netfs on
````

**Comment by snxkunwar** [comment]
> Have you activated the following services for the backup

Hello @dcz01 
Thank you for your reply.

Sir i don't get the term support template can you please explain about the support template.
Currently, we are using **Ubuntu 16.04**  operating system.
We are using  ReaR version **rear_2.4-0git**
We have taken backup and stored on the NFS server successfully.  The above issues are facing while recovering server. 



Thanks.

**Comment by dcz01** [comment]
@snxkunwar 
Well this is the normal support template here (normally opened automatically when opening a new case):

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Description of the issue (ideally so that others can reproduce it):

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):



Ok, i'm not a Ubuntu user and i haven't a such system here to test, but i would say that here is an problem by accessing the nfs server even if the config file isn't correct to restore or the nfs server is down.
Have you set an access only to this server or all servers which want to access the nfs server?
Maybe the wrong servername or ip adress comes along.

**Comment by jsmeix** [comment]
@snxkunwar 
you get our issue template
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
when you click on the "New Issue" button on
https://github.com/rear/rear/issues

I use (on openSUSE and SLES) in my etc/rear/local.conf always
```
BACKUP_OPTIONS="nfsvers=3,nolock"
```
for example see
https://github.com/rear/rear/blob/master/usr/share/rear/conf/examples/SLE11-ext3-example.conf
thar reads (excerpt)
```
# BACKUP_OPTIONS variable contains the NFS mount options and
# with 'mount -o nolock' no rpc.statd (plus rpcbind) are needed:
BACKUP_OPTIONS="nfsvers=3,nolock"
```

**Comment by jsmeix** [comment]
No news is good news.
