### ISSUE TITLE
Error in grabbing name during saving partition layout (on name containing spaces)

### ISSUE THREAD

**Issue by gdha** [rear/rear#212]
Error handling 'labels with spaces' in script `layout/save/GNU/Linux/20_partition_layout.sh`

```
++ read partition_nr size start junk
+++ grep '^3:' /tmp/rear.M5FFilyg9X8i2zw/tmp/parted
+++ cut -d : -f 6
++ type='EFI System Partition'
++ [[ -z EFI System Partition ]]
++ sed -i '/^3 /s/$/ EFI' System Partition/ /tmp/rear.M5FFilyg9X8i2zw/tmp/partitions
sed: -e expression #1, char 13: unterminated `s' command
++ read partition_nr size start junk
+++ grep '^4:' /tmp/rear.M5FFilyg9X8i2zw/tmp/parted
+++ cut -d : -f 6
++ type=freedom-boot
++ [[ -z freedom-boot ]]
++ sed -i '/^4 /s/$/ freedom-boot/' /tmp/rear.M5FFilyg9X8i2zw/tmp/partitions
```

**Comment by jsmeix** [comment]
Unfortunately via
https://github.com/rear/rear/commit/2540c7a2319791b58fa2b9c87fdefbe3c5341b4c
the duplicated quoting to make parted work via
https://github.com/rear/rear/commit/316b5f8d5aa5bb96b8aa037266912a59e6cda046
got removed (I assume because no comment explained why that overcomplicated
looking duplicated quoting is actually needed), cf.
https://github.com/rear/rear/issues/1563#issuecomment-358965623
and subsequent comments.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1706 merged
this issue should be again fixed to a currently reasonable extent
which means: Currently it fails for UTF-8 encoded strings
so that UTF-8 encoded GPT partition names
are not (yet?) supported.
