### ISSUE TITLE
Save the entire system to the single ISO image

### ISSUE THREAD

**Issue by geksi** [rear/rear#2141]
For small systems, is it possible to save the whole system to one single ISO image? Business case - restricted DMZ with no backup, nfs, etc.
Thank you!

**Comment by jsmeix** [comment]
Yes,
because it is possible to have the backup inside the ISO image
(usually the ISO contains only the ReaR recovery system).

See what "man rear" tells about `BACKUP_URL=iso://`
e.g. online at
https://github.com/rear/rear/blob/master/doc/rear.8.adoc

It is even possible to spilt it onto more than one ISO image,
see what usr/share/rear/conf/default.conf reads about
`ISO_MAX_SIZE`

But I have no personal experience with using `BACKUP_URL=iso://`
so that I don't know about the details here (I had tested it once
but I do not use it regularly).

**Comment by jsmeix** [comment]
In https://github.com/rear/rear/issues/1545
I had used this /etc/rear/local.conf
```
OUTPUT=ISO
OUTPUT_URL=nfs://10.160.4.244/nfs
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL="iso:///mybackup"
```
but in a 'restricted DMZ with no backup, nfs, etc'
`OUTPUT_URL=nfs://10.160.4.244/nfs` cannot work.

I think `OUTPUT_URL=file://` or `OUTPUT_URL=null`
(see "man rear") could help in this case.

**Comment by jsmeix** [comment]
Alternatively you may think about using
`OUTPUT=USB` and `BACKUP_URL=usb://`
see "man rear" and have a look at
http://relax-and-recover.org/documentation/getting-started
and see the `OUTPUT=USB stuff` section in
usr/share/rear/conf/default.conf

**Comment by jsmeix** [comment]
Because "no news is good news" I assume it is sufficiently answered.
