### ISSUE TITLE
[Question] Duplicate entries within 'releases'

### ISSUE THREAD

**Issue by malvinas2** [rear/rear#2167]
Not really an issue, but may I ask why there are two identical files of each version under [releases](https://github.com/rear/rear/releases)  ? 
E.g. you find an entry called "2.5" and another one called "rear-2.5", "2.4" and "rear-2.4" and so on. 
Checksum and content of the linked files seem to be completely the same?

Is this a github thing?

**Comment by jsmeix** [comment]
@malvinas2 
I don't know about the magic details behind
but from looking at the tag names at
https://github.com/rear/rear/releases
e.g. `2.5` and `rear-2.5`
I guess this is because of
```
Tag version in master branch:

git tag -s -a rear-2.xx -m "Rear release 2.xx"
git tag -s -a 2.xx -m "Rear release 2.xx"
```
in our `Release process` description at
https://github.com/rear/rear/wiki/Release-process

I assume the two tags with different names
like `2.5` and `rear-2.5` are intentional.
