### ISSUE TITLE
Booted into the USB, Can't Recover

### ISSUE THREAD

**Issue by gaia** [rear/rear#2193]
* Relax-and-Recover 2.4 / Git (installed via apt)

* Debian 10

* BareMetal

* x86_64

* UEFI + GRUB

* Root on mdadm, NVME disk attached, rear on USB flash drive:

* Booted into the USB disk, ran `rear recover`, got 
![image](https://user-images.githubusercontent.com/87547/61611981-20220500-ac12-11e9-90a5-29431727e0ae.png)

* Workaround: ?

**Comment by gozora** [comment]
Can it be that /usr/share/rear is symlink somewhere, on your origibal system?

V.

**Comment by gozora** [comment]
Can it be, that /usr/share/rear is symlink somewhere on your original system?

V.

**Comment by gozora** [comment]
Sorry for accidental close of this issue. Missclicked on phone :-)

V.

**Comment by gaia** [comment]
> Can it be, that _/usr/share/rear_ is symlink somewhere, on your original system?
> 
> V.

It is not (borg is `/usr/sbin/borg -> /path/to/borg-linux64`)

![image](https://user-images.githubusercontent.com/87547/61612815-6b3d1780-ac14-11e9-8a54-8af3f0e26fa4.png)

**Comment by gozora** [comment]
At the first sight, it looks like you are missing _/usr/share/rear_ directory in you ReaR recovery system, but based on provided data I can't tell why.
@gaia maybe try to correctly fill [ReaR issue template](https://github.com/rear/rear/issues/new) and someone might have an idea what is wrong...

V.

**Comment by gaia** [comment]
sorry, what is missing from the template?

**Comment by gaia** [comment]
it is missing from the rescue disk

![image](https://user-images.githubusercontent.com/87547/61649899-43c36a80-ac67-11e9-9efa-bad65d72cd6b.png)

**Comment by gozora** [comment]
> sorry, what is missing from the template?
For me the most important pieces ...

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf")
* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

> is there a variable that needs to be set correctly for it to be included? IMHO it should be included no matter what

Normally _/usr/share/rear/_ is included by [COPY_AS_IS](https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L1224) in [default.conf](https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf)
Since I've already removed your _local.conf_ from previous issue, and you did not provided any for this issue, I'll do again a blind guess ... 
Is there a chance that you've somehow set/reset COPY_AS_IS variable in your _local.conf_/_site.conf_ ?

V.

**Comment by gaia** [comment]
it works now, you guessed right, again. gracias!
