### ISSUE TITLE
Selecting default editor in ReaR

### ISSUE THREAD

**Issue by adatum** [rear/rear#2209]
By default in recovery mode, selecting a menu item that requires editing opens vi. Is it possible to set the default (possibly in local.conf) to something else, for example nano? 

I know nano is available in the ReaR shell, but it would be nice to stay in the recovery workflow with the desired editor.

Or of course I could try learning vi..

**Comment by jsmeix** [comment]
We had the same request in the past, see
https://github.com/rear/rear/issues/1298

For now using in user dialogs the generic choice
```
Use Relax-and-Recover shell and return back to here
```
is the only way to do whatever one wants.

I unerstand the request that in the ReaR recovery system things like
```
# export EDITOR="/bin/nano"

# rear recover
```
should make those user dialogs use $EDITOR instead of the
currently hardcoded 'vi'.

Currently - and for some more weeks - I am not in the office
so that I cannot do actual work on ReaR but as time permits
I will have another look if I could find a sufficiently simple and
fail safe working way how the user could specify his preferred
editor in the ReaR recovery system.
