### ISSUE TITLE
Are SAN boot disks (with "mpath") supported by "rear" ?

### ISSUE THREAD

**Issue by WautersPh** [rear/rear#228]
Dears,

I'm getting the following error when attempting to "rear recover" a RHEL 5.6 system having its boot disk on the SAN.

Can rear handle such a configuration or is "rear" only foreseen for local system disks ?
Or am I missing a critical setup in "rear" somewhere ?

Thanks on forehand for your help.

Regards.

Philippe

**Comment by DanielBerglar** [comment]
Hello,
i know this issue is known and has a workaround but i´m facing a similar problem and have some additional findings.

I´m using SLES 11 SP3 on a HP Blade Server with SAN disks only.
after the "rear -v mkbackup" with the following local.conf:
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=nfs://xxxxxxxxxxxxxxxxx
ONLY_INCLUDE_VG=( 'VG00'  )
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y

the disklayout.conf file looks like this:
#disk /dev/sda 5368709120 msdos
#part /dev/sda 1077511680 2097152 primary boot /dev/sda1
#part /dev/sda 4289097728 1079611392 primary none /dev/sda2
#disk /dev/sdb 26843545600 
#disk /dev/sdc 5368709120 msdos
#part /dev/sdc 1077511680 2097152 primary boot /dev/sdc1
#part /dev/sdc 4289097728 1079611392 primary none /dev/sdc2
#disk /dev/sdd 26843545600 
#disk /dev/sde 5368709120 msdos
#part /dev/sde 1077511680 2097152 primary boot /dev/sde1
#part /dev/sde 4289097728 1079611392 primary none /dev/sde2
#disk /dev/sdf 26843545600 
#disk /dev/sdg 5368709120 msdos
#part /dev/sdg 1077511680 2097152 primary boot /dev/sdg1
#part /dev/sdg 4289097728 1079611392 primary none /dev/sdg2
#disk /dev/sdh 26843545600 
....
multipath /dev/mapper/mpathb /dev/sdb,/dev/sdd,/dev/sdf,/dev/sdh
multipath /dev/mapper/mpatha /dev/sda,/dev/sdc,/dev/sde,/dev/sdg
part /dev/mapper/mpatha 1077511680 unknown primary boot /dev/mapper/mpatha_part1
part /dev/mapper/mpatha 4289097728 unknown primary none /dev/mapper/mpatha_part2

When i restore from this iso without correcting the "unknown" start sectors for the mpatha/b partitions the system wont boot. I´m setting up grub manualy after restore.

I´m writing cause i´m not shure if you mentioned that the start sectors for the partitioning are not correctly collected during backup.
Will there be a fix for the next release?

Kind regards
Daniel

**Comment by gdha** [comment]
@DanielBerglar I rather close this issue now as rear-1.17 will be released soon. If your problem still occurs I would propose to open a new issue for it (as now it is nested somewhere deep in another kind of issue).
