### ISSUE TITLE
SLES 12.4 : backup keep running forever and doesn't end up 

### ISSUE THREAD

**Issue by akashlate** [rear/rear#2343]
Hi,
We configured REAR for our SUSE server.
when we take backup using command 'rear -d -D mkbackup' the command. backup never finishes and in log we found below entries continuously
(Rear Version : rear118a-1.18.a-8.3.x86_64
Ebiso Version : ebiso-0.2.4-1.23.x86_64)
Please find attached 
[rear-mumhanaebg.log](https://github.com/rear/rear/files/4349151/rear-mumhanaebg.log)
[local.conf.txt](https://github.com/rear/rear/files/4349153/local.conf.txt)

local.conf and log files

++ kill -0 68805
+++ awk '{s+=$1} END {print s}'
+++ stat -c %s /tmp/rear.YbYqGM7FJAH87pU/outputfs/mumhanaebg/backup.tar.gz
++ size=2248261632
++ ProgressInfo 'Archived 2144 MiB [avg 205 KiB/sec]'
++ echo -en '\e[2K\rArchived 2144 MiB [avg 205 KiB/sec]\e7'
++ sleep 1
++ kill -0 68805
+++ awk '{s+=$1} END {print s}'
+++ stat -c %s /tmp/rear.YbYqGM7FJAH87pU/outputfs/mumhanaebg/backup.tar.gz
++ size=2248261632
++ ProgressInfo 'Archived 2144 MiB [avg 205 KiB/sec]'
++ echo -en '\e[2K\rArchived 2144 MiB [avg 205 KiB/sec]\e7'
++ sleep 1

**Comment by jsmeix** [comment]
@akashlate 
please provide us the information we ask for, see
https://raw.githubusercontent.com/rear/rear/master/.github/ISSUE_TEMPLATE.md
You get that automatically when you click on the [New issue] button at
https://github.com/rear/rear/issues

In your https://github.com/rear/rear/files/4349151/rear-mumhanaebg.log
I see (excerpts):
```
Archived 29 MiB [avg 15120 KiB/sec]
Archived 43 MiB [avg 14992 KiB/sec]
...
Archived 1302 MiB [avg 24244 KiB/sec]
Archived 1308 MiB [avg 23928 KiB/sec]
...
Archived 2131 MiB [avg 13899 KiB/sec]
Archived 2144 MiB [avg 13808 KiB/sec]
Archived 2144 MiB [avg 13722 KiB/sec]
...
Archived 2144 MiB [avg 10025 KiB/sec]
Archived 2144 MiB [avg 9979 KiB/sec]
...
Archived 2144 MiB [avg 1000 KiB/sec]
Archived 2144 MiB [avg 999 KiB/sec]
...
Archived 2144 MiB [avg 203 KiB/sec]
```
so speed seems to decrease by a factor of 100
from about 20000 KiB/sec to about 200 KiB/sec.

Because you use BACKUP=NETFS I guess
it is perhaps your NFS server that gets somehow
slower and slower in receiving the backup data?

In general:
You use a rather old ReaR version 1.18 from 2016.
I would first and foremost recommend to upgrade
to a more recent ReaR version, see the sections
"rear / rear116 / rear1172a / rear118a / rear23a"
and
"Testing current ReaR upstream GitHub master code"
and
"SUSE support for Relax-and-Recover"
in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
Because "no news is good news" I assume the root cause was found
that let the backup become slower and slower in this particular case
so the issue can be closed.
