### ISSUE TITLE
rear mkrescue fails with ERROR: The BACKUP method 'INTERNAL' is not known to ReaR.

### ISSUE THREAD

**Issue by OliverO2** [rear/rear#2352]
* ReaR version: Relax-and-Recover 2.5 / Git
* System architecture: x86
* Description of the issue:

When using a backup method which is not part of the rear distribution, `rear mkrescue` fails with
```
ERROR: The BACKUP method 'INTERNAL' is not known to ReaR.
Some latest log messages since the last called script 035_valid_backup_methods.sh:
  2020-03-30 23:13:34.319009171 Including prep/default/035_valid_backup_methods.sh
```

* Possibly related to: 8eb72c1d845d2b91fa76f18d47c74454ed5432ec

* Solution: Instead of checking the contents of `default.conf` for lines looking like `BACKUP=<method>`, a more fail-safe solution would be to check for the existence of `$SHARE_DIR/backup/<method>`.

**Comment by jsmeix** [comment]
How `BACKUP=INTERNAL`is used is described in
https://github.com/rear/rear/pull/2353#issuecomment-606585731
that reads in particular
```
Yes, there is no INTERNAL backup method in ReaR
as it's just what I'm using over here.
Actually, I have these directories, which integrate nicely
with ReaR updates as there is no common code:

backup/INTERNAL
build/INTERNAL
prep/INTERNAL
restore/INTERNAL

Configuration is done entirely via one line in site.conf:

BACKUP=INTERNAL
```
so this issue here is fixed via
https://github.com/rear/rear/commit/e98c8adcd75d043672bbed9564bedef377d9639e
because now prep/default/035_valid_backup_methods.sh
tests for a `$SHARE_DIR/restore/$BACKUP` directory
that exists in this particular case here.
