### ISSUE TITLE
combining volumes

### ISSUE THREAD

**Issue by Hardcore-fs** [rear/rear#2413]
Sometimes in case of emergency. we have to do a fast restore to a different system, with less drives

if  Original system has:
/dev/sda1
/dev/sdb1
both of say 16 GB

is there an easy way on restore to bring sdb1 into say /dev/sda3
if the new system drive is 146gb

**Comment by gozora** [comment]
Hi @Hardcore-fs,

"Easy" is relative, because what is easy basically depends on personal skills ...
But in general, yes ReaR can move content from one partition to another during `rear recover` workflow.

V.

**Comment by Hardcore-fs** [comment]
yep i did it manually.... 
but it took two attempts to find the right menu to get out and the right stage in the process.
I would be real nice if  there was a 'squash' function, 
In the end I think i only had to change a few numbers & change sdb1-> sda3

**Comment by jsmeix** [comment]
@Hardcore-fs 
a side note FYI:

In general regarding system migration with ReaR see
https://github.com/rear/rear/issues/2339#issuecomment-598067616
and follow the links therein in particular see
http://lists.relax-and-recover.org/pipermail/rear-users/2018-November/003626.html
and also follow the links therein.

Migrating an original system that was on /dev/sda1 and /dev/sdb1
both of 16 GB onto replacement hardware with a single /dev/sda3
that has 146 GB could be more or less straightforward by adapting
the matching entries in var/lib/rear/layout/disklayout.conf
as long as only filesystems on plain partitions are used
but things get tricky when filesystems on higher level strorage objects
like LVM logical volumes are used because there is no automatism
in ReaR that adapts (size) vaules of higher level strorage objects
so you need to do all that manually.
