### ISSUE TITLE
Rear with Bareos service not running on Recovery

### ISSUE THREAD

**Issue by Theprim0** [rear/rear#2490]
Rear version: 2.4
OS: Centos 7

When im restoring with "rear recover", i see it can talk to Bareos Director and Start the Job for recovery, but the issue comes when Director tries to connect to the client to port 9102. 

`bareos-dir JobId 47492: Fatal error: lib/bsock_tcp.cc:131 Unable to connect to Client: TEST-CLIENT on 182.11.53.216:9102. ERR=Conexión rehusada`

On the restoration machine I just see port 22 listening. There's no way Director can connect to the client if 9102 is not listening. Also I can't find a service to start bareos-fd

Thanks.

**Comment by gdha** [comment]
@Theprim0 Please have a look at https://gist.github.com/gdha/178504db0f6e0099848c2963ece81b6a#file-rear-automated-test-sh-log-L197 for an example local.conf - perhaps your `/etc/rear/local.conf` was not complete - we cannot tell as it was not attached.

**Comment by jsmeix** [comment]
@Theprim0 
I would like to know how you did enter your issue report
because normally I would assume one uses the [New issue] button on
https://github.com/rear/rear/issues
which leads to
https://github.com/rear/rear/issues/new
which shows
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
which lists what information we need to be able to do something useful.

In general regarding issues with third-party backup tools:
Usually we at ReaR upstream do not use third-party backup tools
so usually we cannot reproduce issues with third-party backup tools.
Nevertheless we try to help - provided we get sufficient information
so that we have a chance to do provide some useful help.

In particular regarding Bareos you may also contact the Bareos team via
https://github.com/bareos

**Comment by Theprim0** [comment]
I resolved this issue months ago, the problem was:

ReaR could not install/start bareos-fd daemon because on the client, I had 2 lines commented out:

![image](https://user-images.githubusercontent.com/13757003/104596534-6116a080-5674-11eb-9508-92ed2682627b.png)

To make this work, i just commented them both and then made the new iso.

The problem it's because when ReaR tries to recover, it does not understand the python plugin, so it won't start.

**Comment by gdha** [comment]
@Theprim0 So, you did not need any plugin for the recovery, right? Could you briefly explain what these plugins are meant for?  And, how do we know these are not required at all? Otherwise, python and the `/usr/lib64/bareos/plugins` could be copied over to the DR mediam?

**Comment by Theprim0** [comment]
At normal cases, this is not a problem, but it is if you use a plugin with Bareos.

In my case, I was using the package *bareos-filedaemon-python-plugin* to make MySql database backups with Bareos.
There are plugins to backup Postgres, Mysql, LDAP, MSSQL,... databases. 

So I guess if there's more people using Bareos with a plugin as this one, ReaR may not work as expected.

Don't exactly remember if my restore didn't work was because it was either Bareos trying to load the plugins or Bareos trying to use python. Or both. (Inside booted ISO)

Maybe if ReaR could come with the needed package, this issue can be resolved? At least resolved as make it run and restore the files, but not the database.

More info about Bareos plugins:
https://docs.bareos.org/TasksAndConcepts/Plugins.html

I know this is a specific case, and not too much people using ReaR with Bareos, and even less with a plugin, but some may, and if that's the case, this post may help

**Comment by gdha** [comment]
@Theprim0 Thank you so much for the prompt reply and useful explanation. I will check it out.
