### ISSUE TITLE
Backup NBKDC is not compatible with NovaStor DataCenter 8.0.0 or newer

### ISSUE THREAD

**Issue by JohannesRoehlNovaStor** [rear/rear#2518]
ReaR version: 2.6

ReaR version: Fedora Workstation 32 and other

ReaR configuration files:

```
OUTPUT=ISO
BACKUP=NBKDC
SET_STATIC_NETWORKING=y
```

Hardware:
VMware guest and other

Description of the issue:

If NovaStor DataCenter 8.0.0 or higher is installed and `BACKUP=NBKDC` is used, several issues are triggered:

1. The installation directory of NovaStor DataCenter is not found, so `rear mkbackup` fails
2. Important files are not copied to the live image, preventing network connection with NovaStor DataCenter backup server
3. Some minor issues

Patches for these issues are already in the works, and are in NovaStor internal review. A pull request will be published, once internal review is finished.

**Comment by jsmeix** [comment]
@JohannesRoehlNovaStor 
thank you in advance for your contribution to ReaR
to improve `BACKUP=NBKDC` support in ReaR.

Contributions for third-party backup tool support in ReaR
are much appreciated because we at ReaR upstream
usually do not have those third-party backup tools
(in particular not when a third-party backup tool is proprietary software)
so in case of issues with third-party backup tools and ReaR
we can usually do nothing but totally depend on contributions
from those who use and know about the third-party backup tools.

Have a relaxing and recovering weekend!

**Comment by JohannesRoehlNovaStor** [comment]
@jsmeix: Thanks, and you are welcome! I wish you a nice weekend, too!

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/2529 merged this issue is done.

@JohannesRoehlNovaStor 
thank you for keeping BACKUP=NBKDC support in ReaR up to date!

**Comment by JohannesRoehlNovaStor** [comment]
You are welcome! Thank you for merging my commits!
