### ISSUE TITLE
machine is not getting booting post recovery in physical machine (OS mirroring RAID 1) 

### ISSUE THREAD

**Issue by cvijayvinoth** [rear/rear#2630]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
BACKUP=RSYNC
RSYNC_PREFIX="yuvaraj1_${HOSTNAME}"
BACKUP_PROG="/var/www/html/imageBackup/rsync"
OUTPUT_URL=rsync://yuvaraj1@192.168.1.123::rsync_backup
BACKUP_URL=rsync://yuvaraj1@192.168.1.123::rsync_backup
BACKUP_RSYNC_OPTIONS+=(-z --progress --password-file=/var/www/html/xxxxx/xxxx)
ISO_DIR="/var/www/html/imageBackup/iso/$HOSTNAME"
MESSAGE_PREFIX="$$: "
PROGRESS_MODE="plain"
AUTOEXCLUDE_PATH=( /tmp )
PROGRESS_WAIT_SECONDS="1"
#export TMPDIR="$(</etc/rear/path.txt)/imageBackup/iso/"
export TMPDIR="/var/www/html/imageBackup/iso/"
PXE_RECOVER_MODE=automatic
ISO_FILES=("/var/www/html/imageBackup/rsync")
ISO_PREFIX="${HOSTNAME}"
ISO_DEFAULT="automatic"
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
PC

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86 compatible

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
BIOS & GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT" or "lsblk" as makeshift):
[lsblk.txt](https://github.com/rear/rear/files/6631344/lsblk.txt)

* Description of the issue (ideally so that others can reproduce it):

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

* rear -D recover log file attached
[rear-localhost (2).log](https://github.com/rear/rear/files/6630961/rear-localhost.2.log)
![2021-06-10](https://user-images.githubusercontent.com/426209/121522046-589f7780-ca12-11eb-8cbc-c92973baf3ec.jpg)

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by pcahyna** [comment]
`Warning: rsync --fake-super not possible on system (192.168.1.6) (please upgrade rsync to 3.x)`

I suspect you are using an old rsync version. I am working on changes that will turn this Warning into an Error and raise it during backup, instead of waiting for problems during restore.

For now, please try again backing up and restoring with the system rsync (it is new enough).

**Comment by cvijayvinoth** [comment]
@pcahyna  : sure let me check and update you.

**Comment by cvijayvinoth** [comment]
Thanks for your help. Its working fine.

**Comment by pcahyna** [comment]
> `Warning: rsync --fake-super not possible on system (192.168.1.6) (please upgrade rsync to 3.x)`
> 
> I suspect you are using an old rsync version. I am working on changes that will turn this Warning into an Error and raise it during backup, instead of waiting for problems during restore.

For the reference, the changes in question are #2632, but during the work on the PR I found that using the rsync daemon does not work together with the detection of the ability to use --fake-super. I would rather recommend to use the ssh transport (URLs without the `::`) instead of the rsync daemon. (There is apparently no way to specify from the client side that the daemon should use --fake-super on its side, `-M--fake-super` is accepted but ignored.)
