### ISSUE TITLE
REAR ISO cannot be created as bootable 

### ISSUE THREAD

**Issue by MubbashirAdnan** [rear/rear#2668]
Hi,
I have been working around with REAR for a long while. I have created ISO using CentOS7 installed on VM using:
OUTPUT=ISO
OUTPUT_URL=null
BACKUP=NETFS
BACKUP_URL="iso:///backup"

This has successfully created the ISO using "rear mkbackup". Generated ISO can be used on VM and it is booting without an issue. 

I am trying to convert this ISO to a Bootable USB (without using OUTPUT=USB) as i have to share these iso's and i want people to use them by creating bootables. 
I used Rufus to create bootable usb of the ISO but it is not booting on base system.  

Can you please guide on exact configuration for this case? i don't have a requirement to create backup as well, 'mkrescue' can also work in my case as i just require installed binaries to stay inside the ISO.

**Comment by gdha** [comment]
See http://relax-and-recover.org/documentation/faq

**Comment by MubbashirAdnan** [comment]
Thank you for your response @gdha , I have managed to resolve it using: 
- Creating ISO using mkbackup with the above configurations
- Then using "isohybrid /path/to/image.iso"
- Finally using "dd if=image.iso of=/dev/sdb"

Bootable created after converting to hybrid iso and making it bootable using dd is working.
* I was also stuck in the bigger to smaller / smaller to bigger disk migration - but resolved it by customizing the percentage accordingly in default.conf. 

I have a question @jsmeix @gdha : Is there a way to add a customized flash screen on boot at recovery? Because REAR can be used as creating custom Linux ISO images containing installed applications. So adding a custom screen in these cases will be great and helpful. 
By custom screen i mean just a flash screen at first recovery boot that might have customized color or text.

**Comment by gdha** [comment]
@MubbashirAdnan I used to have a simple splash screen with my very old project mkcdrec with isolinux. The howto can be found here: http://frantisek.rysanek.sweb.cz/splash/isolinux-splash-HOWTO.html

Create a splash file and add a copy line in script usr/share/rear/output/ISO/Linux-i386/300_create_isolinux.sh to try it out.
Keep us posted...

**Comment by MubbashirAdnan** [comment]
Thank you @gdha. Will try it out and let you know.

**Comment by MubbashirAdnan** [comment]
@gdha Can you please guide if i can change the default timeout settings that appear after we boot the ISO? 
To be more specific, i am using REAR as mkbackup with the backup included within the ISO. I am using it as migrator on variable disk layouts. When i choose automatic recover while booting,  i have to face 4 to 5 menus confirming disk layout and running disk creation scripts. I have to choose 1 (which is default) every time. The default timeout to choose option 1 is 300 seconds in each menu. Can i change this to 10 or 20 seconds? Thanks

**Comment by gdha** [comment]
@MubbashirAdnan  Use the variable USER_INPUT_TIMEOUT=3 in the local.conf file to define 3 seconds for example.

**Comment by jsmeix** [comment]
@MubbashirAdnan 
in general see the config variable descriptions in default.conf
e.g. the description of the various USER_INPUT_* config variables
that is is ReaR upstream master code currently at
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L240

**Comment by MubbashirAdnan** [comment]
Hello @gdha @jsmeix, Thank you for the help. Can you please let me know regarding the REAR ISO for migration on different disk sizes. How do i exactly configure manually if i face a disk size mismatch error while installing the generated ISO?  I have performed it using the default.conf by increasing the percentage. But i want to know if there is a way to easily change the configuration of disk size while ISO is installing. Please tell the exact lines that i have to write in runtime configuration. 

Using default.conf disk increase percentage: i created ISO on 500GB drive and I had to install it on 1TB disk size, so i increased the disk size to 100%. What if i have to install it on even bigger disk i.e. 2TB? should i go past 100%? 

Waiting for the kind response, Thanks :)

**Comment by jsmeix** [comment]
@MubbashirAdnan 

regarding migration to a system with a bit smaller or a bit bigger disk
see in conf/default.conf the description of the config variables
AUTORESIZE_PARTITIONS
AUTORESIZE_EXCLUDE_PARTITIONS
AUTOSHRINK_DISK_SIZE_LIMIT_PERCENTAGE
AUTOINCREASE_DISK_SIZE_THRESHOLD_PERCENTAGE

I reccommend to not use AUTORESIZE_PARTITIONS="yes"
with layout/prepare/default/430_autoresize_all_partitions.sh
because that may result bad aligned partitions in particular
bad aligned for what flash memory based disks  (i.e. SSDs) need
that usually need a 4MiB or 8MiB alignment (a too small value
will result lower speed and less lifetime of flash memory devices),
see the comment at USB_PARTITION_ALIGN_BLOCK_SIZE
in default.conf

In general regarding system migration with ReaR
(e.g. to a system with substantially different disk size):

In general migrating a system onto different hardware
(where "hardware" could be also a virtual machine)
does not "just work", cf. "Inappropriate expectations" at
https://en.opensuse.org/SDB:Disaster_Recovery

In sufficiently simple cases it may "just work" but in general
do not expect too much built-in intelligence from a program
(written in plain bash which is not a programming language
  that is primarily meant for artificial intelligence ;-)
that would do the annoying legwork for you.

In general ReaR is first and foremost meant to recreate
a system as much as possible exactly as it was before.

Additionally ReaR supports to migrate a system
but here "supports" means that ReaR provides a lot
that should help you to get such a task done
but it does not mean that it would "just work" without
possibly laborious manual settings and adaptions
with trial and error legwork until you made things work
for you in your particular case.

See also
http://lists.relax-and-recover.org/pipermail/rear-users/2018-November/003626.html
that provides additional information what one must manually adapt
when migrating onto different hardware.
