### ISSUE TITLE
disk reformatting issue during BMR on linux 7.9 physical server

### ISSUE THREAD

**Issue by nmaheve** [rear/rear#2720]
we are facing issue while doing BMR recovery . 

disk reformatting issue during the time of recovery , i have attached the snapshot of same as well 

![error](https://user-images.githubusercontent.com/89590205/142912365-6aafca56-5563-40c8-8d32-ce39e70c38e9.png)

![errror1](https://user-images.githubusercontent.com/89590205/142912527-5135dc6f-ec23-4fe8-8d7e-a0a84d0da4e4.png)

**Comment by jsmeix** [comment]
https://raw.githubusercontent.com/rear/rear/master/.github/ISSUE_TEMPLATE.md

**Comment by nmaheve** [comment]
Classification: Confidential
Hello Support ,

Here is the details

#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"): RHEL7.9

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): BareMetal

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI/grub2

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):DM

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it): file system is not getting restored

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content




From: Johannes Meixner ***@***.***>
Sent: Tuesday, November 23, 2021 12:47 PM
To: rear/rear ***@***.***>
Cc: Nikhil Kumar Maheve ***@***.***>; Author ***@***.***>
Subject: Re: [rear/rear] disk reformatting issue during BMR on linux 7.9 physical server (Issue #2720)

[CAUTION: This Email is from outside the Organization. Unless you trust the sender, Don't click links or open attachments as it may be a Phishing email, which can steal your Information and compromise your Computer.]

https://raw.githubusercontent.com/rear/rear/master/.github/ISSUE_TEMPLATE.md

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frear%2Frear%2Fissues%2F2720%23issuecomment-976216761&data=04%7C01%7Cnikhilkumar.maheve%40hcl.com%7C95b187812f2148e922b008d9ae513726%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637732486125112778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3LmeDDeRb5vXjalsYpOVxFpemW1lkCuIfSRk2Ye2nnQ%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVLQTPMCJJ3DIP5GBFZLVKDUNM5V5ANCNFSM5IRUBLZA&data=04%7C01%7Cnikhilkumar.maheve%40hcl.com%7C95b187812f2148e922b008d9ae513726%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637732486125112778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=pMIZ6PRml%2FdldZLPjQmipJipV5Z3wySi6991iPPxdVY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cnikhilkumar.maheve%40hcl.com%7C95b187812f2148e922b008d9ae513726%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637732486125122739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Wsti5LVlr5WEUInhAeYy96C1JZ7nKMlM8ZXuMr4XnwE%3D&reserved=0> or Android<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cnikhilkumar.maheve%40hcl.com%7C95b187812f2148e922b008d9ae513726%7C189de737c93a4f5a8b686f4ca9941912%7C0%7C0%7C637732486125122739%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4tPm6BKKUCxBrQWN8S8s7FEenRHFRPWE7udkmUxo3ek%3D&reserved=0>.

::DISCLAIMER::
________________________________
The contents of this e-mail and any attachment(s) are confidential and intended for the named recipient(s) only. E-mail transmission is not guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or may contain viruses in transmission. The e mail and its contents (with or without referred errors) shall therefore not attach any liability on the originator or HCL or its affiliates. Views or opinions, if any, presented in this email are solely those of the author and may not necessarily reflect the views or opinions of HCL or its affiliates. Any form of reproduction, dissemination, copying, disclosure, modification, distribution and / or publication of this message without the prior written consent of authorized representative of HCL is strictly prohibited. If you have received this email in error please delete it and notify the sender immediately. Before opening any email and/or attachments, please check them for viruses and other defects.
________________________________

**Comment by suraj952** [comment]
Requested details have been sent out over the email as well. do we have any update on this please.

**Comment by pcahyna** [comment]
Can you please attach the log of the failing restore, and also the disklayout.conf file (`/var/lib/rear/layout/disklayout.conf`)?

**Comment by pcahyna** [comment]
and do you restore to the same or identical hardware as was the original system, or is the hardware different? I am especially interested in your disk sizes, are they same as on the original hardware?

**Comment by suraj952** [comment]
We are trying to recover data on same machine. so there is no hardware mismatch issue should be occur and the logs we have already provided what we have handy and currently server is crashed.

**Comment by pcahyna** [comment]
@suraj952 I am interested in the log file offered in entry 2 on the last screen (/var/log/rear/reat-test _something_ .log). `/var/lib/rear/layout/disklayout.conf` is also present in the rescue system.  The script `/var/lib/rear/layout/diskrestore.sh` would also be interesting to have. Please fetch them from the rescue system (it should be possible to ssh/sftp to it, if the network is configured)  and attach them here.

**Comment by pcahyna** [comment]
oh and please try to rerun recover with the `-D` parameter (`rear -D recover`) and attach also a log file from this attempt, it will contain much more detail.

**Comment by pcahyna** [comment]
Hello Suraj, I don't see any files here. I think you should reply using the web interface instead of e-mail. In the web interface there is a bar titled "Attach files by dragging & dropping, selecting or pasting them." just below the text comment box. Click on it and upload your files.

**Comment by suraj952** [comment]
[rear-testl07dc.log](https://github.com/rear/rear/files/7626963/rear-testl07dc.log)

[BMR log file.zip](https://github.com/rear/rear/files/7626999/BMR.log.file.zip)

PFA the requested log files in zipped folder.
.

**Comment by suraj952** [comment]
Hi,

All the three files have been attached in zipped folder.

Regards,

Suraj Rawat | Storage Services
Office: +1(408) 722-9387 Extn 0 | Cell: +91-8742939172
Email: ***@***.******@***.***> | Web: http://www.aarp.org<http://www.aarp.org/>
***@***.***

**Comment by pcahyna** [comment]
Thanks, from the log I see that the problem most likely is "A volume group called rhel already exists." and is due to restoring to the disks with your original system, so the original volume group is still there. I can suggest wiping the old data first using `wipefs`, as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=1919989#c5. (that is, you boot the rescue system, and first you wipe data the old disks and only then you start `rear recover`. Or, you can restore to clean disks, if you have some spare disks with the same size as the original disks, and keep the old disks as backup.)

I also suggest to edit `/etc/rear/local.conf` in the rescue system and add the line `MIGRATION_MODE=n`. It can be seen from your screenshots that due to the presence of two disks of the same size, ReaR has switched to the so-called migration mode, which is usually used for migrating to a different hardware, and the restoration of LVM is then less faithful. As you are restoring to the same hardware, you don't need migration mode.

**Comment by suraj952** [comment]
[latest-log-after_wipefs.zip](https://github.com/rear/rear/files/7627318/latest-log-after_wipefs.zip)

We have wiped out the data in same way as given in Bugzilla link and did “rear recover” But still no luck.

Please find the latest logs for the same and let me know if you have any question related to this issue.

**Comment by pcahyna** [comment]
Now the layout recreation succeeds and your problem seems to be
```
Including restore/REQUESTRESTORE/default/200_prompt_user_to_start_restore.sh
2021-11-30 11:30:52.689499158 Please start the restore process on your backup host.

Make sure that you restore the data into /mnt/local (by default '/mnt/local')
instead of '/' because the hard disks of the recovered system are mounted there.

2021-11-30 11:30:52.733135532 Please restore your backup in the provided shell and, when finished, type exit
in the shell to continue recovery.
```
Have you restored your backup to the recreated filesystems? It seems that you have not and your filesystems are empty. What backup software are you using (what is the value of the `BACKUP` configuration variable)?

**Comment by suraj952** [comment]
We are using Rubrik backup software.

**Comment by suraj952** [comment]
yes we have tried to restore backup by running “rear recover” and but there was issue related to ownership of filesystem. I believe, that error can be found in log files which we had shared earlier.

**Comment by DamaniN** [comment]
@suraj952 and @nmaheve, `rear recover` only prepares the system for data recovery. You then have to go back to Rubrik and recover the actual data. The Rubrik agent should now be running on the rescue system, and you should be able to access it from Rubrik. Remember that when you recover the actual data from Rubrik to redirect the recover to `/mnt/local` instead of `/`.

See [Chapter 16](https://github.com/rear/rear/blob/master/doc/user-guide/16-Rubrik-CDM.adoc) of the ReaR user guide  for more details. You should be around step 11 now.

**Comment by pcahyna** [comment]
@suraj952 note that Rubrik CDM support was added to ReaR in version 2.6 by @DamaniN in PR #2249, but according to the logs and screenshot, you are using ReaR 2.4, so you must restore the data manually (not sure how, I have never used Rubrik CDM).
Concerning
> there was issue related to ownership of filesystem. I believe, that error can be found in log files

-if you mean these lines:
```
2021-11-30 11:31:42.229193058 Recreating directories (with permissions) from /var/lib/rear/recovery/directories_permissions_owner_group
'bin' -> 'usr/bin'
mkdir: created directory 'etc'
mode of 'etc' retained as 0755 (rwxr-xr-x)
chroot: failed to run command '/bin/bash': No such file or directory
2021-11-30 11:31:42.256494605 Failed to 'chown root:root etc' 
```
then this is not an "issue related to ownership of filesystem", but the fact that the recreated system is empty, there has been no backup restored to the reformatted disks. I see this in the log earlier:
```
Please start the restore process on your backup host.

Make sure that you restore the data into /mnt/local (by default '/mnt/local')
instead of '/' because the hard disks of the recovered system are mounted there.

2021-11-30 11:30:52.733135532 Please restore your backup in the provided shell and, when finished, type exit
in the shell to continue recovery.
```
Have you started the restore process when prompted? I suppose this prompt was shown on the screen as well.

(Anyway, this issue has digressed from the original disk reformatting issue, which is a known problem when using disks with prior data, and I believe it is solved already in the development version. For older versions, wiping the disks manually is an easy workaround, as shown by your latest log, which records that the disks were reformatted just fine.)

**Comment by suraj952** [comment]
@pcahyna and @DamaniN Currently server is crashed and as we have ran Wipe on the system so i think backup services also get wiped from the host and Rubrik CDM is also not able to communicate with the Host as RBS status showing disconnected. Can you share POA accordingly.

**Comment by pcahyna** [comment]
Sure, everything gets wiped from the host, simply because ReaR reformats all the disks, as the title of the issue ("disk reformatting issue") shows. You need to have the software needed for backup restoration in the rescue system. You haven't added the Rubrik CDM client there when creating the rescue media (ISO or USB)? If not, I suppose it will be posible to copy it to the rescue system from somewhere else and thus resolve your problem, but I can't help you with this, I know nothing about CDM. By the way, can you paste your `/etc/rear/local.conf` file here?

**Comment by suraj952** [comment]
Is it possible if you can join us on virtual session. our linux team can able to see the file system and you were saying that file syste m is empty so that would be great help if we can work together on the VR.

**Comment by DamaniN** [comment]
@suraj952, If you have re-installed the Rubrik CDM agent on the rescue system, you can register the rescue system with your Rubrik server. Assuming that you backed up the server in the past, you will be able to recover the data to it. The rescue system will be registered as a new host, so you will need to perform a redirected recovery of the data. If you need help with registration and restoring the data from Rubrik at this point, please contact Rubrik support.

You may run into a conflict where Rubrik thinks that the rescue system is the original system because it has the same IP address. Normally, the CDM integration with ReaR takes care of this. Since the proper version of ReaR wasn't used, this conflict will have to be taken care of manually. Rubrik Support can help with that. 

As listed in the link I provided above, be sure to recover the data in `/` to `/mnt/local`. After the data recovery, be sure to exit the ReaR shell prompt and answer the last question. This will allow ReaR to  finalize the rescue, and you will be able to reboot the rescue host properly.

**Comment by gdha** [comment]
@DamaniN  Thank you for your wise words.

**Comment by suraj952** [comment]
No @DaminiN we are not able to install rubrik services into server as server got crashed when we tried to  perform recovery from ISO backed up file. We tried to install Rubrik backup agent in crashed server but it's not working.

So if you guys can help over the virtual remote session that would be great. Also see the below snapshot and let us know what next step we need to perform from here.

***@***.***

Regards,

Suraj Rawat | Storage Services
Office: +1(408) 722-9387 Extn 0 | Cell: +91-8742939172
Email: ***@***.******@***.***> | Web: http://www.aarp.org<http://www.aarp.org/>
***@***.***

**Comment by DamaniN** [comment]
@suraj952, please create a case with Rubrik support for further help with re-installing the Rubrik agent on the rescue host.

**Comment by suraj952** [comment]
@DamaniN per your suggestion, Case #00286029 have been opened with Rubrik support for the same.

**Comment by pcahyna** [comment]
@suraj952 
> Hi, Please see the output below of /etc/rear/local.conf file here. ***@***.*** 

I don't see anything unfortunately, I suggest to use the web interface. Anyway, I hope that Rubrik support will be able to help you with CDM. I have a suggestion for you and maybe the Rubrik support: instead of trying to get the Rubrik client into the booted rescue system, wouldn't it be better to restore the entire backup to a different server and then copy the whole subdirectory to the `/mnt/local` directory at the rescue system during the rescue process, when ReaR asks to restore files? This could be done e.g. via rsync or via tar and ssh, something like `tar cf - . | ssh root@crashed_system "cd /mnt/local; tar xpf -"` (of course tar will need some more parameters to restore all the attributes properly, but that's the general idea). @DamaniN what do you think?

**Comment by pcahyna** [comment]
@DamaniN thanks a lot for looking into the issue.

**Comment by jsmeix** [comment]
I think this is meanwhile fixed or done outside of ReaR.
