### ISSUE TITLE
SUSE sle 15 SP4

### ISSUE THREAD

**Issue by andreacosta83** [rear/rear#2890]
Hi, will it come and if so when, will the .rpm for SUSE sle 15 SP4 be made available?

Or is it possible to use the .rpm from SP3?

Best regards.
Andrea

**Comment by jsmeix** [comment]
@andreacosta83 
what RPM packages are you talking about?

Is it about officially by SUSE supported SUSE Linux Enterprise
RPM packages from SUSE, then see the section
"SUSE support for Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

Or is it about voluntary openSUSE Build Service (OBS) RPM packages
e.g. at
https://build.opensuse.org/package/show/Archiving/rear
which is not built for any SLE version
or at
https://build.opensuse.org/project/show/Archiving:Backup:Rear
which is built for many Linux distributions and versions.

In particular it is built for SLE15 up to SLE15 SP3
but not for SP4 regardless that SLE15 SP4 is selected
on the OBS page where one can select what distributions
a package should be built for (that selection is only visible
for users who are logged in with admin permissions for the
Archiving:Backup:Rear project).
I will try to find out what is wrong there in OBS why it is
not built for SLE15 SP4 regardless that is it selected.

But normally it does not matter if ReaR is built
for SLE15 SP3 or SLE15 SP4 because ReaR is only bash scripts
which are same for all Linux distributions and versions.

What could cause trouble are RPM package install dependencies
so it could be impossible to install a RPM package
that was built for one Linux distribution version
on another Linux distribution version.

But for SLE15 SP3 versus SLE15 SP4 it is rather unlikely
that RPM package install dependencies will cause trouble.
When you can "just install" a ReaR RPM package that was
built for SLE15 SP3 on SLE15 SP4 you get the exact same
ReaR scripts installed as if you installed a ReaR package
that was built for SLE15 SP4 so an installable ReaR package
that was built for SLE15 SP3 will work same on SLE15 SP4
as a ReaR package that was built for SLE15 SP4.

FYI
because it is somewhat related as an addendum
you may have a look at the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
Got it!

For SLE15 SP4 and openSUSE Leap 15.4 things were changed
(compared to SLE15 SP3 and openSUSE Leap 15.3)
how RPM packages are built.

Up to SLE15 SP3 and openSUSE Leap 15.3 both were separated
regarding RPM package are build so in OBS there are two
separated things called "SLE_15_SP3" and "openSUSE_Leap_15.3"
where ReaR RPM packages are built for.

Accordingly there is
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/SLE_15_SP3/
which contains in particular
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/SLE_15_SP3/x86_64/rear-2.7-1.x86_64.rpm
with a size of 734140 bytes.

And there is
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/openSUSE_Leap_15.3/
which contains in particular
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/openSUSE_Leap_15.3/x86_64/rear-2.7-1.x86_64.rpm
with a size of 734144 bytes.

So two slightly different binary RPM packages
that contain two times the same software.

For SLE15 SP4 and openSUSE Leap 15.4 packages where Leap
inherits the package from SLE are built exactly same
so in OBS there is only one generic thing called "15.4"
where ReaR RPM packages are built for and there is only one
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/15.4/
which contains in particular
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/15.4/x86_64/rear-2.7-1.x86_64.rpm
with a size of 734172 bytes.

By the way:
I noticed that for "15.4" the architecture "ppc64l" was
not enabled to build ReaR RPM packages for that architecture.
I enabled it now because RPM package install dependencies
are different for different architectures so that now
in particular ReaR 2.7 as RPM package for SLE15 SP4
for the "ppc64l" architecture is now available at
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/15.4/ppc64le/

**Comment by andreacosta83** [comment]
> @andreacosta83
> what RPM packages are you talking about?

@jsmeix Sorry you're right, I didn't specify: I always fetched the RPMs from 
http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/ 
depending on the distro version used, where SLE_15_SP4 is not currently present.

So, summarizing, I can fetch and install from SLE_15_SP3 and I shouldn't have problems (if not for the dependencies) or you advise me to fetch and install the .rpm from the generic folder called "15.4"
(at URL: http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/15.4/ ) ?

**Comment by jsmeix** [comment]
For SLE15 SP4 the common folder for "15.4" software
is the right one - as far as I understand how OBS works.

In the end the SUSE or openSUSE version does not matter
as long as you can "just install" a ReaR RPM package because
all RPM package for a particular ReaR version contain the
same ReaR bash scripts so you get the same software installed.
