### ISSUE TITLE
relax-and-recover connot be shrinked (new disk more than 2% smaller)

### ISSUE THREAD

**Issue by sd2070953** [rear/rear#2912]
两台服务器磁盘都是lvm格式，源服务器硬盘大小为20，但是文件其实只有4G，  目标还原服务器磁盘大小为15G,足够装下系统文件，但是提示：如标题报错，目标磁盘小于源磁盘，这样我就没办法还原了。然后我找台目标磁盘为25G的服务器，可以正常还原系统。
有没有办法让目标磁盘小于源磁盘还能正常还原。谢谢。

**Comment by jsmeix** [comment]
@sd2070953 
all is only in English here.

Furthermore we show
https://github.com/rear/rear/blob/master/.github/ISSUE_TEMPLATE.md
when you use the [New issue] button on
https://github.com/rear/rear/issues

From the subject
"relax-and-recover connot be shrinked (new disk more than 2% smaller)"
I assume your issue is related to the section
"Resizing partitions in MIGRATION_MODE during 'rear recover'"
in usr/share/rear/conf/default.conf online e.g. at
https://github.com/rear/rear/blob/rear-2.7/usr/share/rear/conf/default.conf#L475
