### ISSUE TITLE
ERROR: Could not find 'isolinux.bin'. Maybe you have to set ISO_ISOLINUX_BIN [] or install the syslinux package ?

### ISSUE THREAD

**Issue by ph818** [rear/rear#2921]
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.7 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Ubuntu 22.10

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

```
$ cat /etc/rear/local.conf
### write the rescue initramfs to USB and update the USB bootloader
OUTPUT=USB

### create a backup using the internal NETFS method, using 'tar'
BACKUP=NETFS

### write both rescue image and backup to the device labeled REAR-000
BACKUP_URL=usb:///dev/disk/by-label/REAR-000
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
PC, lenovo

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI and GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
NVMe

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
list of devices, probably not relevant

* Description of the issue (ideally so that others can reproduce it):
running REaR for the first time fails with
```
$ sudo usr/sbin/rear -v mkrescue
ERROR: Could not find 'isolinux.bin'. Maybe you have to set ISO_ISOLINUX_BIN [] or install the syslinux package ?
```

* Workaround, if any:
sudo apt install isolinux

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
log contains what you would expect

Suggest adjusting the error message so it recommends the isolinux package.

**Comment by jsmeix** [comment]
No,
we won't recommends which software package to install
because we at ReaR upstream do not have the manpower
to implement that for the various Linux distributions
and then continuously maintain for the various versions
of the various Linux distributions what specific software package
in what version of what Linux distribution needs to be installed
to get this or that needed thing.

In particular regarding Ubuntu:
I am not a Ubuntu user
(and I won't find time to test things on Ubuntu) and
we at ReaR upstream do not have an active maintainer who uses Ubuntu
(and it seems Canonical is not sufficiently interested in ReaR)
so ReaR support for Ubuntu can be only as good as voluntary
conrtibutors who use Ubuntu contribute - which is much appreciated!

My above statement that we will not tell the user
what software package is missing
is meant for the generic code in ReaR.

We could have distribution specific code provided:

Distribution specific code is properly conditioned,
See the SetOSVendorAndVersion() function in lib/config-functions.sh
what variables are set how to which vaules to distinguish between
different distributions and distribution versions.
See layout/prepare/Linux-s390/205_s390_enable_disk.sh
for an example of distribution specific code inside a script.

AND

There is someone who continuously tracks and maintains
distribution specific code to keep it up to date in the future.

**Comment by jsmeix** [comment]
Via
https://github.com/rear/rear/commit/680a576b60d31c233a4adce8aecc38b37df19238
I fixed prep/ISO/Linux-i386/330_find_isolinux.sh
to no longer show a distribution specific software package name
to avoid misleading info when isolinux.bin cannot be found.
