### ISSUE TITLE
Stop supporting SLES10 and SLES11

### ISSUE THREAD

**Issue by schlomo** [rear/rear#2940]
According to https://www.suse.com/lifecycle/#product-suse-linux-enterprise-server it seems to me that with ReaR >2.7 we don't need to support SLES10 and SLES11 any more:
![image](https://user-images.githubusercontent.com/101384/220186947-b4eacc2e-ae71-42a6-be8e-c21cc96033a3.png)

SLES12 and SLES15 we of course need to support till 2027 and 2031.

@jsmeix can you confirm this?

If this is the case then I'd like to propose dropping support for those old OS versions and thereby also allow making use of more modern Bash features.

**Comment by jsmeix** [comment]
In general regarding public available information
when support ends for a SUSE product:
Those dates are the earliest dates when support ends.
For special cases under special conditions certain support
may last even longer (but is not commonly available).

But that doesn't matter for ReaR upstream because
SUSE supports the ReaR that is provided in SLE products.

What we support at ReaR upstream is documented in
our release notes, e.g. for ReaR 2.7 see
https://github.com/rear/rear/blob/rear-2.7/doc/rear-release-notes.txt#L3814

Regarding making use of more modern Bash features
(i.e. making use of bash 4 features)
we still have
https://github.com/rear/rear/wiki/Coding-Style

So this issue here is not about 
"Stop supporting SLES10 and SLES11"
but about
"switch from bash 3 to bash 4 as minimum required bash version"

**Comment by jsmeix** [comment]
SLES12 SP5 has GNU bash version 4.3.48

**Comment by jsmeix** [comment]
I think this one is obsoleted by
https://github.com/rear/rear/issues/2941

@schlomo 
feel free to reopen this one if I misunderstood.
