### ISSUE TITLE
Use_Static_Networking setting is being ignored

### ISSUE THREAD

**Issue by ZENAdmin-Ops** [rear/rear#3087]
* ReaR version ("/usr/sbin/rear -V"):
2.7

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Debian 11

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
OUTPUT_URL=file:///home/zen/debian11-DR6-recovery.iso
USE_STATIC_NETWORKING=”Yes”
IP=10.254.242.85
NM=255.255.255.0
GW=10.254.242.1
```
* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
Hyper-V VM

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):

* Description of the issue (ideally so that others can reproduce it):

The static networking configuration is being ignored.

I have tried using both:
```
USE_STATIC_NETWORKING=”Yes”
```
and
```
USE_STATIC_NETWORKING=Yes
```
In the log file I see the following:
```
2023-11-21 12:43:55.981052718 Including prep/GNU/Linux/210_include_dhclient.sh
2023-11-21 12:43:56.019326262 Detected an active Network Manager connection 'Wired connection 1' set up via DHCPv6
2023-11-21 12:43:56.020850060 Auto-enabling DHCP on the rescue system
```

* Workaround, if any:

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by jsmeix** [comment]
Set
```
USE_DHCLIENT="No"
```
to enforce disabling DHCP client on the rescue system.

With
```
USE_STATIC_NETWORKING="Yes"
```
[usr/share/rear/skel/default]/etc/scripts/system-setup.d/58-start-dhclient.sh
won't do anything so "Auto-enabling DHCP on the rescue system"
should not matter.

ReaR configuration file settings like
```
IP=10.254.242.85
NM=255.255.255.0
GW=10.254.242.1
```
should have no effect because IP, NM, GW
are no documented config variables.
See "man rear" the
section "RESCUE IMAGE KERNEL COMMAND LINE OPTIONS"
about "ip= nm= netdev= gw="
e.g. online at
https://github.com/rear/rear/blob/master/doc/rear.8.adoc
and see "KERNEL_CMDLINE" in
usr/share/rear/conf/default.conf
e.g. currently online at
https://github.com/rear/rear/blob/master/usr/share/rear/conf/default.conf#L144

**Comment by ZENAdmin-Ops** [comment]
Hello,

I have tried entering IP=10.254.242.85 and so on in the Recovery environment, but while the commands are accepted, the IP address is not changed.

When the doc states that you can edit the kernel command line, can you advise how I do this?

Thanks

**Comment by ZENAdmin-Ops** [comment]
OK, I worked this out.
