### ISSUE TITLE
BACKUP=BORG --prefix deprecated --glob-archives could be used instead

### ISSUE THREAD

**Issue by llucps** [rear/rear#3121]
* ReaR version ("/usr/sbin/rear -V"):

Relax-and-Recover 2.7 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):

Debian GNU/Linux 12 (bookworm)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

```
### Add library path
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/systemd/

### Rescue image will be the default (ISO) ###
OUTPUT=ISO
OUTPUT_URL="sshfs://xxx@xxx.xx/."
COPY_AS_IS=("/etc/ssl/private" "/usr/share/file/magic")

### Borg stuff ###
BACKUP=BORG
BORGBACKUP_HOST="xxxx.xxx.xx"
BORGBACKUP_PORT=23
BORGBACKUP_USERNAME="xxxxx"
BORGBACKUP_REPO="/./xxxx-backup"
BORGBACKUP_ARCHIVE_PREFIX="$HOSTNAME"
BORGBACKUP_PRUNE_KEEP_DAILY=14
BORGBACKUP_PRUNE_KEEP_WEEKLY=2
BORGBACKUP_PRUNE_KEEP_MONTHLY=3
BORGBACKUP_COMPRESSION="zlib,5"
COPY_AS_IS_EXCLUDE=("/tmp" "/dev" "/proc" "/sys" "/lost+found" "/home/lost+found/" "/run/" "/var/backup/server/" "/var/backup/websites/")
BORGBACKUP_SHOW_STATS=YES
export BORG_PASSPHRASE="xxxxxxxxxxxxx"
```

* Description of the issue (ideally so that others can reproduce it):

According to Borg documentation the `--prefix` parameter is deprecated and should not be used anymore.

https://borgbackup.readthedocs.io/en/stable/usage/prune.html
https://github.com/borgbackup/borg/issues/7031

In my logs I get this warning:

```
Pruning old backup archives in Borg repository /./xxxx-backup on xxx.xxx.xx
Warning: "--prefix" has been deprecated. Use "--glob-archives 'yourprefix*'" (-a) instead.
```
I'm assuming that although the BORGBACKUP_ARCHIVE_PREFIX="$HOSTNAME" works for now it should be replaced for something like this?

`BORGBACKUP_ARCHIVE_GLOB="$HOSTNAME-*"`

What do you think?
Thanks.

**Comment by llucps** [comment]
@jsmeix According the the release notes the --glob-archives options was introduced on borg 1.2.2 (2022-08-20)

https://github.com/borgbackup/borg/blob/1.2.7/docs/changes.rst#version-122-2022-08-20

And more info here https://github.com/borgbackup/borg/issues/6806

**Comment by schlomo** [comment]
https://github.com/borgbackup/borg/issues/6806#issuecomment-1170319393 actually states that Borg 2.0 will not support the `--prefix` option any more, so the 1.x series presumably will continue to support it.

@llucps can you tell us how much our ReaR code will have to change in order to support Borg 2.x? If this is the only change, then we should just adjust it. But if there are more incompatible changes then we should maybe consider adding a `BORG2` backup method that is fully optimised for the Borg 2.x series. We have also other backup methods (most notably `GALAXY`) where we have multiple backup methods to support multiple versions of the same backup software.
