### ISSUE TITLE
Automatic keyboard configuation fails on Ubuntu 22.04 (and probably other Debian based systems)

### ISSUE THREAD

**Issue by schlomo** [rear/rear#3133]
Debian systems use [setupcon](https://manpages.debian.org/testing/console-setup/setupcon.1.en.html) to configure font and keyboard layout for the console.

Without specifying anything in the configuration ReaR uses `dumpkeys` to backup the keyboard configuration and `loadkeys` to load it again. In my case the `loadkeys` failed with an error about missing `ckbcomp`.

I had to add `ckbcomp` to `PROGS` to fix this, see https://github.com/schlomo/rear-ppdm/commit/bb41f08e47b11cc7c4fa493643911320a9f863ae

Looking at our code it seems to me like we don't consider systems with `setupcon` at all, and I'm wondering if we wouldn't be better off by simply supporting that and automatically including all required files.

In any case, a "small" fix was adding `ckbcomp` which will be part of my next PR

**Comment by jsmeix** [comment]
Only a general side note:

The root cause of most issues with Debian based systems is
that we have nobody from Canonical or Ubuntu or Debian
who actively contributes to ReaR so support for
Debian based systems is what they contribute.

Some time ago I talked to one who works at Canonical
(about something different than disaster recovery)
and by the way I mentioned ReaR but unfortunately
it seems Canonical is not (yet?) sufficiently
interested in actively supporting upstream ReaR.

I am not a Debian or Ubuntu user
(and I won't find time to test things there).
I don't know what Canonical provides to their
customers regarding disaster recovery.
Perhaps something different so they don't need ReaR.
