### ISSUE TITLE
SLES15 SP5: vi: E1187: Failed to source defaults.vim

### ISSUE THREAD

**Issue by abbbi** [rear/rear#3151]
hi,

this is an minor issue as it does not affect functionality but can be fixed quite easily:

Executing "vi" within the bootet recovery iso (sles15 sp5) shields the following error:

```
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

workaround is to create an empty `/root/.vimrc` file.

**Comment by abbbi** [comment]
would

https://github.com/rear/rear/blob/master/usr/share/rear/build/GNU/Linux/130_create_dotfiles.sh

be the right place to simply touch the file?

**Comment by pcahyna** [comment]
I suppose this would work, but I suspect https://github.com/rear/rear/tree/master/usr/share/rear/skel/default/root would be an even better place, as the file is static and if you put it there, you will see just by looking at the directory listing that it is there, instead of having to look inside the code and think about what it is doing.

**Comment by abbbi** [comment]
> I suppose this would work, but I suspect https://github.com/rear/rear/tree/master/usr/share/rear/skel/default/root would be an even better place, as the file is static and if you put it there, you will see just by looking at the directory listing that it is there, instead of having to look inside the code and think about what it is doing.

if the user wants to ship its custom .vimrc file that might be the better place.. yes. But by default? Touching it ifs existant
during dotfiles creation doesnt hurt anyone and would create it if not.

**Comment by pcahyna** [comment]
I don't say it will hurt, but having a static file in the directory structure is easier to understand for developers who sometimes need to check how something happens (I am among them), than having a code to generate it dynamically.

**Comment by jsmeix** [comment]
I can reproduce it.
I will have a look how to solve it properly.

**Comment by jsmeix** [comment]
Offhandedly I think that
dynamically generating something static
is (or at least looks) self-contradicting.

**Comment by pcahyna** [comment]
I would keep dynamic generation of (currently) static .bash_history there though because I hope that we would eventually make it dynamic. For example, it does not make much sense to preload `nano` into history if there is no `nano` in the rescue image. But this issue does not have a high priority for me :-)
