### ISSUE TITLE
SLES15 SP5: Cannot create initrd (found no mkinitrd in the recreated system)

### ISSUE THREAD

**Issue by abbbi** [rear/rear#3152]
Rear 2.7
--

hi,

it appears that

`finalize/SUSE_LINUX/i386/550_rebuild_initramfs.sh`

makes use of the "mkinitrd" executable. This executable has been moved to a special package on SLES15 SP5 called
`dracut-mkinitrd-deprecated`, which seems to be optional and may not be existent on the system backed up.

In reality it seems this "mkinitrd" exectuable is just an wrapper shellscript to call dracut, see the following
discussion:

https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/WKZFPUPW3BQ4GYLI4HIWLJDWANUOBLIT/

However, as the executable may be missing, this can result in recovery to spoil:

```
2024-01-10 13:38:11.294431793 Running mkinitrd...
2024-01-10 13:38:11.298370613 WARNING:
Cannot create initrd (found no mkinitrd in the recreated system).
Check the recreated system (mounted at /mnt/local)
and decide yourself, whether the system will boot or not.
```

maybe it would make sense to implement an fall-back to dracut commands if mkinitrd is not available:

`dracut -f --regenerate-all `

**Comment by abbbi** [comment]
@pcahyna thanks, it may make sense to either port these changes to the SUSE related parts too, or use common code base for this?

**Comment by jsmeix** [comment]
I can reproduce it.
I will have a look how to solve it properly.

**Comment by jsmeix** [comment]
@abbbi 
could you please test if
https://github.com/rear/rear/pull/3155
also works for you?

In particular check your "rear -D recover" log file
for possible issues when dracut is run.

**Comment by jsmeix** [comment]
This issue happens only since SLES15-SP5.
This is the reason why I did not notice it
because I falsely assumed that SLE service packs
do not break backward compatibility without serious reason.

In this case it seems backward compatibility got broken
by accident because a single RPM requirement in one
RPM package (mdadm) was no longer needed and that
single RPM requirement was the only reason why
dracut-mkinitrd-deprecated got installed on SLES15-SP4.

Details:

I installed SLES15-SP4 and there
dracut-mkinitrd-deprecated is installed by default.

In contrast on SLES15-SP5 dracut-mkinitrd-deprecated
is no longer installed by default.

Both on SLES15-SP4 and SLES15-SP5 dracut-mkinitrd-deprecated
belongs to the sle-module-basesystem repository
```
# zypper search -v dracut-mkinitrd-deprecated
...
Name                       ... Repository
dracut-mkinitrd-deprecated ... sle-module-basesystem
```
so on SLES15-SP5 dracut-mkinitrd-deprecated
should be always available to be "just installed".

On SLES15-SP4 dracut-mkinitrd-deprecated
is installed because mdadm requires /sbin/mkinitrd
```
SLES15-SP4: # rpm -e --test dracut-mkinitrd-deprecated
error: Failed dependencies:
/sbin/mkinitrd is needed by (installed) mdadm-4.1-...
```

On SLES15-SP5 mdadm does no longer require /sbin/mkinitrd
```
SLES15-SP5: # rpm -q --changelog mdadm
...
* Thu Nov 24 2022 colyli@suse.com
- mdadm.spec: remove "PreReq: %{_sbindir}/mkinitrd" as it is
  unnecessary now. (bsc#1202352)
```
where `bsc#1202352` is
https://bugzilla.opensuse.org/show_bug.cgi?id=1202352

Therein another openSUSE mail thread
on `factory@lists.opensuse.org` is referenced
https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/GDAZ7TVXS2BAXENVBAMHVXVHLSR7D7NQ/

**Comment by abbbi** [comment]
Tested and can Confirm its working for me, thanks!
