### ISSUE TITLE
questions to the ReaR release cycle - best current version

### ISSUE THREAD

**Issue by Sen5ation** [rear/rear#3169]
Hi there,

We are using relax and recover in a professional environment and were wondering which release version we can use.
The current procedure is that we download the 2.7 release from the repo, apply some patches to it (for our use cases) and then use that version internally.

At the moment the 2.7 release is quite old (June 2022) and we have a lot of bugs, especially in cloud environments. We are wondering when the 2.8 release is planned or (if it is too far away) which (snapshot) version you suggest to use/download here as a base for our internal rear version? Are there ans minor releases for public download?

Best regards
Sebastian

**Comment by jsmeix** [comment]
The ReaR 2.8 release date is not yet planned, see
https://github.com/rear/rear/milestones
```
ReaR v2.8
No due date
```

In general I recommend to try out our latest GitHub master code
because the GitHub master code is the only place where we fix things
and if there are issues it helps when you use exactly the code
where we could fix things.

See the section
"Testing current ReaR upstream GitHub master code" in
https://en.opensuse.org/SDB:Disaster_Recovery
how you can try out our current ReaR GitHub master code
without conflicts with your already installed ReaR version.

In general we at ReaR upstream do not support older ReaR versions.
We at ReaR upstream do not plain reject issues with older ReaR versions
(e.g. we may answer easy to solve questions also for older ReaR versions)
but we do not spend much time on issues with older ReaR versions because
we do not (and cannot) fix issues in released ReaR versions.
Issues in released ReaR versions are not fixed by us (by ReaR upstream).
Issues in released ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (if the fix can be backported with
reasonable effort) by the Linux distributor wherefrom you got ReaR.

When you
"have a lot of bugs, especially in cloud environments",
but you do not report them to us here at ReaR upstream,
usually nothing can get fixed.

Regarding "especially in cloud environments":
Usually we at ReaR upstream do not have "cloud environments"
in particular not when one has to pay for them, so usually
nothing will get fixed for special cloud environments.

I know from various issues here at ReaR upstream that
especially cloud environments are especially problematic
because especially cloud environments are especially
strange how things behave within cloud environments.
In particular strange storage that does not behave same
as usual storage with usual physical harddisks or SSDs
or usual virtual disks of usual QEMU/KVM virtual machines.
Also strange bootloader related things that do not behave
same as usual bootloader things on physical hardware
or on usual QEMU/KVM virtual machines.

In general see the section
"How to contribute to Relax-and-Recover" in
https://en.opensuse.org/SDB:Disaster_Recovery

If you or your company requires a missing feature,
see the sections "Sponsoring"
and "Professional services" in
https://relax-and-recover.org/development/

**Comment by schlomo** [comment]
Hello @Sen5ation most people either find the older versions, e.g. 2.6 or 2.7, sufficient for their use case or they import a current build package from here.

Helping with the implementation of ReaR in a professional context is a big part of the consultancy engagements that we see via [ReaR Professional Support](https://relax-and-recover.org/support/#:~:text=means%20for%20sponsoring-,Professional%20Support,-If%20your%20company) and I kindly ask you to reach out to us for more details on that.

Most new features are the result of either professional users contributing features they find useful or engaging with us to develop the missing features.

I agree with you, BTW, that the lack of regular releases is bad. Unfortunately making a release is a lot of work and so far [nobody is willing to pay for a new release](https://relax-and-recover.org/events/)

**Comment by gdha** [comment]
@Sen5ation  REAR 2.8 is aimed to be released before 2025 - no month can be pinned yet as this must be agreed amongst the ReaR contributors. And, as @schlomo mentioned earlier nobody is willing to pay for it.

**Comment by jsmeix** [comment]
This is sufficiently answered.
