### ISSUE TITLE
Bareos+ReaR: Problem booting the system after successful recovery

### ISSUE THREAD

**Issue by Ram9998** [rear/rear#3187]
* ReaR version ("/usr/sbin/rear -V"): 2.6

* If your ReaR version is not the current version, explain why you can't upgrade:

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
OS_VENDOR=OracleServer
OS_VERSION=8

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
OUTPUT=ISO
ISO_DIR=/backups
BACKUP=BAREOS
BAREOS_CLIENT=VL-BPCACSAPP01
BAREOS_FILESET=LinuxAll
BAREOS_RESTORE_JOB=RestoreOLVM
USE_STATIC_NETWORKING=y
* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): VM (OLVM)

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): UEFI GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): NVME

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
 <details>
  <summary>Screenshot</summary>
  <img src="https://github.com/rear/rear/assets/110440356/a01da010-95e8-47ed-9c9d-23ec889263c5">
</details>

* Description of the issue (ideally so that others can reproduce it):
I'm using Bareos+ReaR. Can't boot from a restored system. Problem installing EFI Boot Manager:
<details>
  <summary>Screenshot</summary>
  <img src="https://github.com/rear/rear/assets/110440356/060e1be0-2ca3-491a-a80a-a4f4bd7f793f">
</details>
 
* Workaround, if any: 

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[rear-VL-BPCACSAPP01.log](https://github.com/rear/rear/files/14787463/rear-VL-BPCACSAPP01.log)

You can drag-drop log files into this editor to create an attachment
or paste verbatim text like command output or file content
by including it between a leading and a closing line of
three backticks like this:

```
verbatim content
```

**Comment by jsmeix** [comment]
I am not a Bareos user so I cannot actually help
with Bareos specific issues.

From what I notice at first glance in your
https://github.com/rear/rear/files/14787463/rear-VL-BPCACSAPP01.log
(excerpts)
```
+ source /usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
...
++ mkdir /mnt/local/var/lib/bareos
mkdir: cannot create directory '/mnt/local/var/lib/bareos': No such file or directory

...

+ source /usr/share/rear/restore/default/900_create_missing_directories.sh
...
mkdir: created directory 'etc'
...
++ chroot /mnt/local /bin/bash --login -c 'chown -v root:root etc'
chroot: failed to run command '/bin/bash': No such file or directory

...

+ source /usr/share/rear/finalize/Linux-i386/670_run_efibootmgr.sh
...
++ test -f /mnt/local//boot/efi/EFI/redhat/grubx64.efi
++ LogPrintError 'Failed to create EFI Boot Manager entries (UEFI bootloader '\''/boot/efi/EFI/redhat/grubx64.efi'\'' not found under target /mnt/local)'
```
it seems the backup or the restore was incomplete
because it looks as if basic directories are missing
in the recreated system under /mnt/local
like /mnt/local/var/lib and /mnt/local/etc
(and many more that 900_create_missing_directories.sh shows)
and also /bin/bash seems to be missing
in the recreated system under /mnt/local
and finally also /mnt/local/boot/efi/EFI/redhat/grubx64.efi
seems to be missing in the recreated system.

Did you actually do what the Bareos restore script
/usr/share/rear/restore/BAREOS/default/400_restore_backup.sh
tells you to do
```
Please verify that the backup has been restored correctly to '/mnt/local'
in the provided shell. When finished, type exit in the shell to continue
recovery.
```
?
