### ISSUE TITLE
recover only disk layout (partitions, logical volumes and filesystems)?

### ISSUE THREAD

**Issue by Framsfex** [rear/rear#3193]
I have tested ReaR only once with Redhat (recovery was a desaster, I will write another message to this topic).
Maybe I have overlooked it in the documentation:

(How) Is it possible to backup+restore ONLY the disk layout with partitions, logical volumes and filesystems but without content?

Background of my question: I use linuxclone (https://fex.belwue.de/linuxtools/linuxclone.html) to backup my files and need only a disk layout recovery., because linuxclone cannot handle LVM.

**Comment by jsmeix** [comment]
@Framsfex 
I assume that ins your
```
backup+restore ONLY the disk layout
with partitions, logical volumes and filesystems
but without content
```
"without content" means without a backup of the files.

Use "rear mkrescue" to only create a bootable
ReaR recovery system that contains info about the
disk layout with partitions, logical volumes and filesystems
but no backup of the files.

To only recreate the disk layout with partitions,
logical volumes and filesystems
but to not restore a backup of the files
there is the **experimental** workflow 'layoutonly'
so instead of "rear recover" (that also restores a backup)
you can try out how far "rear layoutonly" does what you need.
Because 'layoutonly' is **experimental** it may not (yet) do
what you need for your particular intended use case.

Note that you are rather outside of what ReaR is usually
meant to do - which is to recreate a (destroyed) system
as it was before (as much as possible).

**Comment by Framsfex** [comment]
On Fri 2024-04-05 (05:30), Johannes Meixner wrote:

> "without content" means without a backup of the files.

Yes. I should have written it more precise.


> Use "rear mkrescue" to only create a bootable
> ReaR recovery system that contains info about the
> disk layout with partitions, logical volumes and filesystems
> but no backup of the files.
> To only recreate the disk layout with partitions,
> logical volumes and filesystems
> but to not restore a backup of the files

This is what I need! Great.


> there is the **experimental** workflow 'layoutonly'
> so instead of "rear recover" (that also restores a backup)
> you can try out how far "rear layoutonly" does what you need.
> Because 'layoutonly' is **experimental** it may not (yet) do
> what you need for your particular intended use case.

Thanks, I will test it!


> Note that you are rather outside of what ReaR is usually
> meant to do - which is to recreate a (destroyed) system
> as it was before (as much as possible).

Yes, I know, my use case is very special.

-- 
Ullrich Horlacher              Server und Virtualisierung
Rechenzentrum TIK
Universitaet Stuttgart         E-Mail: ***@***.***
Allmandring 30a                Tel:    ++49-711-68565868
70569 Stuttgart (Germany)      WWW:    https://www.tik.uni-stuttgart.de/
***@***.***>
