### ISSUE TITLE
Improve output on missing libraries for systemd core lib

### ISSUE THREAD

**Issue by schlomo** [rear/rear#3283]
on `master` we now have

```
Testing that the recovery system in /var/tmp/rear.AHBCO3wxs3FdARC/rootfs contains a usable system
/usr/lib/x86_64-linux-gnu/systemd/libsystemd-core-255.so requires libraries where 'ldd' shows 'not found'
/usr/lib/x86_64-linux-gnu/systemd/libsystemd-core-255.so requires libsystemd-shared-255.so which was not found by 'ldd' but exists as /var/tmp/rear.AHBCO3wxs3FdARC/rootfs/usr/lib/x86_64-linux-gnu/systemd/libsystemd-shared-255.so
```

thanks to #3250 and I'd like to suggest a small improvement on it:

1. strip the ReaR build including `.../rootfs` from the found library
2. show these lines only in the log and not on the console, because this info is not actionable and we decided to assume that all is well if the missing lib is found somewhere.

**Comment by jsmeix** [comment]
https://github.com/rear/rear/pull/3308
intends to improve this part
```
strip the ReaR build including .../rootfs from the found library
```

**Comment by jsmeix** [comment]
Regarding the second part:
```
show these lines only in the log and not on the console ...
```

I agree but - at least as I currently see - it is
not straightforward to implement it because the message
```
... requires libraries where 'ldd' shows 'not found'
```
is already output when there is any bnary
where 'ldd' shows 'not found'
and only later we find out that the file
where 'ldd' shows 'not found'
actually exists within the recovery system.

Therefore the subsequent message
```
... exists as ...
```
is shown to the user to tell him that
the file where 'ldd' had shown 'not found'
actually exists within the recovery system
so things should be OK with this file
BUT
one cannot rely on that things are actually OK
with this file so the user should better
double check things
SO
this message is actionable
at least to a certain degree.

**Comment by jsmeix** [comment]
More regarding the second part:

We cannot silently rely on the assumption
that all is well if the missing thing is found somewhere.

See
https://github.com/rear/rear/pull/3308#issuecomment-2328139914

**Comment by schlomo** [comment]
> We cannot silently rely on the assumption that all is well if the missing thing is found somewhere.

Totally agree, which is why I want to be able to white-list specific things to be nevertheless OK, for example this systemd core library. Or also the many special libs that some backup software references where we know that they don't exist or exist somewhere as part of the backup software tree.

That way we can slowly reduce the amount of false positives.

**Comment by jsmeix** [comment]
I think with https://github.com/rear/rear/pull/3308 merged
this issue is solved because the first part
```
strip the ReaR build including .../rootfs from the found library
```
is implemented by https://github.com/rear/rear/pull/3308
and the second part
```
show these lines only in the log and not on the console
```
cannot be done because we cannot silently rely on the assumption
that all is well if the missing thing is found somewhere
so we need to show these lines on the user's terminal
to have him informed (in verbose mode).
