### ISSUE TITLE
LVM Snapshots supported?

### ISSUE THREAD

**Issue by X4** [rear/rear#413]
Hi,

this project really looks very exciting! I'm having an LVM setup. Are LVM snapshots supported?

**Comment by gdha** [comment]
@bbeaver Stumbled over this issue - what shall we do with it?

**Comment by X4** [comment]
I think the most usable solution for @gdha and you would be in adding Pre/Post and Event based conditions to ReaR. ReaR could then run custom programs and run/pause/skip based on the return code provided.

**Comment by schlomo** [comment]
ReaR already allows dropping Bash scripts into `/usr/share/rear/*`to extend the different stages as needed. I would hope that this is enough, or do you need something different?

You could easily create a `rear-mylvmbackup` package that adds some files to the ReaR script collection so that those added scripts will be called as part of the regular ReaR execution. Thereby providing the glue between ReaR and mylvmbackup.

This holds true for almost any other extension as well. Of course we are also happy to accept mylvmbackup support as a pull request, if somebody wants to contribute it to ReaR.

**Comment by X4** [comment]
Thank you @shlomo :+1: I'm already perfectly fine with what ReaR provides.

**Comment by DEvil0000** [comment]
Just come accress this ticket since I am looking for the same feature.
using LVM snapshot feature (optinally per LVM volume) while doing the backup is a great thing to create consistent or kind of in sync backups.
Looks like this is still open - correct?

**Comment by gdha** [comment]
@DEvil0000 Yes - the feauture is still open. I've added the label "needs sponsorship" - if you are capable of providing such feature you are most welcome ;-)
