### ISSUE TITLE
SLES12: recovering fails due btrfs subvolume target directory not existing

### ISSUE THREAD

**Issue by abbbi** [rear/rear#497]
recovering a standard SLES12 installation fails:

Creating btrfs-filesystem / on /dev/sda2
Btrfs v3.16+20140829
See http://btrfs.wiki.kernel.org for more information.
````
Turning ON incompat feature 'extref': increased hardlink limit per file to 65536
Turning ON incompat feature 'skinny-metadata': reduced-size metadata extent refs
fs created label (null) on /dev/sda2
        nodesize 16384 leafsize 16384 sectorsize 4096 size 17.77GiB
Mounting filesystem /
Creating btrfs-filesystem /.snapshots on /dev/sda2
Mounting filesystem /.snapshots
Create subvolume '/mnt/local/.snapshots'
Creating btrfs-filesystem /var/tmp on /dev/sda2
Mounting filesystem /var/tmp
An error occurred during layout recreation.
````

looking at the detaile dlogfile:
````
++++ btrfs filesystem show /dev/sda2
+++ new_uuid=ac7ef7e9-9fd6-45c1-8453-029ff966fcb8
+++ '[' 6dc24dde-008f-48ac-9eda-160f736f05ec '!=' ac7ef7e9-9fd6-45c1-8453-029ff966fcb8 ']'
+++ '[' '!' -f /var/lib/rear/layout/fs_uuid_mapping ']'
+++ grep -q 6dc24dde-008f-48ac-9eda-160f736f05ec /var/lib/rear/layout/fs_uuid_mapping
+++ [[ 0 -eq 0 ]]
++++ tail -1
++++ awk '{print $2}'
++++ grep 6dc24dde-008f-48ac-9eda-160f736f05ec /var/lib/rear/layout/fs_uuid_mapping
+++ old_uuid=ac7ef7e9-9fd6-45c1-8453-029ff966fcb8
+++ SED_SCRIPT=';/6dc24dde-008f-48ac-9eda-160f736f05ec/s/ac7ef7e9-9fd6-45c1-8453-029ff966fcb8/ac7ef7e9-9fd6-45c1-8453-029ff966fcb8/g'
+++ sed -i ';/6dc24dde-008f-48ac-9eda-160f736f05ec/s/ac7ef7e9-9fd6-45c1-8453-029ff966fcb8/ac7ef7e9-9fd6-45c1-8453-029ff966fcb8/g' /var/lib/rear/layout/fs_uuid_mapping
+++ LogPrint 'Mounting filesystem /var/tmp'
+++ Log 'Mounting filesystem /var/tmp'
+++ test 1 -gt 0
++++ Stamp
++++ date '+%Y-%m-%d %H:%M:%S '
+++ echo '2014-10-29 10:11:12 Mounting filesystem /var/tmp'
2014-10-29 10:11:12 Mounting filesystem /var/tmp
+++ Print 'Mounting filesystem /var/tmp'
+++ test 1
+++ echo -e 'Mounting filesystem /var/tmp'
+++ btrfs subvolume create /mnt/local/var/tmp
ERROR: can't access '/mnt/local/var'
2014-10-29 10:11:12 An error occurred during layout recreation.
````

indeed `/mnt/local/var` does not exist on the target volume. This is the original filesystem layout of the system the backup was created from (basically  a standard SLES12 installation)
````
linux-60x9:~ # mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=1285608k,nr_inodes=321402,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
/dev/sda2 on / type btrfs (rw,relatime,space_cache)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
/dev/sda2 on /.snapshots type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/tmp type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/opt type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/spool type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/log type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/lib/pgsql type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/lib/named type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/lib/mailman type btrfs (rw,relatime,space_cache)
/dev/sda2 on /boot/grub2/x86_64-efi type btrfs (rw,relatime,space_cache)
/dev/sda2 on /var/crash type btrfs (rw,relatime,space_cache)
/dev/sda2 on /usr/local type btrfs (rw,relatime,space_cache)
/dev/sda2 on /tmp type btrfs (rw,relatime,space_cache)
/dev/sda2 on /srv type btrfs (rw,relatime,space_cache)
/dev/sda2 on /opt type btrfs (rw,relatime,space_cache)
/dev/sda2 on /boot/grub2/i386-pc type btrfs (rw,relatime,space_cache)
/dev/sda3 on /home type xfs (rw,relatime,attr2,inode64,noquota)
````

**Comment by jsmeix** [comment]
Hello Gratien,
very many thanks for all your efforts to integrate my patch
into the mainstream of rear and for your testing!

Of course my further work will be based on the mainstream of rear.

Regaring Fedora:

I will try to change your current fix for Fedora into a generic solution.

I think I know what is different in Fedora's btrfs setup
that my code which is intended to be generic support for btrfs
currently does not work on Fedora:

I have installed Fedora-Live-Workstation-i686-21-5.

During its setup I selected Fedora's btrfs default partitioning scheme.

I got the following:
<pre>
# fdisk -l
...
Device     Boot   Start      End  Sectors  Size Id Type
/dev/sda1  *       2048  1026047  1024000  500M 83 Linux
/dev/sda2       1026048  5220351  4194304    2G 82 Linux swap ...
/dev/sda3       5220352 52428799 47208448 22.5G 83 Linux

# btrfs subvolume list -a /
ID 257 gen 62 top level 5 path <FS_TREE>/root
ID 258 gen 44 top level 5 path <FS_TREE>/home

# btrfs subvolume get-default /
ID 5 (FS_TREE)

# findmnt -t btrfs
TARGET  SOURCE           FSTYPE OPTIONS
/       /dev/sda3[/root] btrfs  rw,relatime,seclabel,space_cache
`-/home /dev/sda3[/home] btrfs  rw,relatime,seclabel,space_cache

# mkdir /tmp/btrfsroot

# mount -t btrfs -o subvolid=0 /dev/sda3 /tmp/btrfsroot

# ls /tmp/btrfsroot     
home  root

# ls /tmp/btrfsroot/root
bin  boot  dev  etc  home  lib  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

# findmnt -t btrfs
TARGET           SOURCE           FSTYPE OPTIONS
/                /dev/sda3[/root] btrfs  rw,relatime,seclabel,space_cache
|-/tmp/btrfsroot /dev/sda3        btrfs  rw,relatime,seclabel,space_cache
`-/home          /dev/sda3[/home] btrfs  rw,relatime,seclabel,space_cache

# cat /etc/fstab | tr -s '[:blank:]'
...
UUID=1b...df / btrfs subvol=root 0 0
UUID=bf...8d /boot ext4 defaults 1 2
UUID=1b...df /home btrfs subvol=home 0 0
UUID=1b...4a swap swap defaults 0 0
</pre>

The crucial difference is that on Fedora what is in the running system mounted at the root of the filesystem tree (i.a. at the '/' mountpoint) is NOT the btrfs default subvolume but the btrfs subvolume "root".

This is shown in /etc/fstab.

Accordingly instead of testing for Fedora's btrfs way via a hardcoded subvolume name "root" by
<pre>
if test "$subvolume_path" = "root" ; then
</pre>
a more generic solution to test for Fedora's btrfs way should be to inspect /etc/fstab what is mounted at the '/' mountpoint and write that information to $LAYOUT_FILE.

**Comment by jsmeix** [comment]
The required information is already provided by my current code:

On SLES 12 I have in disklayout.conf (excerpt):
<pre>
# Format: btrfsdefaultsubvol <device> <mountpoint> <btrfs_subvolume_ID> [<btrfs_subvolume_path>]
btrfsdefaultsubvol /dev/sda2 / 257 @
...
# Format: btrfsmountedsubvolume <device> <subvolume_mountpoint> <mount_options> <btrfs_subvolume_path>
btrfsmountedsubvolume /dev/sda2 / rw,relatime,space_cache @
</pre>
On SLES 12 the btrfs default subvolume is '@' and this one is mounted at the mountpoint '/' (as expected according to how a btrfs default subvolume is meant to be used).

On openSUSE 13.2 I have in disklayout.conf (excerpt):
<pre>
# Format: btrfsdefaultsubvol <device> <mountpoint> <btrfs_subvolume_ID> [<btrfs_subvolume_path>]
btrfsdefaultsubvol /dev/sda2 / 5
...
# Format: btrfsmountedsubvolume <device> <subvolume_mountpoint> <mount_options> <btrfs_subvolume_path>
btrfsmountedsubvolume /dev/sda2 / rw,relatime,space_cache /
</pre>
On openSUSE 13.2 the btrfs default subvolume is the btrfs root subvolume '/' (empty btrfs_subvolume_path for btrfsdefaultsubvol) and that one is mounted at the mountpoint '/' (as expected according to how a btrfs default subvolume is meant to be used).

On Fedora 21 I have in disklayout.conf (excerpt):
<pre>
# Format: btrfsdefaultsubvol <device> <mountpoint> <btrfs_subvolume_ID> [<btrfs_subvolume_path>]
btrfsdefaultsubvol /dev/sda3 / 5
...
# Format: btrfsmountedsubvolume <device> <subvolume_mountpoint> <mount_options> <btrfs_subvolume_path>
btrfsmountedsubvolume /dev/sda3 / rw,relatime,seclabel,space_cache root
</pre>
On Fedora 21 the btrfs default subvolume is the btrfs root subvolume '/' (enpty btrfs_subvolume_path for btrfsdefaultsubvol) but that one is not mounted at the mountpoint '/' instead the btrfs subvolume 'root' is mounted at the mountpoint '/' (in contrast to how a btrfs default subvolume is meant to be used).

Accordingly I think I only need to enhance 13_include_mount_subvolumes_code.sh to deal with the (unexpected) case when not the btrfs default subvolume is mounted at the mountpoint '/' but another btrfs subvolume is mounted there.

I am not a btrfs expert but from my point of view it looks like a misconfiguration (a.k.a. bug) in Fedora 21 how they set up btrfs. I think Fedora should specify as btrfs default subvolume what is mounted at the '/' mountpoint.

Regardless if it is really a misconfiguration or not - I like to have rear working fail-safe because regardless what a Linux distribution does by default, an admin could manually create such an awkward btrfs setup and when then rear does not work it is of course a bug in rear ;-)

**Comment by jsmeix** [comment]
I am testing rear git201501071534 version on Fedora 21
with special adaptions for generic btrfs support on Fedora
via rear-1.16.1-git201501071534.btrfs_generic_fedora.diff
in my openSUSE build service home project "home:jsmeix"
therein source package "rear1161git201501071534btrfsFedora"
that results RPMs rear1161btrfs-1.16.1.fedora-N.M.noarch.rpm

I had two minor issues with Fedora21 that I reported as
https://github.com/rear/rear/issues/531 and https://github.com/rear/rear/issues/532 but basically recovery with generic btrfs support worked for me on Fedora21.

Now I need to re-test if it still works on openSUSE and SLES12...

**Comment by jsmeix** [comment]
I think this issue is now fixed via my last
commit 548965e045ac33c8aa02d5d284d590e7c0846ac9
"Implement basic support for btrfs in a generic way"

Note the "basic support".

Currently recovery works btrfs filesystem by btrfs filesystem.

Therefore it probably fails if there are
"interwoven btrfs subvolume mounts" which means
- a subvolume sv1 on a btrfs on /dev/sdXn
  is mounted at a mountpoint directory
  that belongs to a btrfs on /dev/sdYm
and/or
- a subvolume sv2 on a btrfs on /dev/sdYm
  is mounted at a mountpoint directory
  that belongs to a btrfs on /dev/sdXn

In particular when the mountpoint directories are no plain directories
but also subvolumes sv3 and sv4 on any of the btrfs filesystems.

**Comment by jsmeix** [comment]
FYI

Regarding "full btrfs support" (even for "interwoven mounts"),
see what I above "commented on 10 Dec 2014" regarding
a well separated component type "mount".

Currently recovery works $device by $device e.g.
first everything is done for /dev/sda
then everything is done for /dev/sdb.

But in case of "interwoven mounts" between /dev/sdXn and /dev/sdYm
this $device by $device recovery may fail.

Therefore for "full btrfs support" recovery should be done different:

1. "part" (creating partitions) on all devices,
2. "fs" (creating filesystems) on all partitions
3. "btrfssubvol" (creating btrfs subvolumes) on all btrfs filesystems
4. "mount" (creating mountpoints and mount stuff) for all filesystems and subvolumes.

**Comment by gdha** [comment]
As the current btrfs implementation works on Fedora, SLES and OpenSuSe I declare this version ready for shipping with rear-1.17.

**Comment by gdha** [comment]
added to the release notes so we can close this issue
