### ISSUE TITLE
mbr.bin is not in ISOLINUX (ubuntu 15.04)

### ISSUE THREAD

**Issue by sorintelecom** [rear/rear#584]
In order to use rear in ubuntu 15.04, you must symlink mbr.bin file from  /usr/lib/SYSLINUX/ to /usr/lib/ISOLINUX/ (sudo ln -s /usr/lib/SYSLINUX/mbr.bin /usr/lib/ISOLINUX/).

It is possible to change the rear corresponding script?

**Comment by schlomo** [comment]
I did some checking.

```
$ lsb_release -ds ; dpkg -S /usr/lib/*/mbr.bin /usr/lib/*/mbr/mbr.bin
Ubuntu 14.04.2 LTS
syslinux-legacy: /usr/lib/syslinux-legacy/mbr.bin
syslinux-common: /usr/lib/syslinux/mbr.bin
dpkg-query: no path found matching pattern /usr/lib/*/mbr/mbr.bin
```

```
$ lsb_release -ds ; dpkg -S /usr/lib/*/mbr.bin /usr/lib/*/mbr/mbr.bin 
Ubuntu 15.04
syslinux: /usr/lib/SYSLINUX/mbr.bin
syslinux-common: /usr/lib/syslinux/mbr/mbr.bin
```

The code looking for mbr.bin looks in `$SYSLINUX_DIR` which is set in https://github.com/rear/rear/blob/master/usr/share/rear/lib/bootloader-functions.sh#L48 like this:

```
	if [[ -z "$SYSLINUX_DIR" ]]; then
		for file in /usr/{share,lib,libexec}/*/isolinux.bin ; do
			if [[ -s "$file" ]]; then
				SYSLINUX_DIR="$(dirname $file)"
				break # for loop
			fi
		done
	fi
```

I think the problem is that in 15.04 the mbr.bin file is now not any more found in the same location as isolinux.bin.

The ideal solution would somewhat reorganize the way how we find the various syslinux files and make the searches independant from each other.

I would suggest to create a new function called `find_syslinux_file` that returns the full path to a file given as argument and that searches for that file in "typical" syslinux paths.

**Comment by gdha** [comment]
@schlomo no problem - seems a good idea as such we can mask the complexity per OS distro.

**Comment by gdha** [comment]
@sorintelecom your feedback is welcome if you try the latest version from github http://download.opensuse.org/repositories/Archiving:/Backup:/Rear:/Snapshot/xUbuntu_15.04/all/

**Comment by gdha** [comment]
I think this is OK in the meantime, but did not received conclusive feedback yet
