### ISSUE TITLE
UEFI booting from USB disk

### ISSUE THREAD

**Issue by gdha** [rear/rear#603]
Booting in UEFI mode from an USB disk can be a life saver when UEFI ISO booting is no option, e.g. SLES 11/12 cannot create an UEFI bootable ISO image (yet).
- elilo seems out of the question (as it uses `/etc/elilo.conf` to read what to make bootable; alternative location seems problematic)
- grub.efi might be useable (like we do for ISOs)
- syslinux-efi (if version >6.02) ??

**Comment by gdha** [comment]
See http://askubuntu.com/questions/516730/syslinux-6-02-where-to-and-what-has-to-be-copied-to-create-a-working-manual-in

**Comment by gdha** [comment]
As `ebiso` is now available (http://www.it3.be/2015/10/27/uefi-iso-boot-with-ebiso/) there is no real need for this issue. We implement this feature as a paid service only

**Comment by gdha** [comment]
Re-open this issue when we found a sponsor to implement this missing feature

**Comment by jsmeix** [comment]
@gdha 
I wonder if issues with  "looking for sponsorship"
should be kept open until it is implemented
because otherwise I think in parctice nobody
can find them.

When one clicks at the right under "Labels"
onto "looking for sponsorship" one gets a list
filtered by
<pre>
is:open label:"looking for sponsorship" 
</pre>
which means that closed issues
are excluded by default.

To get all issues with "looking for sponsorship"
one has to manually change the filter to
<pre>
label:"looking for sponsorship"
</pre>
but then it is impossible to decide which ones
are already implemented (and rightfully closed) versus
which ones are not yet implemented (but closed nevertheless).

**Comment by gdha** [comment]
@jsmeix I tend to add *looking for sponsorship* issues on our web pages (http://relax-and-recover.org/support/sponsors) and then close these as they will be kept open forever. No-one is sponsoring anyhow.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/834 and https://github.com/rear/rear/pull/837
I regard this issue as done.

UEFI booting from USB disk/stick is implemented in two parts:
    
Part 1 is this issue https://github.com/rear/rear/issues/603 that
implements support for "rear format --efi" to format
an USB disk/stik with an additional UEFI (FAT) partition.
    
Part 2 is https://github.com/rear/rear/issues/831 that
implements filling the UEFI (FAT) partition on USB disk/stick
with bootloader and creating an appropriate bootloader config.
