### ISSUE TITLE
expire the old noarch rear versions on Fedora Build service

### ISSUE THREAD

**Issue by gdha** [rear/rear#660]
we see now a rear.noarch and a rear.x86_64 version on Fedora Build Service. We should expire the noarch version within a few days..

**Comment by schlomo** [comment]
Just to be sure, was that the story where the conflicting RPM dependencies for different archs are the motivator for going away from noarch?

**Comment by gdha** [comment]
@schlomo indeed that was the main reason of the change (proposed by J Meixner)

**Comment by jsmeix** [comment]
Actually it was @k0da who found the issue and reported it to me via personal mail.

Here what Dinar Valeev wrote in his mail to me:
<pre>
There is last remaining bit, packaging.

We package rear as noarch but do require arch specific
bootloader as rpm requirement. See Require: syslinux

As this is noarch package I propose to change it
to Suggests: syslinux, because we can't make arch
dependent Requirements for noarch packages.

Just checked with Fedora spec, they do it wrong:

BuildArch: noarch
%ifarch %ix86 x86_64
Require: syslinux
%endif

%ifarch ppc ppc64
Require: yaboot
%endif
</pre>

From that I created https://github.com/rear/rear/issues/629
