### ISSUE TITLE
Move DISKLAYOUT_FILE to default.conf?

### ISSUE THREAD

**Issue by schlomo** [rear/rear#678]
When looking at #668 I realized that `DISKLAYOUT_FILE` is defined in many places:

```
$ grep -r DISKLAYOUT_FILE= .
./usr/share/rear/layout/save/GNU/Linux/10_create_layout_file.sh:DISKLAYOUT_FILE=${DISKLAYOUT_FILE:-$VAR_DIR/layout/disklayout.conf}
./usr/share/rear/lib/checklayout-workflow.sh:    DISKLAYOUT_FILE=$TEMP_LAYOUT
./usr/share/rear/lib/mkbackuponly-workflow.sh:	DISKLAYOUT_FILE=$TMP_DIR/backuplayout.conf
./usr/share/rear/lib/savelayout-workflow.sh:    DISKLAYOUT_FILE=$VAR_DIR/layout/disklayout.conf
```

But it is not defined in `default.conf` and the setting in `savelayout-workflow.sh` actually repeats the builtin default in `10_create_layout_file.sh`. 

I suspect that it would be better (more ReaR-like and less error prone) to have the default setting in `default.conf`.

**Comment by jsmeix** [comment]
@gdha 
You added the DISKLAYOUT_FILE to usr/share/rear/conf/default.conf
in the following section:
<pre>
# DRLM (Disaster Recovery Linux Manager) Variables
</pre>

I assume the DISKLAYOUT_FILE variable
does not belog only to DRLM but is a
generic global variable for any disk-layout code.

If I am right I woul like to place the DISKLAYOUT_FILE variable
in a section for generic global variables in default.conf

**Comment by gdha** [comment]
@jsmeix no problem - you may move it

**Comment by jsmeix** [comment]
I relation to https://github.com/rear/rear/issues/708 I think that
neither the DISKLAYOUT_FILE variable
nor a RECOVERY_FS_ROOT variable
belongs into usr/share/rear/conf/default.conf
because those variables are not meant to be
configured by the user, see default.conf
<pre>
# PLEASE NOTE:
#
# * Here we define and describe ALL configuration variables and set them to a sane
#   default. Please do NOT change them here, but rather copy them to site.conf or
#   local.conf
# * Most variables can be set to an empty value (VAR=) which means that this
#   setting is off or set to some automatic mode.
</pre>

I think generic global variables like DISKLAYOUT_FILE
and RECOVERY_FS_ROOT belong into usr/sbin/rear
like SHARE_DIR CONFIG_DIR VAR_DIR LOG_DIR ...

**Comment by gdha** [comment]
@jhoekx what is your opinion on this topic?

**Comment by schlomo** [comment]
What is actually the purpose of making DISKLAYOUT_FILE and RECOVERY_FS_ROOT
a variable?

Whom do you expect in which situation to change it?

Answering those questions will also tell you where to put them.

**Comment by jsmeix** [comment]
My (I cannot speak for the others) actual purpose of using
things like DISKLAYOUT_FILE and RECOVERY_FS_ROOT
is not as a real variable (i.e. where the value is meant to change)
but as a constant that has a meaningful name to avoid
hardcoded meaningless literal values in the scripts.

For me things like DISKLAYOUT_FILE and RECOVERY_FS_ROOT
represent values that rear needs internally to work.

I think we should declare those kind of variables
as bash constants via
<pre>
readonly VAR_DIR="$REAR_DIR_PREFIX/var/lib/rear"
...
readonly DISKLAYOUT_FILE="$VAR_DIR/layout/disklayout.conf"
readonly RECOVERY_FS_ROOT="/mnt/local"
</pre>

I think such rear-internal values can be defined in usr/sbin/rear or
in a separated file (not default.conf) that is sourced by usr/sbin/rear.

**Comment by schlomo** [comment]
+1 for readonly constants. I would put them in the main rear script, unless
you plan to read them also from outside the rear framework, e.g. from the
system-setup scripts in the rescue system.

**Comment by jsmeix** [comment]
I will have readonly constants in the main rear script because this is
simplest and only if really needed have them in a separated file.

Depending on how variables are meant to be used they can be
easily moved from usr/sbin/rear to default.conf or vice versa
and they can be easily declared as readonly or not.

**Comment by jsmeix** [comment]
Of course https://github.com/rear/rear/pull/710 is not yet
the final solution - but it should be a first working step
(at least "rear mkbackup" and "rear recover" still works for me).

**Comment by jsmeix** [comment]
This particular issue about DISKLAYOUT_FILE is fixed.
It is now in usr/sbin/rear
<pre>
# Generic global variables that are not meant to be configured by the user
# (i.e. that do not belong into usr/share/rear/conf/default.conf),
# see https://github.com/rear/rear/issues/678
# and https://github.com/rear/rear/issues/708
# Location of the disklayout.conf file created by savelayout
# (no readonly DISKLAYOUT_FILE because it is also set in checklayout-workflow.sh and mkbackuponly-workflow.sh):
DISKLAYOUT_FILE="$VAR_DIR/layout/disklayout.conf"
</pre>

I close this particular issue.

I will continue to work on this kind of issues
as needed in the future.
