### ISSUE TITLE
Option to specify the rear config file to use

### ISSUE THREAD

**Issue by pavoldomin** [rear/rear#68]
Assume, we want to automate rear backup with the different setup on different days. E.g. ISO & tar.gz to URL on Mondays and OBDR on Fridays. The possible method would be to have option, that tells rear, which config files to use, like, 

``` bash
rear -d /etc/rear.monday/ -v mkrescue 
```

would source local.conf (and other .conf) in _/etc/rear.monday/_.

**Comment by spland30** [comment]
Just an observation. 

First, I believe the user was very clear on the requirement. They outlined the need and then gave examples to further help explain the requirement.

Second, If I were to design this... By **default**, Rear would always use the config file imbedded in the rescue image. However, Rear should also provide an option to override the default configuration by specifying the config file at the command line. It shouldn't have been that difficult to implement this change.

The other question is... where in the documentation does it say that the config file is part of the recue image. I find that the rear documentation is lacking in many areas, I spent weeks trying to get this tool up and running because there was not adequate documentation. Users should not have to read 1000's lines of code to fully understand how the tools works. People don't have time to read code, or run any needless trial buy error tests to understand it's functionality or why the tool is not working as expected.

**Comment by gdha** [comment]
@spland30  Have a look at https://relax-and-recover.org/rear-user-guide/
The @rear/contributors also like to have better documentation as you do, but as usual lack of time is the main cause of running late (really late). The ReaR User Guide sub-project is a attempt to improve this situation. However, my time is limited and every hour I spend on it is unpaid and _I am not an employee_ so I hope you understand my problem...
There are solutions, but I leave it as an exercise for you to find out.
