### ISSUE TITLE
[FR] Specify Bacula jobid in confi

### ISSUE THREAD

**Issue by HazCod** [rear/rear#717]
Currently, the config allows us to specify the volume on beforehand but not the jobid.
(this is possible too in bootstrap.txt of bextract)

It would be good if we could specify the JobId too in the configuration file, so an almost-automatic disaster recovery CD can be built.

**Comment by gdha** [comment]
@HazCod Dag and Jeroen wrote the Bacula integration, but they are not active currently within the rear project. So, no clue who could assist you with the feature request?

**Comment by gdha** [comment]
@HazCod Could you explain with an example?

**Comment by HazCod** [comment]
@gdha As far as I know, when booting the recovery CD for bacula, you need to select the jobid. If we could include that in our config too, users could just insert the CD and it would recover automatically. 
( no user-driven decisions needed )

Jobids here are ids of the backup jobs done by bacula, e.g.:
001 today at 12:00
002 today at 13:00
003  todat at 14:00

So if I want to generate a disaster recovery ISO for the latest backup, I would just fill in the last known JobId in the config file and generate the ISO.

**Comment by gdha** [comment]
@HazCod sounds indeed interesting to keep. Are you able to prepare a pull request for this?

**Comment by HazCod** [comment]
Not at the moment as i'm currently not using rear in my situation, I'm afraid

**Comment by jsmeix** [comment]
I neither use Bacula nor Bareos but according to what I read in
https://github.com/rear/rear/pull/997
there is meanwhile support for a variable
named BAREOS_RESTORE_JOB
which seems to be support for a Bareos job ID.

According to
https://www.bareos.org/en/
"Bareos is a ... fork of the backup project from bacula.org"
which indicates that support for a Bacula job ID
could be implemented in a similar way.

But https://github.com/rear/rear/issues/717#issuecomment-186216176
indicates that at least for now this will not be implemented
so that I close this issue now.

If needed it could be reopened but preferably
a new issue based on a current rear version
should be submitted.
