### ISSUE TITLE
Package dependency error when backing up Debian 8.2 system to USB device 

### ISSUE THREAD

**Issue by jk04au** [rear/rear#720]
My environment
<pre>
Testing date: 2015-11-30
Operating system: Debian 8.2 (jessie)
Package: rear_1.17.2_all.deb
</pre>

I had successfully installed rear with all its dependencies but another dependency showed up when backing up the system to a USB device. 
<pre>
root@debian-8b:/etc/rear# rear -v mkrescue
Relax-and-Recover 1.17.2 / Git
Using log file: /var/log/rear/rear-debian-8b.log
ERROR: Executable extlinux is missing! Please install syslinux-extlinux or alike
Aborting due to an error, check /var/log/rear/rear-debian-8b.log for details
Terminated
</pre>

No errors were observed once extlinux package was installed.
<pre>
apt-get install extlinux
</pre>

This issue seems to be related to Issue #696.

**Comment by gdha** [comment]
Rear adds/checks dependencies on package level for the minimum requirements. `isolinux` belongs to the minimum required packages. However, `extlinux` is an optional package only required with USB. Therefore, we do additional checks in the **prep** phase. That is what you saw during your test run. We assume that the users first try it manually before automating rear.

**Comment by gdha** [comment]
@jk04au are you satisfied with the answer? If you are fine then close this issue. Thanks.

**Comment by jk04au** [comment]
Reading your response, I get the impression that _extlinux_ will remain an optional package and will not be installed automatically when ReaR is installed. However, some time in future, if the user is backing up to the USB device, ReaR will detect _extlinux_ is missing and installs it automatically.  Is that right?

**Comment by schlomo** [comment]
Yes and no. ReaR will notice that the required program extlinux is missing and it will abort asking you - the admin - to install it yourself.

ReaR should not install software *for you*.

We already discussed several times to idea to provide `rear-usb`, `rear-tape`, `rear-everything`... packages that would simply install `rear` and also include the dependencies for the given use case (or all dependencies to use all built-in features of ReaR).

See #250 and #133. #696 is really bug because ISO is the default that ships with ReaR.

I will now close the issue, if you have further questions please feel free to reopen it or to open a new issue.
