### ISSUE TITLE
Create a Synology-integrated application or documentation

### ISSUE THREAD

**Issue by dagwieers** [rear/rear#747]
It would be nice if Synology would ship with something that would enable it out-of-the-box to be used in a standardized way with Relax-and-Recover. What do others think ?

**Comment by schlomo** [comment]
Yes, that would be nice. Since Synology is a NAS I would guess that NFS/CIFS-based backups with PXE boot would be a feasable thing. Most likely a Synology already includes all the server components (NFS, CIFS, DHCP, TFTP) so that the ReaR module would only have to tie them together with useable configuration.

Another thing could be that we don't do PXE but USB-based booting. Then the user should be able to put a USB stick into the NAS box and use a GUI function to create a bootable USB stick for a target system.

BTW, in [ReaR Server Proposal](//www.slideshare.net/schlomo/rear-server-proposal-10) I once collected some thoughts on how to build a ReaR server.

**Comment by gdha** [comment]
Indeed a good idea! Perhaps http://drlm.org/ could be dumped on it? However, it still need tweaks at the client side as well.
On the other, the NAS box can already be used as a NFS storage location, and as such it already supports rear out-of-the-box, no? To use more fancy things, like becoming a PXE boot server then it needs some more configuration...

**Comment by dagwieers** [comment]
Right, my idea was something more integrated. Or in the worst case a section in the documentation of how to configure it in a secure way. NFS is not the most secure solution (unless you have complete control of the infrastructure), I'd much rather prefer something like RBME myself :-)

Since I would like to set this up at home, let me think about it and figure something out to discuss...

**Comment by gdha** [comment]
Synology is easy to configure via the command line to become a NFS server or RSYNC server. As there is no-one interested for sponsor this I close it for the time being.
