### ISSUE TITLE
Business Case: Store the OS backup in both local and remote server

### ISSUE THREAD

**Issue by yin747** [rear/rear#750]
I would like to store system backup in local file system first by using "rear" and then transfer the outputs to centralized backup server with in-house script. As a result, I make two copy of Linux system image. 

My question is How to perform system restore ISO image from remote server?

### local.conf ###
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=nfs://192.168.1.50/var/crash/rear/
BACKUP_URL=file:///fsbackup/
EXCLUDE_RECREATE=( "${EXCLUDE_RECREATE[@]}" "fs:/tmp" "fs:/media"
   "fs:/var/tmp" "fs:/mnt" "fs:/var/crash" 
   "fs:/sys" "fs:/dev" "fs:/proc" "fs:/fsbackup")
NETFS_KEEP_OLD_BACKUP_COPY=

**Comment by gdha** [comment]
If you copy the 2th copy on a NFS server then you can use that to restore on a recovery system. You just have to modify to `local.conf` file entry of `BACKUP_URL` to the new location, e.g.
`BACKUP_URL=nfs://NFS-server/path-to-rear-images/` before starting the `rear -v recover` process.

**Comment by schlomo** [comment]
To further automate the process you could actually have Bash code in your `local.conf` that sets `BACKUP_URL` differently depending on running during recovery or during backup.

Since ReaR is a very simple Bash-based framework it should be also simple for you to integrate your in-house script into ReaR to automatically transfer away the backup after creating it locally.

If you do both you will be rewarded with the full automation that ReaR can provide while still using your internal procedures.

**Comment by yin747** [comment]
Dear gdha,

I used above setting of local.conf. The implementation results are ..
1. The system backup in local file system
2. The rescue ISO image is stored in NFS server.

However, when I used the rescue ISO image for system recovery, the source of system backup is pointed to file:///fsbackup.


Regards,
Samson

**Comment by gdha** [comment]
See also answer in #751
