### ISSUE TITLE
f23: dhclient cannot load /usr/lib64/bind99/libirs-export.so.91 library

### ISSUE THREAD

**Issue by gdha** [rear/rear#772]
The rescue image created on fedora23 boots fine, but we do no get an IP address (via dhclient), because dhclient cannot find the shared object file.
The libraries are there, but the `/lib64/bind99` path is missing in `/etc/ld.so.conf` file.

**Comment by gdha** [comment]
In script `build/GNU/Linux/39_copy_binaries_libraries.sh` there is a call to `ldconfig $v -r "$ROOTFS_DIR" >&8` and it goes clearly over the `/lib/64/bind99` libs, but did not add it the the `/etc/ld/so.conf` file.
Perhaps, we should skip this old fashion why of working and use the more standard way with conf files under `/etc/ld.so.conf.d/` directory?

**Comment by jsmeix** [comment]
Since
https://github.com/rear/rear/commit/d62a555fd3460a618e47e8a6c6288e13cbd940fb
the recovery system could fail to boot, see
https://github.com/rear/rear/issues/1496

**Comment by jsmeix** [comment]
@gdha 
we need a better solution which results a clean recovery system.

**Comment by jsmeix** [comment]
@gdha 
I think - but that is only a guess - that in
https://github.com/rear/rear/commit/d62a555fd3460a618e47e8a6c6288e13cbd940fb
only the new script
rescue/GNU/Linux/550_copy_ldconfig.sh
that copies the /etc/ld.so.conf* stuff to ROOTFS
could be sufficient to fix this issue here
because with the ldconfig config files in ROOTFS
the 'ldconfig' call at the end of the later
build/GNU/Linux/390_copy_binaries_libraries.sh
should "do the right thing".
I.e. I think moving additionally the 'ldconfig' call from
build/GNU/Linux/390_copy_binaries_libraries.sh
into the init scripts of the recovery system
to anothe new script
skel/default/etc/scripts/system-setup.d/01-run-ldconfig.sh
is not needed.

Furthermore I wonder why in
skel/default/etc/scripts/system-setup.d/01-run-ldconfig.sh
the 'ldconfig' call is with the '-X' option?
What is the reason behind why ldconfig must not
update links in the recovery system?
What goes wrong if ldconfig also updated links?

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1502 merged
issues like https://github.com/rear/rear/issues/1494
should now be avoided while it could still work for
special cases like this issue here because now
a ldconfig failure is no longer a fatal error, the
failure is only reported but it does not error out.

**Comment by jsmeix** [comment]
With https://github.com/rear/rear/pull/1521 merged
the whole binaries and libraries copying code is now
cleaned up and simplified.
