### ISSUE TITLE
get rid of progress-bar code

### ISSUE THREAD

**Issue by gdha** [rear/rear#887]
- rear version (/usr/sbin/rear -V): 1.18
- OS version (cat /etc/rear/os.conf or lsb_release  -a): n/a
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): n/a
- Brief description of the issue: issue #874 (2>&8 or >&8 usage)
- Work-around, if any: 

We are not using the progress-bar code for years anymore (the `>&8` redirection), so the question was asked, why not get rid of it and capture the code in the logging (or not)?

**Comment by jsmeix** [comment]
I could do it together with
https://github.com/rear/rear/issues/885

**Comment by jsmeix** [comment]
Only FYI regarding https://github.com/rear/rear/pull/874#issuecomment-227135652 (excerpt):
<pre>
The progress bar mechanism would swallow all data.
</pre>

I assume that with a "tee" method as in https://github.com/rear/rear/issues/885#issuecomment-226787322
it is in general possible to avoid to "swallow all" messages.

With such a "tee" method it should be in general possible
to have all messages at various places at the same time,
e.g. on the terminal puls in the log plus for a progres bar.

**Comment by jsmeix** [comment]
I need to fix all the old deprecated usage of '>&8'
as precondition for https://github.com/rear/rear/issues/885
cf. https://github.com/rear/rear/issues/885#issuecomment-310393496

**Comment by jsmeix** [comment]
This is no longer a precondition
for https://github.com/rear/rear/issues/885
but can be done any time later as needed,
for for an explanation why see
https://github.com/rear/rear/pull/1391#issuecomment-311040948

**Comment by jsmeix** [comment]
Actually with https://github.com/rear/rear/pull/1391 merged
this specific issue here is fixed because via
https://github.com/rear/rear/commit/4f4efb37db4c4ee7d1b05f247101c1680e1f8c31
I replaced all old deprecated usage of '>&8' with '>/dev/null'
so that there is no longer any old deprecated usage of '>&8'.

Regarding how to fix the old deprecated usage of '>&8' properly
I submitted the general issue https://github.com/rear/rear/issues/1395
