### ISSUE TITLE
OUTPUT=ISO, BACKUP=NETFS, OUTPUT/BACKUP_URL=rsync:// does not copy the backup.tar.gz to the remote location?

### ISSUE THREAD

**Issue by eltonyuy** [rear/rear#899]
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): 17.2 and 18
* OS version (cat /etc/rear/os.conf or lsb_release  -a): 
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=6
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=rsync://10.x.x.x/exports
OUTPUT_URL=rsync://10.x.x.x./exports

* Brief description of the issue

I'm trying to do a backup with ouput format NETFS and ISO, over rsync and have what I thing are two issues

1) The backup.tar.gz does not get copied to the remote location. Is that ok? Only the .iso file is. What I have in mind is that after I boot from the .iso, it'll go to the specified rsync server and get the backup.tar.gz from there.  Is that working as designed or it should copy to the remote location? How does the recover part works if the file does not gets copied? Do we have to do that copying on our own?

2) Is there a way to specify a user/password or a remote user other than root with ssh key authentication for the rsync? We want to have a central rsync server to where we are going to generate all backups and  from where we are going to pull all the images to an external site, but we can't give "root" access to every server involved in the backup to the central rsync server.

* Work-around, if any

I changed one line in a script to copy the file to the remote location, but not sure if that'll make rear recover the backup.tar.gz from there, we haven't tried that.

**Comment by gdha** [comment]
@eltonyuy The `BACKUP_URL=rsync://10.x.x.x/exports` was never implemented in rear, because we have the `BACKUP=RSYNC` method. I am not planning to implement this scheme unless it is sponsored, or somebody does it in my behalf.

**Comment by jsmeix** [comment]
Regarding "BACKUP_URL=rsync://..." not implemented:

In current rear master I have implemeted a test for
currently known valid BACKUP_URL schemes,
see https://github.com/rear/rear/issues/842

With current rear master I get:
<pre>
# grep -v '^#' /etc/rear/local.conf
OUTPUT=ISO
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=rsync://10.160.4.244/nfs

# /usr/sbin/rear mkbackup
ERROR: Invalid scheme 'rsync' in
BACKUP_URL 'rsync://10.160.4.244/nfs'
valid schemes: nfs cifs usb tape file iso sshfs ftpfs
Aborting due to an error,
check /root/rear/var/log/rear/rear-e229.log for details
Terminated
</pre>

But I did not do any test for OUTPUT_URL.

**Comment by gdha** [comment]
@jsmeix Thanks for the test.

**Comment by jsmeix** [comment]
I think this issue can be closed as an
"enhancement" that is "looking for sponsorship".

@eltonyuy 
FYI regarding why such issues get closed,
see https://github.com/rear/rear/issues/603#issuecomment-218463947
