### ISSUE TITLE
--help option requires root access

### ISSUE THREAD

**Issue by scr4bble** [rear/rear#921]
* rear version (/usr/sbin/rear -V):
Relax-and-Recover 1.17.2 / Git

$ rear --help
ERROR: Relax-and-Recover needs ROOT privileges!

Maybe it could work even without root privileges.

**Comment by jsmeix** [comment]
From a user's point of view
it could be made working without root privileges
but as it is currently implemented it would require
some exceptional case handling for that.

Currently "rear --help" is implemented as a "help" workflow
and all workflows (i.e. anything that is run by /usr/sbin/rear)
have that test that root runs  /usr/sbin/rear.

Because "man rear" works for any user, I don't think
it is really worth the effort to implement exceptional case
handling when "/usr/sbin/rear --help" outputs its usage
information.

@scr4bble 
if you really think this feature is a must-have,
reopen this issue together with a GitHub pull request
so that we can see hwo you think it should be actually
implemented.
