### ISSUE TITLE
Be more verbose by default

### ISSUE THREAD

**Issue by scr4bble** [rear/rear#934]
* rear version (/usr/sbin/rear -V):
Relax-and-Recover 1.17.2 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
RedHatEnterpriseServer 7

Please consider to make verbose mode as a default behavior.
Maybe some --quiet option could be there for non verbose output.

**Comment by jsmeix** [comment]
See https://github.com/rear/rear/issues/929

The non-verbose mode is intentionally
since version 1.11.0
see https://github.com/rear/rear/issues/929#issuecomment-233609454

But I don't know the reasoning behind why
it is silent by default.

I guess it is "traditional UNIX style" where
commands are by default non-verbose.
