### ISSUE TITLE
Undocumented grub options

### ISSUE THREAD

**Issue by tcerna** [rear/rear#935]
* rear version (/usr/sbin/rear -V):
rear-1.17.2

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
RHEL-7.2 Server

* Brief description of the issue:

If user has installed grub2, it is necessary to generate grub password and specify it in directive GRUB_RESCUE_PASSWORD in /etc/rear/local.conf. 

```
# cat /etc/rear/local.conf
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://$NFS_SERVER_IP/mnt/rear/"
GRUB_RESCUE=1
GRUB_RESCUE_PASSWORD="grub.pbkdf2.sha512...."
```

I found some information about this only in documentation 
http://relax-and-recover.org/usage/#rescue_system

Please add information about grub options GRUB_RESCUE and GRUB_RESCUE_PASSWORD also in manual page. There and in documentation should be also documented information about default user name (rearadmin) or how to set up own user name (probably with variable GRUB_SUPERUSER).

```
# rpm -q grub2
grub2-2.02-0.41.el7.x86_64
```

I'm a little bit confused from behavior on RHEL6 and RHEL7. No grub password is required in RHEL6, is it because of nonexisting grub2? Grub2 is installed in RHEL7 and GRUB_RESCUE_PASSWORD is necessary.

**Comment by jsmeix** [comment]
I am against any duplicated stuff
because that leads to a maintenace nightmare
to always keep duplicated things in sync.

In particular I am against duplicated documentation.

If something is documeted at "this"
then other documentation should not duplicate it
but only point to "this".

I think traditionally UNIX man pages are short
and not menat as the full documentation.

@tcerna 
for your various documentation issues
could you submit GitHub pull requests
so that we have real proposals how you
think things should be fixed.

**Comment by gdha** [comment]
@tcerna The `GRUB_RESCUE` stuff were never my favourite additions to rear and see these as easy test facilities. I prefer to avoid mentioning this in the man-page as it would overload the user with too much details which he probably will never use. It fits more in a developers guide (still to be written and postponed due to lack of free time and lack of sponsoring)

**Comment by jsmeix** [comment]
Regarding GRUB_RESCUE
see also https://github.com/rear/rear/issues/913
in particular https://github.com/rear/rear/issues/913#issuecomment-232654462
and https://github.com/rear/rear/issues/913#issuecomment-232662751

FYI:
My personal opinion abut the GRUB_RESCUE functionality:

I would even recommend to drop that completely.

Reason:

GRUB_RESCUE is (as far as I know) the only functionality
where rear changes the currently running system and
it changes it even in a critical way because it changes
the bootloader of the currently running system.

I would never expect that any kind of "make me a backup"
program run like "rear mkbackup" changes my currently
running system in a substantial way.

I find this GRUB_RESCUE functionality terrifying.

**Comment by schlomo** [comment]
I agree with @jsmeix and also would prefer ReaR to not modify the local system.

**Suggestion**:
Let's rename `GRUB_RESCUE` to `DEVEL_GRUB_RESCUE` to make it transparent that this is a development and testing feature and not meant for production. If people use it in production then at least they know about this.

**Comment by jsmeix** [comment]
I will do that: https://github.com/rear/rear/issues/938
Hopefully next week I will submit a GitHub pull request.

**Comment by jsmeix** [comment]
I close this issue here because as far as I understand it
we agree that GRUB_RESCUE (or its successor)
is not meant for normal usage so that it should
not be mentioned in the man page.

**Comment by tcerna** [comment]
@jsmeix @gdha Sorry but I can't agree with your arguments. When I became tester of rear, I was like an ordinary user and I didn't know how to correctly set and use this tool. I configured rear and I wanted to start rescue mode and there was no item in grub selection with "Rear recover". So this parameter is necessary.

@schlomo  You told that this parameter is only for development and testing. How can ordinary user do recover without specifying this parameters? I don't know.

And what about parameter GRUB_RESCUE_PASSWORD? There is no information about it in man page and neither in documentation. But we were not able to start recover without password. Can I file it as new bug?

**Comment by gozora** [comment]
When dealing bare-metal restore, you can't rely that grub (or any other bootloader) will be available.
For this situation you should use one of the methods specified in [OUTPUT](https://github.com/rear/rear/blob/master/doc/user-guide/03-configuration.adoc), boot from appropriate media and start with restore.

**Comment by jsmeix** [comment]
@tcerna 
I don't know about Red Hat's documentation about rear
and what Red Hat's intended users of rear are
but for SUSE's documentation you may have a look at
https://en.opensuse.org/SDB:Disaster_Recovery
and follow the links at the end in the "See also" section.
