### ISSUE TITLE
Name of the generated ISO or auto-creation of FTP-Directory

### ISSUE THREAD

**Issue by e-it** [rear/rear#984]
* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a): CentOS release 6.7 (Final)

Hello,

I would like to include REAR to my Puppet-Deployment. To do so I would like to use FTP as output_url, which works fine. 

But: The name of the generated iso is `rear-1.iso` in one case, which could be the name of another system aswell. 

In Puppet I managed to create a configuration that adds a FTP-folder to the output_url - but if that folder does not exist the upload fails.

So my questions are:

- Is it possible to create an iso by using the fqdn? 
- Is it possible to auto-create a folder to FTP if it does not exist?

**Comment by jsmeix** [comment]
I testes current GitHub master code
on my SLES12-SP2-RC1 test system with
<pre>
OUTPUT=ISO
OUTPUT_URL=ftp://10.160.4.244/rear
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://10.160.4.244/nfs
</pre>
and on the test host d245 "rear -d -D mkbackup"
results on my NFS and FTP server 10.160.4.244
<pre>
# ls -lh /srv/ftp/rear/
total 159M
-rw------- 1 ftp ftp   62 Aug 25 12:37 README
-rw------- 1 ftp ftp 150M Aug 25 12:37 rear-d245.iso
-rw------- 1 ftp ftp 8.5M Aug 25 12:37 rear.log
-rw------- 1 ftp ftp  262 Aug 25 12:37 VERSION

# ls -lh /nfs/d245
total 700M
-rw------- 1 nobody nogroup 700M Aug 25 12:38 backup.tar.gz
-rw------- 1 nobody nogroup    0 Aug 25 12:37 .lockfile
</pre>

I.e. I get the hostname of the system where "rear mkbackup"
was run in the ISO file "rear-d245.iso" and the backup
in a "d245" directory.

With
<pre>
OUTPUT_URL=ftp://10.160.4.244/rear/$HOSTNAME
</pre>
"rear mkbackup" does not automatically create the
hostname directory on the FTP server but fails with
<pre>
Copying result files '/root/rear/var/lib/rear/output/rear-d245.iso /myreartmp/rear.DfguWh3MnUvQSxk/tmp/VERSION /myreartmp/rear.DfguWh3MnUvQSxk/tmp/README /myreartmp/rear.DfguWh3MnUvQSxk/tmp/rear.log' to ftp location
ERROR: Problem transferring result files to ftp://10.160.4.244/rear/d245
Aborting due to an error, check /root/rear/var/log/rear/rear-d245.log for details
</pre>

But when I manually crate that directory on the FTP server
it "just works".

I.e. when you know in advance the hostnames, create
matching directories in advance on your FTP server.

**Comment by jsmeix** [comment]
Ah!
I did not notice that you wrote "using the fqdn".
See usr/share/rear/conf/default.conf
<pre>
ISO_PREFIX="rear-$HOSTNAME"
</pre>

But I wonder abut your case where the hostname
seems to be "1" - it this really the intended hostname?
If yes, you should not use same hostnames on
different systems.
If no, I think you need to fix that system so that
it has the actually intended hostname.

**Comment by jsmeix** [comment]
FYI:
<pre>
ISO_PREFIX="rear-$( hostname ).$( domainname )"
</pre>
"just works" for me.
